# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_ps7_0_0/base_filter_ps7_0_0.xci
# IP: The module: 'base_filter_ps7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_ps7_0_0/base_filter_ps7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_filter_ps7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_ps7_0_0/base_filter_ps7_0_0.xci
# IP: The module: 'base_filter_ps7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_ps7_0_0/base_filter_ps7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_filter_ps7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
