-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity AddWeighted is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    src1_data_stream_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    src1_data_stream_V_empty_n : IN STD_LOGIC;
    src1_data_stream_V_read : OUT STD_LOGIC;
    src2_data_stream_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    src2_data_stream_V_empty_n : IN STD_LOGIC;
    src2_data_stream_V_read : OUT STD_LOGIC;
    dst_rows_V_dout : IN STD_LOGIC_VECTOR (10 downto 0);
    dst_rows_V_empty_n : IN STD_LOGIC;
    dst_rows_V_read : OUT STD_LOGIC;
    dst_cols_V_dout : IN STD_LOGIC_VECTOR (11 downto 0);
    dst_cols_V_empty_n : IN STD_LOGIC;
    dst_cols_V_read : OUT STD_LOGIC;
    dst_data_stream_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    dst_data_stream_V_full_n : IN STD_LOGIC;
    dst_data_stream_V_write : OUT STD_LOGIC;
    dst_rows_V_out_din : OUT STD_LOGIC_VECTOR (10 downto 0);
    dst_rows_V_out_full_n : IN STD_LOGIC;
    dst_rows_V_out_write : OUT STD_LOGIC;
    dst_cols_V_out_din : OUT STD_LOGIC_VECTOR (11 downto 0);
    dst_cols_V_out_full_n : IN STD_LOGIC;
    dst_cols_V_out_write : OUT STD_LOGIC );
end;


architecture behav of AddWeighted is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_3FE0000000000000 : STD_LOGIC_VECTOR (63 downto 0) := "0011111111100000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv52_0 : STD_LOGIC_VECTOR (51 downto 0) := "0000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv54_0 : STD_LOGIC_VECTOR (53 downto 0) := "000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv12_433 : STD_LOGIC_VECTOR (11 downto 0) := "010000110011";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv11_433 : STD_LOGIC_VECTOR (10 downto 0) := "10000110011";
    constant ap_const_lv12_36 : STD_LOGIC_VECTOR (11 downto 0) := "000000110110";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv12_8 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_const_lv12_9 : STD_LOGIC_VECTOR (11 downto 0) := "000000001001";
    constant ap_const_lv54_3FFFFFFFFFFFFF : STD_LOGIC_VECTOR (53 downto 0) := "111111111111111111111111111111111111111111111111111111";

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal src1_data_stream_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln355_reg_1048 : STD_LOGIC_VECTOR (0 downto 0);
    signal src2_data_stream_V_blk_n : STD_LOGIC;
    signal dst_rows_V_blk_n : STD_LOGIC;
    signal dst_cols_V_blk_n : STD_LOGIC;
    signal dst_data_stream_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter27 : STD_LOGIC := '0';
    signal icmp_ln355_reg_1048_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal dst_rows_V_out_blk_n : STD_LOGIC;
    signal dst_cols_V_out_blk_n : STD_LOGIC;
    signal t_V_4_reg_266 : STD_LOGIC_VECTOR (31 downto 0);
    signal rows_V_fu_302_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal rows_V_reg_1029 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal cols_V_fu_306_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal cols_V_reg_1034 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln354_fu_310_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal i_V_fu_315_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_V_reg_1043 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln355_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter14 : BOOLEAN;
    signal ap_block_state18_pp0_stage0_iter15 : BOOLEAN;
    signal ap_block_state19_pp0_stage0_iter16 : BOOLEAN;
    signal ap_block_state20_pp0_stage0_iter17 : BOOLEAN;
    signal ap_block_state21_pp0_stage0_iter18 : BOOLEAN;
    signal ap_block_state22_pp0_stage0_iter19 : BOOLEAN;
    signal ap_block_state23_pp0_stage0_iter20 : BOOLEAN;
    signal ap_block_state24_pp0_stage0_iter21 : BOOLEAN;
    signal ap_block_state25_pp0_stage0_iter22 : BOOLEAN;
    signal ap_block_state26_pp0_stage0_iter23 : BOOLEAN;
    signal ap_block_state27_pp0_stage0_iter24 : BOOLEAN;
    signal ap_block_state28_pp0_stage0_iter25 : BOOLEAN;
    signal ap_block_state29_pp0_stage0_iter26 : BOOLEAN;
    signal ap_block_state30_pp0_stage0_iter27 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln355_reg_1048_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_1048_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal j_V_fu_326_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal tmp_reg_1057 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_62_reg_1062 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_296_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_i_i_reg_1077 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_299_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_8_i_i_reg_1082 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_286_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal t1_reg_1087 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_291_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal t2_reg_1092 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_277_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_9_i_i_reg_1097 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_281_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sum_reg_1102 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Val2_22_fu_340_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Val2_22_reg_1107 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln833_fu_357_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln833_reg_1112 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln833_reg_1112_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln833_reg_1112_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln837_fu_363_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln837_reg_1118 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln837_reg_1118_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln837_reg_1118_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_20_reg_1124 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_20_reg_1124_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_21_fu_393_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal p_Result_21_reg_1133 : STD_LOGIC_VECTOR (53 downto 0);
    signal man_V_1_fu_397_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal man_V_1_reg_1138 : STD_LOGIC_VECTOR (53 downto 0);
    signal icmp_ln571_fu_403_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln571_reg_1143 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln571_reg_1143_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln571_reg_1143_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal F2_fu_409_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal F2_reg_1149 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln581_fu_415_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln581_reg_1157 : STD_LOGIC_VECTOR (0 downto 0);
    signal F2_6_fu_427_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal F2_6_reg_1163 : STD_LOGIC_VECTOR (11 downto 0);
    signal F2_6_reg_1163_pp0_iter25_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln582_fu_435_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln582_reg_1169 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln582_reg_1169_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln585_fu_441_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln585_reg_1176 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln603_fu_457_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln603_reg_1181 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln603_reg_1181_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln583_fu_471_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln583_reg_1187 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_22_fu_540_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_22_reg_1193 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_24_fu_552_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_24_reg_1198 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln581_fu_577_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln581_reg_1204 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln403_fu_582_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln403_reg_1209 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln581_fu_588_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln581_reg_1214 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln603_6_fu_609_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln603_6_reg_1219 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln621_fu_633_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln621_reg_1225 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln621_3_fu_647_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln621_3_reg_1231 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_3_fu_673_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_3_reg_1238 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_70_reg_1245 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln631_fu_687_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln631_reg_1250 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln635_fu_693_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal zext_ln635_reg_1256 : STD_LOGIC_VECTOR (53 downto 0);
    signal Range2_V_3_fu_697_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal Range2_V_3_reg_1261 : STD_LOGIC_VECTOR (53 downto 0);
    signal Range1_all_zeros_3_fu_709_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_3_reg_1267 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln642_fu_727_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln642_reg_1272 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_25_fu_780_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_25_reg_1278 : STD_LOGIC_VECTOR (7 downto 0);
    signal underflow_fu_919_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_reg_1284 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln658_1_fu_932_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln658_1_reg_1290 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state3 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter22 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter23 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter24 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter25 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter26 : STD_LOGIC := '0';
    signal t_V_reg_255 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state31 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state31 : signal is "none";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal grp_fu_296_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_299_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal rows_V_fu_302_p0 : STD_LOGIC_VECTOR (10 downto 0);
    signal cols_V_fu_306_p0 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_V_fu_343_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_V_5_fu_353_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal tmp_1_i_fu_385_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal trunc_ln556_fu_369_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln461_fu_381_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln581_fu_421_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_64_fu_447_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Val2_s_fu_463_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal sext_ln581_fu_468_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln586_fu_475_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal ashr_ln586_fu_479_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_65_fu_489_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln586_fu_485_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln588_fu_496_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln591_fu_516_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln591_fu_521_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln591_fu_511_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_525_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_23_fu_504_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal qb_fu_533_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_fu_548_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_67_fu_558_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln582_fu_572_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln603_fu_592_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln603_fu_597_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln416_fu_566_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln603_5_fu_603_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pos1_fu_615_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal pos2_fu_624_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_69_fu_639_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln618_fu_620_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln623_fu_653_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal ashr_ln623_fu_657_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal lD_fu_663_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln621_fu_667_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln619_fu_629_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln639_3_fu_715_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln642_fu_703_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln639_fu_721_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln581_fu_733_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln582_fu_741_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln403_fu_753_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln403_3_fu_758_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln403_fu_747_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln581_fu_770_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln603_fu_775_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln604_fu_736_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln403_3_fu_763_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln631_fu_796_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_fu_806_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal and_ln631_fu_801_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_fu_811_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln631_fu_816_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln641_fu_833_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_fu_838_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln639_fu_824_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_fu_828_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln642_fu_853_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln645_fu_849_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln641_fu_843_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln642_3_fu_866_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln639_fu_858_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln639_3_fu_873_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln654_fu_888_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_23_fu_788_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln621_fu_899_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln621_4_fu_904_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln557_fu_915_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_118_fu_893_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln621_5_fu_910_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln658_fu_927_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_fu_881_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_fu_942_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_1_fu_952_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln340_fu_947_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln428_3_fu_970_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln428_fu_974_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln571_fu_980_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln428_fu_938_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln571_fu_985_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln571_4_fu_991_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln571_3_fu_1003_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_fu_957_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln571_fu_1008_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln340_1_fu_1014_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_fu_963_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln571_fu_996_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_277_ce : STD_LOGIC;
    signal grp_fu_281_ce : STD_LOGIC;
    signal grp_fu_286_ce : STD_LOGIC;
    signal grp_fu_291_ce : STD_LOGIC;
    signal grp_fu_296_ce : STD_LOGIC;
    signal grp_fu_299_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;

    component sobel_accel_dadd_udo IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component sobel_accel_dmul_vdy IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component sobel_accel_uitodwdI IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    sobel_accel_dadd_udo_U88 : component sobel_accel_dadd_udo
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => t1_reg_1087,
        din1 => t2_reg_1092,
        ce => grp_fu_277_ce,
        dout => grp_fu_277_p2);

    sobel_accel_dadd_udo_U89 : component sobel_accel_dadd_udo
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_9_i_i_reg_1097,
        din1 => ap_const_lv64_0,
        ce => grp_fu_281_ce,
        dout => grp_fu_281_p2);

    sobel_accel_dmul_vdy_U90 : component sobel_accel_dmul_vdy
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_i_i_reg_1077,
        din1 => ap_const_lv64_3FE0000000000000,
        ce => grp_fu_286_ce,
        dout => grp_fu_286_p2);

    sobel_accel_dmul_vdy_U91 : component sobel_accel_dmul_vdy
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_8_i_i_reg_1082,
        din1 => ap_const_lv64_3FE0000000000000,
        ce => grp_fu_291_ce,
        dout => grp_fu_291_p2);

    sobel_accel_uitodwdI_U92 : component sobel_accel_uitodwdI
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_296_p0,
        ce => grp_fu_296_ce,
        dout => grp_fu_296_p1);

    sobel_accel_uitodwdI_U93 : component sobel_accel_uitodwdI
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_299_p0,
        ce => grp_fu_299_ce,
        dout => grp_fu_299_p1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln354_fu_310_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((icmp_ln354_fu_310_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state3);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter22_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter22 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter23_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter23 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter24_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter24 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter25_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter25 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter26_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter26 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter27_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter27 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
                elsif (((icmp_ln354_fu_310_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter27 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    t_V_4_reg_266_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln355_fu_321_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                t_V_4_reg_266 <= j_V_fu_326_p2;
            elsif (((icmp_ln354_fu_310_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                t_V_4_reg_266 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    t_V_reg_255_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state31)) then 
                t_V_reg_255 <= i_V_reg_1043;
            elsif ((not(((dst_cols_V_out_full_n = ap_const_logic_0) or (dst_rows_V_out_full_n = ap_const_logic_0) or (dst_cols_V_empty_n = ap_const_logic_0) or (dst_rows_V_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                t_V_reg_255 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln355_reg_1048_pp0_iter23_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                F2_6_reg_1163 <= F2_6_fu_427_p3;
                F2_reg_1149 <= F2_fu_409_p2;
                icmp_ln571_reg_1143 <= icmp_ln571_fu_403_p2;
                icmp_ln581_reg_1157 <= icmp_ln581_fu_415_p2;
                icmp_ln582_reg_1169 <= icmp_ln582_fu_435_p2;
                icmp_ln585_reg_1176 <= icmp_ln585_fu_441_p2;
                icmp_ln603_reg_1181 <= icmp_ln603_fu_457_p2;
                icmp_ln833_reg_1112 <= icmp_ln833_fu_357_p2;
                icmp_ln837_reg_1118 <= icmp_ln837_fu_363_p2;
                man_V_1_reg_1138 <= man_V_1_fu_397_p2;
                p_Result_20_reg_1124 <= p_Val2_22_fu_340_p1(63 downto 63);
                    p_Result_21_reg_1133(51 downto 0) <= p_Result_21_fu_393_p1(51 downto 0);
                p_Val2_22_reg_1107 <= p_Val2_22_fu_340_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                F2_6_reg_1163_pp0_iter25_reg <= F2_6_reg_1163;
                icmp_ln355_reg_1048_pp0_iter10_reg <= icmp_ln355_reg_1048_pp0_iter9_reg;
                icmp_ln355_reg_1048_pp0_iter11_reg <= icmp_ln355_reg_1048_pp0_iter10_reg;
                icmp_ln355_reg_1048_pp0_iter12_reg <= icmp_ln355_reg_1048_pp0_iter11_reg;
                icmp_ln355_reg_1048_pp0_iter13_reg <= icmp_ln355_reg_1048_pp0_iter12_reg;
                icmp_ln355_reg_1048_pp0_iter14_reg <= icmp_ln355_reg_1048_pp0_iter13_reg;
                icmp_ln355_reg_1048_pp0_iter15_reg <= icmp_ln355_reg_1048_pp0_iter14_reg;
                icmp_ln355_reg_1048_pp0_iter16_reg <= icmp_ln355_reg_1048_pp0_iter15_reg;
                icmp_ln355_reg_1048_pp0_iter17_reg <= icmp_ln355_reg_1048_pp0_iter16_reg;
                icmp_ln355_reg_1048_pp0_iter18_reg <= icmp_ln355_reg_1048_pp0_iter17_reg;
                icmp_ln355_reg_1048_pp0_iter19_reg <= icmp_ln355_reg_1048_pp0_iter18_reg;
                icmp_ln355_reg_1048_pp0_iter20_reg <= icmp_ln355_reg_1048_pp0_iter19_reg;
                icmp_ln355_reg_1048_pp0_iter21_reg <= icmp_ln355_reg_1048_pp0_iter20_reg;
                icmp_ln355_reg_1048_pp0_iter22_reg <= icmp_ln355_reg_1048_pp0_iter21_reg;
                icmp_ln355_reg_1048_pp0_iter23_reg <= icmp_ln355_reg_1048_pp0_iter22_reg;
                icmp_ln355_reg_1048_pp0_iter24_reg <= icmp_ln355_reg_1048_pp0_iter23_reg;
                icmp_ln355_reg_1048_pp0_iter25_reg <= icmp_ln355_reg_1048_pp0_iter24_reg;
                icmp_ln355_reg_1048_pp0_iter26_reg <= icmp_ln355_reg_1048_pp0_iter25_reg;
                icmp_ln355_reg_1048_pp0_iter2_reg <= icmp_ln355_reg_1048_pp0_iter1_reg;
                icmp_ln355_reg_1048_pp0_iter3_reg <= icmp_ln355_reg_1048_pp0_iter2_reg;
                icmp_ln355_reg_1048_pp0_iter4_reg <= icmp_ln355_reg_1048_pp0_iter3_reg;
                icmp_ln355_reg_1048_pp0_iter5_reg <= icmp_ln355_reg_1048_pp0_iter4_reg;
                icmp_ln355_reg_1048_pp0_iter6_reg <= icmp_ln355_reg_1048_pp0_iter5_reg;
                icmp_ln355_reg_1048_pp0_iter7_reg <= icmp_ln355_reg_1048_pp0_iter6_reg;
                icmp_ln355_reg_1048_pp0_iter8_reg <= icmp_ln355_reg_1048_pp0_iter7_reg;
                icmp_ln355_reg_1048_pp0_iter9_reg <= icmp_ln355_reg_1048_pp0_iter8_reg;
                icmp_ln571_reg_1143_pp0_iter25_reg <= icmp_ln571_reg_1143;
                icmp_ln571_reg_1143_pp0_iter26_reg <= icmp_ln571_reg_1143_pp0_iter25_reg;
                icmp_ln582_reg_1169_pp0_iter25_reg <= icmp_ln582_reg_1169;
                icmp_ln603_reg_1181_pp0_iter25_reg <= icmp_ln603_reg_1181;
                icmp_ln833_reg_1112_pp0_iter25_reg <= icmp_ln833_reg_1112;
                icmp_ln833_reg_1112_pp0_iter26_reg <= icmp_ln833_reg_1112_pp0_iter25_reg;
                icmp_ln837_reg_1118_pp0_iter25_reg <= icmp_ln837_reg_1118;
                icmp_ln837_reg_1118_pp0_iter26_reg <= icmp_ln837_reg_1118_pp0_iter25_reg;
                p_Result_20_reg_1124_pp0_iter25_reg <= p_Result_20_reg_1124;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln355_reg_1048_pp0_iter24_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                Range1_all_ones_3_reg_1238 <= Range1_all_ones_3_fu_673_p2;
                Range1_all_zeros_3_reg_1267 <= Range1_all_zeros_3_fu_709_p2;
                Range2_V_3_reg_1261 <= Range2_V_3_fu_697_p2;
                and_ln403_reg_1209 <= and_ln403_fu_582_p2;
                and_ln581_reg_1204 <= and_ln581_fu_577_p2;
                and_ln603_6_reg_1219 <= and_ln603_6_fu_609_p2;
                and_ln642_reg_1272 <= and_ln642_fu_727_p2;
                icmp_ln621_reg_1225 <= icmp_ln621_fu_633_p2;
                icmp_ln631_reg_1250 <= icmp_ln631_fu_687_p2;
                or_ln581_reg_1214 <= or_ln581_fu_588_p2;
                p_Result_22_reg_1193 <= p_Val2_23_fu_504_p3(7 downto 7);
                p_Val2_24_reg_1198 <= p_Val2_24_fu_552_p2;
                tmp_70_reg_1245 <= pos2_fu_624_p2(11 downto 11);
                trunc_ln583_reg_1187 <= trunc_ln583_fu_471_p1;
                xor_ln621_3_reg_1231 <= xor_ln621_3_fu_647_p2;
                    zext_ln635_reg_1256(31 downto 0) <= zext_ln635_fu_693_p1(31 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((dst_cols_V_out_full_n = ap_const_logic_0) or (dst_rows_V_out_full_n = ap_const_logic_0) or (dst_cols_V_empty_n = ap_const_logic_0) or (dst_rows_V_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                cols_V_reg_1034 <= cols_V_fu_306_p1;
                rows_V_reg_1029 <= rows_V_fu_302_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_V_reg_1043 <= i_V_fu_315_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln355_reg_1048 <= icmp_ln355_fu_321_p2;
                icmp_ln355_reg_1048_pp0_iter1_reg <= icmp_ln355_reg_1048;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln355_reg_1048_pp0_iter25_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                or_ln658_1_reg_1290 <= or_ln658_1_fu_932_p2;
                p_Val2_25_reg_1278 <= p_Val2_25_fu_780_p3;
                underflow_reg_1284 <= underflow_fu_919_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln355_reg_1048_pp0_iter22_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                sum_reg_1102 <= grp_fu_281_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln355_reg_1048_pp0_iter12_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                t1_reg_1087 <= grp_fu_286_p2;
                t2_reg_1092 <= grp_fu_291_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln355_reg_1048 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_62_reg_1062 <= src2_data_stream_V_dout;
                tmp_reg_1057 <= src1_data_stream_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln355_reg_1048_pp0_iter6_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_8_i_i_reg_1082 <= grp_fu_299_p1;
                tmp_i_i_reg_1077 <= grp_fu_296_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln355_reg_1048_pp0_iter17_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_9_i_i_reg_1097 <= grp_fu_277_p2;
            end if;
        end if;
    end process;
    p_Result_21_reg_1133(53 downto 52) <= "01";
    zext_ln635_reg_1256(53 downto 32) <= "0000000000000000000000";

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, dst_rows_V_empty_n, dst_cols_V_empty_n, dst_rows_V_out_full_n, dst_cols_V_out_full_n, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter27, icmp_ln354_fu_310_p2, ap_CS_fsm_state2, icmp_ln355_fu_321_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter26)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((dst_cols_V_out_full_n = ap_const_logic_0) or (dst_rows_V_out_full_n = ap_const_logic_0) or (dst_cols_V_empty_n = ap_const_logic_0) or (dst_rows_V_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln354_fu_310_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln355_fu_321_p2 = ap_const_lv1_1))) and not(((ap_enable_reg_pp0_iter26 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter26 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln355_fu_321_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state31;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state31 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    F2_6_fu_427_p3 <= 
        F2_fu_409_p2 when (icmp_ln581_fu_415_p2(0) = '1') else 
        sub_ln581_fu_421_p2;
    F2_fu_409_p2 <= std_logic_vector(unsigned(ap_const_lv12_433) - unsigned(zext_ln461_fu_381_p1));
    Range1_all_ones_3_fu_673_p2 <= (icmp_ln621_fu_633_p2 and and_ln621_fu_667_p2);
    Range1_all_ones_fu_828_p2 <= (select_ln631_fu_816_p3 and Range1_all_ones_3_reg_1238);
    Range1_all_zeros_3_fu_709_p2 <= "1" when (p_Val2_s_fu_463_p3 = ap_const_lv54_0) else "0";
    Range1_all_zeros_fu_838_p2 <= (ap_const_lv1_1 xor Range1_all_ones_3_reg_1238);
    Range2_V_3_fu_697_p2 <= std_logic_vector(shift_right(unsigned(p_Val2_s_fu_463_p3),to_integer(unsigned('0' & zext_ln635_fu_693_p1(31-1 downto 0)))));
    Range2_all_ones_fu_811_p2 <= "1" when (Range2_V_3_reg_1261 = r_V_fu_806_p2) else "0";
    add_ln591_fu_516_p2 <= std_logic_vector(signed(ap_const_lv12_FFF) + signed(F2_reg_1149));
    and_ln340_1_fu_1014_p2 <= (xor_ln571_fu_1008_p2 and or_ln340_fu_957_p2);
    and_ln340_fu_947_p2 <= (xor_ln340_fu_942_p2 and or_ln658_1_reg_1290);
    and_ln403_3_fu_758_p2 <= (xor_ln403_fu_753_p2 and and_ln581_reg_1204);
    and_ln403_fu_582_p2 <= (p_Result_22_fu_540_p3 and and_ln581_fu_577_p2);
    and_ln428_3_fu_970_p2 <= (icmp_ln837_reg_1118_pp0_iter26_reg and icmp_ln833_reg_1112_pp0_iter26_reg);
    and_ln428_fu_938_p2 <= (icmp_ln837_reg_1118_pp0_iter26_reg and icmp_ln833_reg_1112_pp0_iter26_reg);
    and_ln557_fu_915_p2 <= (p_Result_20_reg_1124_pp0_iter25_reg and icmp_ln621_reg_1225);
    and_ln571_fu_980_p2 <= (xor_ln428_fu_974_p2 and icmp_ln571_reg_1143_pp0_iter26_reg);
    and_ln581_fu_577_p2 <= (xor_ln582_fu_572_p2 and icmp_ln581_reg_1157);
    and_ln603_5_fu_603_p2 <= (xor_ln416_fu_566_p2 and or_ln603_fu_597_p2);
    and_ln603_6_fu_609_p2 <= (and_ln603_5_fu_603_p2 and and_ln403_fu_582_p2);
    and_ln603_fu_775_p2 <= (xor_ln581_fu_770_p2 and icmp_ln603_reg_1181_pp0_iter25_reg);
    and_ln621_4_fu_904_p2 <= (xor_ln621_fu_899_p2 and p_Result_23_fu_788_p3);
    and_ln621_5_fu_910_p2 <= (p_Result_20_reg_1124_pp0_iter25_reg and and_ln621_4_fu_904_p2);
    and_ln621_fu_667_p2 <= (xor_ln621_3_fu_647_p2 and lD_fu_663_p1);
    and_ln631_fu_801_p2 <= (xor_ln631_fu_796_p2 and icmp_ln631_reg_1250);
    and_ln639_fu_824_p2 <= (xor_ln621_3_reg_1231 and icmp_ln631_reg_1250);
    and_ln641_fu_843_p2 <= (icmp_ln641_fu_833_p2 and Range1_all_zeros_fu_838_p2);
    and_ln642_fu_727_p2 <= (or_ln639_fu_721_p2 and icmp_ln642_fu_703_p2);
    and_ln654_fu_888_p2 <= (select_ln639_fu_858_p3 and and_ln603_6_reg_1219);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state31 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(src1_data_stream_V_empty_n, src2_data_stream_V_empty_n, dst_data_stream_V_full_n, ap_enable_reg_pp0_iter1, icmp_ln355_reg_1048, ap_enable_reg_pp0_iter27, icmp_ln355_reg_1048_pp0_iter26_reg)
    begin
                ap_block_pp0_stage0_01001 <= (((icmp_ln355_reg_1048_pp0_iter26_reg = ap_const_lv1_0) and (dst_data_stream_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((icmp_ln355_reg_1048 = ap_const_lv1_0) and (src2_data_stream_V_empty_n = ap_const_logic_0)) or ((icmp_ln355_reg_1048 = ap_const_lv1_0) and (src1_data_stream_V_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(src1_data_stream_V_empty_n, src2_data_stream_V_empty_n, dst_data_stream_V_full_n, ap_enable_reg_pp0_iter1, icmp_ln355_reg_1048, ap_enable_reg_pp0_iter27, icmp_ln355_reg_1048_pp0_iter26_reg)
    begin
                ap_block_pp0_stage0_11001 <= (((icmp_ln355_reg_1048_pp0_iter26_reg = ap_const_lv1_0) and (dst_data_stream_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((icmp_ln355_reg_1048 = ap_const_lv1_0) and (src2_data_stream_V_empty_n = ap_const_logic_0)) or ((icmp_ln355_reg_1048 = ap_const_lv1_0) and (src1_data_stream_V_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(src1_data_stream_V_empty_n, src2_data_stream_V_empty_n, dst_data_stream_V_full_n, ap_enable_reg_pp0_iter1, icmp_ln355_reg_1048, ap_enable_reg_pp0_iter27, icmp_ln355_reg_1048_pp0_iter26_reg)
    begin
                ap_block_pp0_stage0_subdone <= (((icmp_ln355_reg_1048_pp0_iter26_reg = ap_const_lv1_0) and (dst_data_stream_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((icmp_ln355_reg_1048 = ap_const_lv1_0) and (src2_data_stream_V_empty_n = ap_const_logic_0)) or ((icmp_ln355_reg_1048 = ap_const_lv1_0) and (src1_data_stream_V_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, dst_rows_V_empty_n, dst_cols_V_empty_n, dst_rows_V_out_full_n, dst_cols_V_out_full_n)
    begin
                ap_block_state1 <= ((dst_cols_V_out_full_n = ap_const_logic_0) or (dst_rows_V_out_full_n = ap_const_logic_0) or (dst_cols_V_empty_n = ap_const_logic_0) or (dst_rows_V_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state10_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage0_iter14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage0_iter15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp0_stage0_iter16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state20_pp0_stage0_iter17 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state21_pp0_stage0_iter18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state22_pp0_stage0_iter19 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state23_pp0_stage0_iter20 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state24_pp0_stage0_iter21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state25_pp0_stage0_iter22 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state26_pp0_stage0_iter23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state27_pp0_stage0_iter24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state28_pp0_stage0_iter25 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state29_pp0_stage0_iter26 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state30_pp0_stage0_iter27_assign_proc : process(dst_data_stream_V_full_n, icmp_ln355_reg_1048_pp0_iter26_reg)
    begin
                ap_block_state30_pp0_stage0_iter27 <= ((icmp_ln355_reg_1048_pp0_iter26_reg = ap_const_lv1_0) and (dst_data_stream_V_full_n = ap_const_logic_0));
    end process;

        ap_block_state3_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_pp0_stage0_iter1_assign_proc : process(src1_data_stream_V_empty_n, src2_data_stream_V_empty_n, icmp_ln355_reg_1048)
    begin
                ap_block_state4_pp0_stage0_iter1 <= (((icmp_ln355_reg_1048 = ap_const_lv1_0) and (src2_data_stream_V_empty_n = ap_const_logic_0)) or ((icmp_ln355_reg_1048 = ap_const_lv1_0) and (src1_data_stream_V_empty_n = ap_const_logic_0)));
    end process;

        ap_block_state5_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state3_assign_proc : process(icmp_ln355_fu_321_p2)
    begin
        if ((icmp_ln355_fu_321_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, icmp_ln354_fu_310_p2, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln354_fu_310_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter27, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23, ap_enable_reg_pp0_iter24, ap_enable_reg_pp0_iter25, ap_enable_reg_pp0_iter26)
    begin
        if (((ap_enable_reg_pp0_iter27 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter26 = ap_const_logic_0) and (ap_enable_reg_pp0_iter25 = ap_const_logic_0) and (ap_enable_reg_pp0_iter24 = ap_const_logic_0) and (ap_enable_reg_pp0_iter23 = ap_const_logic_0) and (ap_enable_reg_pp0_iter22 = ap_const_logic_0) and (ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    ashr_ln586_fu_479_p2 <= std_logic_vector(shift_right(signed(p_Val2_s_fu_463_p3),to_integer(unsigned('0' & zext_ln586_fu_475_p1(31-1 downto 0)))));
    ashr_ln623_fu_657_p2 <= std_logic_vector(shift_right(signed(p_Val2_s_fu_463_p3),to_integer(unsigned('0' & zext_ln623_fu_653_p1(31-1 downto 0)))));
    cols_V_fu_306_p0 <= dst_cols_V_dout;
        cols_V_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(cols_V_fu_306_p0),32));

    deleted_zeros_fu_881_p3 <= 
        select_ln639_fu_858_p3 when (and_ln603_6_reg_1219(0) = '1') else 
        select_ln639_3_fu_873_p3;

    dst_cols_V_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, dst_cols_V_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dst_cols_V_blk_n <= dst_cols_V_empty_n;
        else 
            dst_cols_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    dst_cols_V_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, dst_cols_V_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dst_cols_V_out_blk_n <= dst_cols_V_out_full_n;
        else 
            dst_cols_V_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dst_cols_V_out_din <= dst_cols_V_dout;

    dst_cols_V_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, dst_rows_V_empty_n, dst_cols_V_empty_n, dst_rows_V_out_full_n, dst_cols_V_out_full_n)
    begin
        if ((not(((dst_cols_V_out_full_n = ap_const_logic_0) or (dst_rows_V_out_full_n = ap_const_logic_0) or (dst_cols_V_empty_n = ap_const_logic_0) or (dst_rows_V_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dst_cols_V_out_write <= ap_const_logic_1;
        else 
            dst_cols_V_out_write <= ap_const_logic_0;
        end if; 
    end process;


    dst_cols_V_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, dst_rows_V_empty_n, dst_cols_V_empty_n, dst_rows_V_out_full_n, dst_cols_V_out_full_n)
    begin
        if ((not(((dst_cols_V_out_full_n = ap_const_logic_0) or (dst_rows_V_out_full_n = ap_const_logic_0) or (dst_cols_V_empty_n = ap_const_logic_0) or (dst_rows_V_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dst_cols_V_read <= ap_const_logic_1;
        else 
            dst_cols_V_read <= ap_const_logic_0;
        end if; 
    end process;


    dst_data_stream_V_blk_n_assign_proc : process(dst_data_stream_V_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter27, icmp_ln355_reg_1048_pp0_iter26_reg)
    begin
        if (((icmp_ln355_reg_1048_pp0_iter26_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then 
            dst_data_stream_V_blk_n <= dst_data_stream_V_full_n;
        else 
            dst_data_stream_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dst_data_stream_V_din <= 
        select_ln340_fu_963_p3 when (and_ln340_1_fu_1014_p2(0) = '1') else 
        select_ln571_fu_996_p3;

    dst_data_stream_V_write_assign_proc : process(ap_enable_reg_pp0_iter27, icmp_ln355_reg_1048_pp0_iter26_reg, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln355_reg_1048_pp0_iter26_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            dst_data_stream_V_write <= ap_const_logic_1;
        else 
            dst_data_stream_V_write <= ap_const_logic_0;
        end if; 
    end process;


    dst_rows_V_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, dst_rows_V_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dst_rows_V_blk_n <= dst_rows_V_empty_n;
        else 
            dst_rows_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    dst_rows_V_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, dst_rows_V_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dst_rows_V_out_blk_n <= dst_rows_V_out_full_n;
        else 
            dst_rows_V_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dst_rows_V_out_din <= dst_rows_V_dout;

    dst_rows_V_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, dst_rows_V_empty_n, dst_cols_V_empty_n, dst_rows_V_out_full_n, dst_cols_V_out_full_n)
    begin
        if ((not(((dst_cols_V_out_full_n = ap_const_logic_0) or (dst_rows_V_out_full_n = ap_const_logic_0) or (dst_cols_V_empty_n = ap_const_logic_0) or (dst_rows_V_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dst_rows_V_out_write <= ap_const_logic_1;
        else 
            dst_rows_V_out_write <= ap_const_logic_0;
        end if; 
    end process;


    dst_rows_V_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, dst_rows_V_empty_n, dst_cols_V_empty_n, dst_rows_V_out_full_n, dst_cols_V_out_full_n)
    begin
        if ((not(((dst_cols_V_out_full_n = ap_const_logic_0) or (dst_rows_V_out_full_n = ap_const_logic_0) or (dst_cols_V_empty_n = ap_const_logic_0) or (dst_rows_V_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dst_rows_V_read <= ap_const_logic_1;
        else 
            dst_rows_V_read <= ap_const_logic_0;
        end if; 
    end process;

    empty_118_fu_893_p2 <= (ap_const_lv1_1 xor and_ln654_fu_888_p2);

    grp_fu_277_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_277_ce <= ap_const_logic_1;
        else 
            grp_fu_277_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_281_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_281_ce <= ap_const_logic_1;
        else 
            grp_fu_281_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_286_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_286_ce <= ap_const_logic_1;
        else 
            grp_fu_286_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_291_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_291_ce <= ap_const_logic_1;
        else 
            grp_fu_291_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_296_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_296_ce <= ap_const_logic_1;
        else 
            grp_fu_296_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_296_p0 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_1057),32));

    grp_fu_299_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_299_ce <= ap_const_logic_1;
        else 
            grp_fu_299_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_299_p0 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_62_reg_1062),32));
    i_V_fu_315_p2 <= std_logic_vector(unsigned(t_V_reg_255) + unsigned(ap_const_lv32_1));
    icmp_ln354_fu_310_p2 <= "1" when (t_V_reg_255 = rows_V_reg_1029) else "0";
    icmp_ln355_fu_321_p2 <= "1" when (t_V_4_reg_266 = cols_V_reg_1034) else "0";
    icmp_ln571_fu_403_p2 <= "1" when (trunc_ln556_fu_369_p1 = ap_const_lv63_0) else "0";
    icmp_ln581_fu_415_p2 <= "1" when (signed(F2_fu_409_p2) > signed(ap_const_lv12_0)) else "0";
    icmp_ln582_fu_435_p2 <= "1" when (tmp_V_fu_343_p4 = ap_const_lv11_433) else "0";
    icmp_ln585_fu_441_p2 <= "1" when (unsigned(F2_6_fu_427_p3) < unsigned(ap_const_lv12_36)) else "0";
    icmp_ln591_fu_511_p2 <= "1" when (signed(F2_reg_1149) > signed(ap_const_lv12_36)) else "0";
    icmp_ln603_fu_457_p2 <= "1" when (tmp_64_fu_447_p4 = ap_const_lv9_0) else "0";
    icmp_ln621_fu_633_p2 <= "1" when (signed(pos1_fu_615_p2) < signed(ap_const_lv12_36)) else "0";
    icmp_ln631_fu_687_p2 <= "1" when (signed(pos2_fu_624_p2) < signed(ap_const_lv12_36)) else "0";
    icmp_ln641_fu_833_p2 <= "1" when (Range2_V_3_reg_1261 = ap_const_lv54_0) else "0";
    icmp_ln642_fu_703_p2 <= "1" when (pos2_fu_624_p2 = ap_const_lv12_36) else "0";
    icmp_ln833_fu_357_p2 <= "1" when (tmp_V_fu_343_p4 = ap_const_lv11_7FF) else "0";
    icmp_ln837_fu_363_p2 <= "0" when (tmp_V_5_fu_353_p1 = ap_const_lv52_0) else "1";

    internal_ap_ready_assign_proc : process(icmp_ln354_fu_310_p2, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln354_fu_310_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    j_V_fu_326_p2 <= std_logic_vector(unsigned(t_V_4_reg_266) + unsigned(ap_const_lv32_1));
    lD_fu_663_p1 <= ashr_ln623_fu_657_p2(1 - 1 downto 0);
    man_V_1_fu_397_p2 <= std_logic_vector(unsigned(ap_const_lv54_0) - unsigned(p_Result_21_fu_393_p1));
    or_ln340_fu_957_p2 <= (xor_ln340_fu_942_p2 or xor_ln340_1_fu_952_p2);
    or_ln571_3_fu_1003_p2 <= (icmp_ln571_reg_1143_pp0_iter26_reg or and_ln428_fu_938_p2);
    or_ln571_4_fu_991_p2 <= (underflow_reg_1284 or or_ln571_fu_985_p2);
    or_ln571_fu_985_p2 <= (and_ln571_fu_980_p2 or and_ln428_fu_938_p2);
    or_ln581_fu_588_p2 <= (icmp_ln582_reg_1169 or icmp_ln581_reg_1157);
    or_ln603_fu_597_p2 <= (xor_ln603_fu_592_p2 or or_ln581_fu_588_p2);
    or_ln639_fu_721_p2 <= (xor_ln639_3_fu_715_p2 or tmp_69_fu_639_p3);
    or_ln645_fu_849_p2 <= (xor_ln621_3_reg_1231 or Range1_all_zeros_3_reg_1267);
    or_ln658_1_fu_932_p2 <= (or_ln658_fu_927_p2 or deleted_zeros_fu_881_p3);
    or_ln658_fu_927_p2 <= (xor_ln621_fu_899_p2 or p_Result_20_reg_1124_pp0_iter25_reg);
    p_Result_21_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_i_fu_385_p3),54));
    p_Result_22_fu_540_p3 <= p_Val2_23_fu_504_p3(7 downto 7);
    p_Result_23_fu_788_p3 <= p_Val2_25_fu_780_p3(7 downto 7);
    p_Result_s_fu_525_p3 <= p_Val2_s_fu_463_p3(to_integer(unsigned(zext_ln591_fu_521_p1)) downto to_integer(unsigned(zext_ln591_fu_521_p1))) when (to_integer(unsigned(zext_ln591_fu_521_p1))>= 0 and to_integer(unsigned(zext_ln591_fu_521_p1))<=53) else "-";
    p_Val2_22_fu_340_p1 <= sum_reg_1102;
    p_Val2_23_fu_504_p3 <= 
        trunc_ln586_fu_485_p1 when (icmp_ln585_reg_1176(0) = '1') else 
        select_ln588_fu_496_p3;
    p_Val2_24_fu_552_p2 <= std_logic_vector(unsigned(p_Val2_23_fu_504_p3) + unsigned(zext_ln415_fu_548_p1));
    p_Val2_25_fu_780_p3 <= 
        shl_ln604_fu_736_p2 when (and_ln603_fu_775_p2(0) = '1') else 
        select_ln403_3_fu_763_p3;
    p_Val2_s_fu_463_p3 <= 
        man_V_1_reg_1138 when (p_Result_20_reg_1124(0) = '1') else 
        p_Result_21_reg_1133;
    pos1_fu_615_p2 <= std_logic_vector(unsigned(ap_const_lv12_8) + unsigned(F2_reg_1149));
    pos2_fu_624_p2 <= std_logic_vector(unsigned(ap_const_lv12_9) + unsigned(F2_reg_1149));
    qb_fu_533_p3 <= 
        p_Result_20_reg_1124 when (icmp_ln591_fu_511_p2(0) = '1') else 
        p_Result_s_fu_525_p3;
    r_V_fu_806_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv54_3FFFFFFFFFFFFF),to_integer(unsigned('0' & zext_ln635_reg_1256(31-1 downto 0)))));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    rows_V_fu_302_p0 <= dst_rows_V_dout;
        rows_V_fu_302_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rows_V_fu_302_p0),32));

    select_ln340_fu_963_p3 <= 
        p_Val2_25_reg_1278 when (and_ln340_fu_947_p2(0) = '1') else 
        ap_const_lv8_FF;
    select_ln403_3_fu_763_p3 <= 
        p_Val2_24_reg_1198 when (and_ln403_3_fu_758_p2(0) = '1') else 
        select_ln403_fu_747_p3;
    select_ln403_fu_747_p3 <= 
        p_Val2_24_reg_1198 when (and_ln403_reg_1209(0) = '1') else 
        select_ln582_fu_741_p3;
    select_ln571_fu_996_p3 <= 
        ap_const_lv8_0 when (or_ln571_4_fu_991_p2(0) = '1') else 
        p_Val2_25_reg_1278;
    select_ln582_fu_741_p3 <= 
        trunc_ln583_reg_1187 when (icmp_ln582_reg_1169_pp0_iter25_reg(0) = '1') else 
        ap_const_lv8_0;
    select_ln588_fu_496_p3 <= 
        ap_const_lv8_FF when (tmp_65_fu_489_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln631_fu_816_p3 <= 
        Range2_all_ones_fu_811_p2 when (and_ln631_fu_801_p2(0) = '1') else 
        xor_ln631_fu_796_p2;
    select_ln639_3_fu_873_p3 <= 
        and_ln641_fu_843_p2 when (and_ln639_fu_824_p2(0) = '1') else 
        select_ln642_3_fu_866_p3;
    select_ln639_fu_858_p3 <= 
        Range1_all_ones_fu_828_p2 when (and_ln639_fu_824_p2(0) = '1') else 
        select_ln642_fu_853_p3;
    select_ln642_3_fu_866_p3 <= 
        Range1_all_zeros_fu_838_p2 when (and_ln642_reg_1272(0) = '1') else 
        or_ln645_fu_849_p2;
    select_ln642_fu_853_p3 <= 
        Range1_all_ones_3_reg_1238 when (and_ln642_reg_1272(0) = '1') else 
        xor_ln621_3_reg_1231;
        sext_ln581_fu_468_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(F2_6_reg_1163),32));

        sext_ln618_fu_620_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(pos1_fu_615_p2),32));

        sext_ln619_fu_629_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(pos2_fu_624_p2),32));

    shl_ln604_fu_736_p2 <= std_logic_vector(shift_left(unsigned(trunc_ln583_reg_1187),to_integer(unsigned('0' & trunc_ln581_fu_733_p1(8-1 downto 0)))));

    src1_data_stream_V_blk_n_assign_proc : process(src1_data_stream_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln355_reg_1048)
    begin
        if (((icmp_ln355_reg_1048 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            src1_data_stream_V_blk_n <= src1_data_stream_V_empty_n;
        else 
            src1_data_stream_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    src1_data_stream_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln355_reg_1048, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln355_reg_1048 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            src1_data_stream_V_read <= ap_const_logic_1;
        else 
            src1_data_stream_V_read <= ap_const_logic_0;
        end if; 
    end process;


    src2_data_stream_V_blk_n_assign_proc : process(src2_data_stream_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln355_reg_1048)
    begin
        if (((icmp_ln355_reg_1048 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            src2_data_stream_V_blk_n <= src2_data_stream_V_empty_n;
        else 
            src2_data_stream_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    src2_data_stream_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln355_reg_1048, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln355_reg_1048 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            src2_data_stream_V_read <= ap_const_logic_1;
        else 
            src2_data_stream_V_read <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln581_fu_421_p2 <= std_logic_vector(unsigned(ap_const_lv12_0) - unsigned(F2_fu_409_p2));
    tmp_1_i_fu_385_p3 <= (ap_const_lv1_1 & tmp_V_5_fu_353_p1);
    tmp_64_fu_447_p4 <= F2_6_fu_427_p3(11 downto 3);
    tmp_65_fu_489_p3 <= p_Val2_22_reg_1107(63 downto 63);
    tmp_67_fu_558_p3 <= p_Val2_24_fu_552_p2(7 downto 7);
    tmp_69_fu_639_p3 <= pos1_fu_615_p2(11 downto 11);
    tmp_V_5_fu_353_p1 <= p_Val2_22_fu_340_p1(52 - 1 downto 0);
    tmp_V_fu_343_p4 <= p_Val2_22_fu_340_p1(62 downto 52);
    trunc_ln556_fu_369_p1 <= p_Val2_22_fu_340_p1(63 - 1 downto 0);
    trunc_ln581_fu_733_p1 <= F2_6_reg_1163_pp0_iter25_reg(8 - 1 downto 0);
    trunc_ln583_fu_471_p1 <= p_Val2_s_fu_463_p3(8 - 1 downto 0);
    trunc_ln586_fu_485_p1 <= ashr_ln586_fu_479_p2(8 - 1 downto 0);
    underflow_fu_919_p3 <= 
        empty_118_fu_893_p2 when (and_ln557_fu_915_p2(0) = '1') else 
        and_ln621_5_fu_910_p2;
    xor_ln340_1_fu_952_p2 <= (or_ln658_1_reg_1290 xor ap_const_lv1_1);
    xor_ln340_fu_942_p2 <= (underflow_reg_1284 xor ap_const_lv1_1);
    xor_ln403_fu_753_p2 <= (p_Result_22_reg_1193 xor ap_const_lv1_1);
    xor_ln416_fu_566_p2 <= (tmp_67_fu_558_p3 xor ap_const_lv1_1);
    xor_ln428_fu_974_p2 <= (ap_const_lv1_1 xor and_ln428_3_fu_970_p2);
    xor_ln571_fu_1008_p2 <= (or_ln571_3_fu_1003_p2 xor ap_const_lv1_1);
    xor_ln581_fu_770_p2 <= (or_ln581_reg_1214 xor ap_const_lv1_1);
    xor_ln582_fu_572_p2 <= (icmp_ln582_reg_1169 xor ap_const_lv1_1);
    xor_ln603_fu_592_p2 <= (icmp_ln603_reg_1181 xor ap_const_lv1_1);
    xor_ln621_3_fu_647_p2 <= (tmp_69_fu_639_p3 xor ap_const_lv1_1);
    xor_ln621_fu_899_p2 <= (icmp_ln621_reg_1225 xor ap_const_lv1_1);
    xor_ln631_fu_796_p2 <= (tmp_70_reg_1245 xor ap_const_lv1_1);
    xor_ln639_3_fu_715_p2 <= (icmp_ln631_fu_687_p2 xor ap_const_lv1_1);
    zext_ln415_fu_548_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(qb_fu_533_p3),8));
    zext_ln461_fu_381_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_V_fu_343_p4),12));
    zext_ln586_fu_475_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln581_fu_468_p1),54));
    zext_ln591_fu_521_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln591_fu_516_p2),32));
    zext_ln623_fu_653_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln618_fu_620_p1),54));
    zext_ln635_fu_693_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln619_fu_629_p1),54));
end behav;
