-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ConvertScaleAbs273 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_src_data_stream_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    p_src_data_stream_V_empty_n : IN STD_LOGIC;
    p_src_data_stream_V_read : OUT STD_LOGIC;
    p_dst_data_stream_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_dst_data_stream_V_full_n : IN STD_LOGIC;
    p_dst_data_stream_V_write : OUT STD_LOGIC );
end;


architecture behav of ConvertScaleAbs273 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv10_2D0 : STD_LOGIC_VECTOR (9 downto 0) := "1011010000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv11_500 : STD_LOGIC_VECTOR (10 downto 0) := "10100000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv12_433 : STD_LOGIC_VECTOR (11 downto 0) := "010000110011";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv11_433 : STD_LOGIC_VECTOR (10 downto 0) := "10000110011";
    constant ap_const_lv12_36 : STD_LOGIC_VECTOR (11 downto 0) := "000000110110";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv52_0 : STD_LOGIC_VECTOR (51 downto 0) := "0000000000000000000000000000000000000000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv12_8 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_const_lv12_9 : STD_LOGIC_VECTOR (11 downto 0) := "000000001001";
    constant ap_const_lv54_0 : STD_LOGIC_VECTOR (53 downto 0) := "000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv54_3FFFFFFFFFFFFF : STD_LOGIC_VECTOR (53 downto 0) := "111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_src_data_stream_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln2527_reg_788 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_dst_data_stream_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal icmp_ln2527_reg_788_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal j_0_reg_164 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln2526_fu_178_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal i_fu_184_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal i_reg_783 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln2527_fu_190_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln2527_reg_788_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln2527_reg_788_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln2527_reg_788_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln2527_reg_788_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln2527_reg_788_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln2527_reg_788_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln2527_reg_788_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln2527_reg_788_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln2527_reg_788_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal j_fu_196_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal tmp_reg_797 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_175_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_assign_reg_807 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_V_3_fu_223_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal tmp_V_3_reg_812 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln833_fu_227_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln833_reg_818 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln833_reg_818_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln833_reg_818_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln571_fu_237_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln571_reg_824 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln571_reg_824_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln571_reg_824_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal F2_fu_243_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal F2_reg_830 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln581_fu_249_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln581_reg_838 : STD_LOGIC_VECTOR (0 downto 0);
    signal F2_2_fu_261_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal F2_2_reg_844 : STD_LOGIC_VECTOR (11 downto 0);
    signal F2_2_reg_844_pp0_iter9_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln582_fu_269_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln582_reg_850 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln582_reg_850_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln583_fu_275_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln583_reg_857 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln583_reg_857_pp0_iter9_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln585_fu_279_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln585_reg_863 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln603_fu_295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln603_reg_868 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln603_reg_868_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln837_fu_301_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln837_reg_874 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln837_reg_874_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_7_fu_371_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_7_reg_880 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_15_fu_383_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_15_reg_885 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln581_fu_408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln581_reg_891 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln403_fu_413_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln403_reg_896 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln581_fu_419_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln581_reg_901 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln603_2_fu_440_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln603_2_reg_906 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln603_2_reg_906_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln621_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln621_reg_911 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln621_reg_911_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln621_1_fu_478_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln621_1_reg_916 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_1_fu_504_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_1_reg_923 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_54_reg_930 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln631_fu_518_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln631_reg_935 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln635_fu_524_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal zext_ln635_reg_941 : STD_LOGIC_VECTOR (53 downto 0);
    signal Range2_V_1_fu_528_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal Range2_V_1_reg_946 : STD_LOGIC_VECTOR (53 downto 0);
    signal Range1_all_zeros_1_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_1_reg_952 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln642_fu_558_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln642_reg_957 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_16_fu_611_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_16_reg_963 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln639_fu_681_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln639_reg_969 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln639_1_fu_696_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln639_1_reg_974 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state3 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal i_0_reg_153 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal grp_fu_175_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_s_fu_206_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_V_fu_213_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln368_fu_209_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln461_fu_233_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln581_fu_255_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_50_fu_285_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_1_i_fu_306_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal sext_ln581_fu_317_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_6_fu_313_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal zext_ln586_fu_320_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal ashr_ln586_fu_324_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal trunc_ln586_fu_330_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln591_fu_346_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln591_fu_351_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln591_fu_341_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_355_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_14_fu_334_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal qb_fu_363_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_fu_379_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_52_fu_389_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln582_fu_403_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln603_fu_423_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln603_fu_428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln416_fu_397_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln603_1_fu_434_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pos1_fu_446_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal pos2_fu_455_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_53_fu_470_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln618_fu_451_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln623_fu_484_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal ashr_ln623_fu_488_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal lD_fu_494_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln621_fu_498_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln619_fu_460_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln639_1_fu_546_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln642_fu_534_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln639_fu_552_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln581_fu_564_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln582_fu_572_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln403_fu_584_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln403_1_fu_589_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln403_fu_578_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln581_fu_601_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln603_fu_606_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln604_fu_567_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln403_1_fu_594_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln631_fu_619_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_fu_629_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal and_ln631_fu_624_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_fu_634_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln631_fu_639_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln641_fu_656_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_fu_661_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln639_fu_647_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_fu_651_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln642_fu_676_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln645_fu_672_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln641_fu_666_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln642_1_fu_689_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln621_fu_713_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_fu_708_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln658_fu_718_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln428_1_fu_731_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln428_fu_735_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln571_fu_741_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln428_fu_704_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln571_fu_746_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln571_1_fu_759_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln571_fu_764_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_fu_724_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln571_fu_752_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_175_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;

    component sobel_accel_sitodtde IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    sobel_accel_sitodtde_U81 : component sobel_accel_sitodtde
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_175_p0,
        ce => grp_fu_175_ce,
        dout => grp_fu_175_p1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln2526_fu_178_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((icmp_ln2526_fu_178_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state3);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                elsif (((icmp_ln2526_fu_178_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    i_0_reg_153_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                i_0_reg_153 <= i_reg_783;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_0_reg_153 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;

    j_0_reg_164_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln2527_fu_190_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                j_0_reg_164 <= j_fu_196_p2;
            elsif (((icmp_ln2526_fu_178_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j_0_reg_164 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln2527_reg_788_pp0_iter7_reg = ap_const_lv1_0))) then
                F2_2_reg_844 <= F2_2_fu_261_p3;
                F2_reg_830 <= F2_fu_243_p2;
                icmp_ln571_reg_824 <= icmp_ln571_fu_237_p2;
                icmp_ln581_reg_838 <= icmp_ln581_fu_249_p2;
                icmp_ln582_reg_850 <= icmp_ln582_fu_269_p2;
                icmp_ln585_reg_863 <= icmp_ln585_fu_279_p2;
                icmp_ln603_reg_868 <= icmp_ln603_fu_295_p2;
                icmp_ln833_reg_818 <= icmp_ln833_fu_227_p2;
                tmp_V_3_reg_812 <= tmp_V_3_fu_223_p1;
                trunc_ln583_reg_857 <= trunc_ln583_fu_275_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                F2_2_reg_844_pp0_iter9_reg <= F2_2_reg_844;
                and_ln603_2_reg_906_pp0_iter10_reg <= and_ln603_2_reg_906;
                icmp_ln2527_reg_788_pp0_iter10_reg <= icmp_ln2527_reg_788_pp0_iter9_reg;
                icmp_ln2527_reg_788_pp0_iter2_reg <= icmp_ln2527_reg_788_pp0_iter1_reg;
                icmp_ln2527_reg_788_pp0_iter3_reg <= icmp_ln2527_reg_788_pp0_iter2_reg;
                icmp_ln2527_reg_788_pp0_iter4_reg <= icmp_ln2527_reg_788_pp0_iter3_reg;
                icmp_ln2527_reg_788_pp0_iter5_reg <= icmp_ln2527_reg_788_pp0_iter4_reg;
                icmp_ln2527_reg_788_pp0_iter6_reg <= icmp_ln2527_reg_788_pp0_iter5_reg;
                icmp_ln2527_reg_788_pp0_iter7_reg <= icmp_ln2527_reg_788_pp0_iter6_reg;
                icmp_ln2527_reg_788_pp0_iter8_reg <= icmp_ln2527_reg_788_pp0_iter7_reg;
                icmp_ln2527_reg_788_pp0_iter9_reg <= icmp_ln2527_reg_788_pp0_iter8_reg;
                icmp_ln571_reg_824_pp0_iter10_reg <= icmp_ln571_reg_824_pp0_iter9_reg;
                icmp_ln571_reg_824_pp0_iter9_reg <= icmp_ln571_reg_824;
                icmp_ln582_reg_850_pp0_iter9_reg <= icmp_ln582_reg_850;
                icmp_ln603_reg_868_pp0_iter9_reg <= icmp_ln603_reg_868;
                icmp_ln621_reg_911_pp0_iter10_reg <= icmp_ln621_reg_911;
                icmp_ln833_reg_818_pp0_iter10_reg <= icmp_ln833_reg_818_pp0_iter9_reg;
                icmp_ln833_reg_818_pp0_iter9_reg <= icmp_ln833_reg_818;
                icmp_ln837_reg_874_pp0_iter10_reg <= icmp_ln837_reg_874;
                trunc_ln583_reg_857_pp0_iter9_reg <= trunc_ln583_reg_857;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln2527_reg_788_pp0_iter8_reg = ap_const_lv1_0))) then
                Range1_all_ones_1_reg_923 <= Range1_all_ones_1_fu_504_p2;
                Range1_all_zeros_1_reg_952 <= Range1_all_zeros_1_fu_540_p2;
                Range2_V_1_reg_946 <= Range2_V_1_fu_528_p2;
                and_ln403_reg_896 <= and_ln403_fu_413_p2;
                and_ln581_reg_891 <= and_ln581_fu_408_p2;
                and_ln603_2_reg_906 <= and_ln603_2_fu_440_p2;
                and_ln642_reg_957 <= and_ln642_fu_558_p2;
                icmp_ln621_reg_911 <= icmp_ln621_fu_464_p2;
                icmp_ln631_reg_935 <= icmp_ln631_fu_518_p2;
                icmp_ln837_reg_874 <= icmp_ln837_fu_301_p2;
                or_ln581_reg_901 <= or_ln581_fu_419_p2;
                p_Result_7_reg_880 <= p_Val2_14_fu_334_p3(7 downto 7);
                p_Val2_15_reg_885 <= p_Val2_15_fu_383_p2;
                tmp_54_reg_930 <= pos2_fu_455_p2(11 downto 11);
                xor_ln621_1_reg_916 <= xor_ln621_1_fu_478_p2;
                    zext_ln635_reg_941(31 downto 0) <= zext_ln635_fu_524_p1(31 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_reg_783 <= i_fu_184_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln2527_reg_788 <= icmp_ln2527_fu_190_p2;
                icmp_ln2527_reg_788_pp0_iter1_reg <= icmp_ln2527_reg_788;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln2527_reg_788_pp0_iter9_reg = ap_const_lv1_0))) then
                p_Val2_16_reg_963 <= p_Val2_16_fu_611_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_0 = and_ln603_2_reg_906) and (icmp_ln2527_reg_788_pp0_iter9_reg = ap_const_lv1_0))) then
                select_ln639_1_reg_974 <= select_ln639_1_fu_696_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln2527_reg_788_pp0_iter9_reg = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln603_2_reg_906))) then
                select_ln639_reg_969 <= select_ln639_fu_681_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln2527_reg_788 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_reg_797 <= p_src_data_stream_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln2527_reg_788_pp0_iter6_reg = ap_const_lv1_0))) then
                x_assign_reg_807 <= grp_fu_175_p1;
            end if;
        end if;
    end process;
    zext_ln635_reg_941(53 downto 32) <= "0000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter11, icmp_ln2526_fu_178_p2, ap_CS_fsm_state2, icmp_ln2527_fu_190_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter10)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln2526_fu_178_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((icmp_ln2527_fu_190_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) and not(((ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1)) or ((icmp_ln2527_fu_190_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state15;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    F2_2_fu_261_p3 <= 
        F2_fu_243_p2 when (icmp_ln581_fu_249_p2(0) = '1') else 
        sub_ln581_fu_255_p2;
    F2_fu_243_p2 <= std_logic_vector(unsigned(ap_const_lv12_433) - unsigned(zext_ln461_fu_233_p1));
    Range1_all_ones_1_fu_504_p2 <= (icmp_ln621_fu_464_p2 and and_ln621_fu_498_p2);
    Range1_all_ones_fu_651_p2 <= (select_ln631_fu_639_p3 and Range1_all_ones_1_reg_923);
    Range1_all_zeros_1_fu_540_p2 <= "1" when (p_Result_6_fu_313_p1 = ap_const_lv54_0) else "0";
    Range1_all_zeros_fu_661_p2 <= (ap_const_lv1_1 xor Range1_all_ones_1_reg_923);
    Range2_V_1_fu_528_p2 <= std_logic_vector(shift_right(unsigned(p_Result_6_fu_313_p1),to_integer(unsigned('0' & zext_ln635_fu_524_p1(31-1 downto 0)))));
    Range2_all_ones_fu_634_p2 <= "1" when (Range2_V_1_reg_946 = r_V_fu_629_p2) else "0";
    add_ln591_fu_346_p2 <= std_logic_vector(signed(ap_const_lv12_FFF) + signed(F2_reg_830));
    and_ln403_1_fu_589_p2 <= (xor_ln403_fu_584_p2 and and_ln581_reg_891);
    and_ln403_fu_413_p2 <= (p_Result_7_fu_371_p3 and and_ln581_fu_408_p2);
    and_ln428_1_fu_731_p2 <= (icmp_ln837_reg_874_pp0_iter10_reg and icmp_ln833_reg_818_pp0_iter10_reg);
    and_ln428_fu_704_p2 <= (icmp_ln837_reg_874_pp0_iter10_reg and icmp_ln833_reg_818_pp0_iter10_reg);
    and_ln571_fu_741_p2 <= (xor_ln428_fu_735_p2 and icmp_ln571_reg_824_pp0_iter10_reg);
    and_ln581_fu_408_p2 <= (xor_ln582_fu_403_p2 and icmp_ln581_reg_838);
    and_ln603_1_fu_434_p2 <= (xor_ln416_fu_397_p2 and or_ln603_fu_428_p2);
    and_ln603_2_fu_440_p2 <= (and_ln603_1_fu_434_p2 and and_ln403_fu_413_p2);
    and_ln603_fu_606_p2 <= (xor_ln581_fu_601_p2 and icmp_ln603_reg_868_pp0_iter9_reg);
    and_ln621_fu_498_p2 <= (xor_ln621_1_fu_478_p2 and lD_fu_494_p1);
    and_ln631_fu_624_p2 <= (xor_ln631_fu_619_p2 and icmp_ln631_reg_935);
    and_ln639_fu_647_p2 <= (xor_ln621_1_reg_916 and icmp_ln631_reg_935);
    and_ln641_fu_666_p2 <= (icmp_ln641_fu_656_p2 and Range1_all_zeros_fu_661_p2);
    and_ln642_fu_558_p2 <= (or_ln639_fu_552_p2 and icmp_ln642_fu_534_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state15 <= ap_CS_fsm(3);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(p_src_data_stream_V_empty_n, p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter1, icmp_ln2527_reg_788, ap_enable_reg_pp0_iter11, icmp_ln2527_reg_788_pp0_iter10_reg)
    begin
                ap_block_pp0_stage0_01001 <= (((icmp_ln2527_reg_788_pp0_iter10_reg = ap_const_lv1_0) and (p_dst_data_stream_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1)) or ((icmp_ln2527_reg_788 = ap_const_lv1_0) and (p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(p_src_data_stream_V_empty_n, p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter1, icmp_ln2527_reg_788, ap_enable_reg_pp0_iter11, icmp_ln2527_reg_788_pp0_iter10_reg)
    begin
                ap_block_pp0_stage0_11001 <= (((icmp_ln2527_reg_788_pp0_iter10_reg = ap_const_lv1_0) and (p_dst_data_stream_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1)) or ((icmp_ln2527_reg_788 = ap_const_lv1_0) and (p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(p_src_data_stream_V_empty_n, p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter1, icmp_ln2527_reg_788, ap_enable_reg_pp0_iter11, icmp_ln2527_reg_788_pp0_iter10_reg)
    begin
                ap_block_pp0_stage0_subdone <= (((icmp_ln2527_reg_788_pp0_iter10_reg = ap_const_lv1_0) and (p_dst_data_stream_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1)) or ((icmp_ln2527_reg_788 = ap_const_lv1_0) and (p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state10_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state14_pp0_stage0_iter11_assign_proc : process(p_dst_data_stream_V_full_n, icmp_ln2527_reg_788_pp0_iter10_reg)
    begin
                ap_block_state14_pp0_stage0_iter11 <= ((icmp_ln2527_reg_788_pp0_iter10_reg = ap_const_lv1_0) and (p_dst_data_stream_V_full_n = ap_const_logic_0));
    end process;

        ap_block_state3_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_pp0_stage0_iter1_assign_proc : process(p_src_data_stream_V_empty_n, icmp_ln2527_reg_788)
    begin
                ap_block_state4_pp0_stage0_iter1 <= ((icmp_ln2527_reg_788 = ap_const_lv1_0) and (p_src_data_stream_V_empty_n = ap_const_logic_0));
    end process;

        ap_block_state5_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state3_assign_proc : process(icmp_ln2527_fu_190_p2)
    begin
        if ((icmp_ln2527_fu_190_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, icmp_ln2526_fu_178_p2, ap_CS_fsm_state2)
    begin
        if (((icmp_ln2526_fu_178_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(icmp_ln2526_fu_178_p2, ap_CS_fsm_state2)
    begin
        if (((icmp_ln2526_fu_178_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ashr_ln586_fu_324_p2 <= std_logic_vector(shift_right(signed(p_Result_6_fu_313_p1),to_integer(unsigned('0' & zext_ln586_fu_320_p1(31-1 downto 0)))));
    ashr_ln623_fu_488_p2 <= std_logic_vector(shift_right(signed(p_Result_6_fu_313_p1),to_integer(unsigned('0' & zext_ln623_fu_484_p1(31-1 downto 0)))));
    deleted_zeros_fu_708_p3 <= 
        select_ln639_reg_969 when (and_ln603_2_reg_906_pp0_iter10_reg(0) = '1') else 
        select_ln639_1_reg_974;

    grp_fu_175_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_175_ce <= ap_const_logic_1;
        else 
            grp_fu_175_ce <= ap_const_logic_0;
        end if; 
    end process;

        grp_fu_175_p0 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_reg_797),32));

    i_fu_184_p2 <= std_logic_vector(unsigned(i_0_reg_153) + unsigned(ap_const_lv10_1));
    icmp_ln2526_fu_178_p2 <= "1" when (i_0_reg_153 = ap_const_lv10_2D0) else "0";
    icmp_ln2527_fu_190_p2 <= "1" when (j_0_reg_164 = ap_const_lv11_500) else "0";
    icmp_ln571_fu_237_p2 <= "1" when (trunc_ln368_fu_209_p1 = ap_const_lv63_0) else "0";
    icmp_ln581_fu_249_p2 <= "1" when (signed(F2_fu_243_p2) > signed(ap_const_lv12_0)) else "0";
    icmp_ln582_fu_269_p2 <= "1" when (tmp_V_fu_213_p4 = ap_const_lv11_433) else "0";
    icmp_ln585_fu_279_p2 <= "1" when (unsigned(F2_2_fu_261_p3) < unsigned(ap_const_lv12_36)) else "0";
    icmp_ln591_fu_341_p2 <= "1" when (signed(F2_reg_830) > signed(ap_const_lv12_36)) else "0";
    icmp_ln603_fu_295_p2 <= "1" when (tmp_50_fu_285_p4 = ap_const_lv9_0) else "0";
    icmp_ln621_fu_464_p2 <= "1" when (signed(pos1_fu_446_p2) < signed(ap_const_lv12_36)) else "0";
    icmp_ln631_fu_518_p2 <= "1" when (signed(pos2_fu_455_p2) < signed(ap_const_lv12_36)) else "0";
    icmp_ln641_fu_656_p2 <= "1" when (Range2_V_1_reg_946 = ap_const_lv54_0) else "0";
    icmp_ln642_fu_534_p2 <= "1" when (pos2_fu_455_p2 = ap_const_lv12_36) else "0";
    icmp_ln833_fu_227_p2 <= "1" when (tmp_V_fu_213_p4 = ap_const_lv11_7FF) else "0";
    icmp_ln837_fu_301_p2 <= "0" when (tmp_V_3_reg_812 = ap_const_lv52_0) else "1";
    j_fu_196_p2 <= std_logic_vector(unsigned(j_0_reg_164) + unsigned(ap_const_lv11_1));
    lD_fu_494_p1 <= ashr_ln623_fu_488_p2(1 - 1 downto 0);
    or_ln571_1_fu_759_p2 <= (icmp_ln571_reg_824_pp0_iter10_reg or and_ln428_fu_704_p2);
    or_ln571_fu_746_p2 <= (and_ln571_fu_741_p2 or and_ln428_fu_704_p2);
    or_ln581_fu_419_p2 <= (icmp_ln582_reg_850 or icmp_ln581_reg_838);
    or_ln603_fu_428_p2 <= (xor_ln603_fu_423_p2 or or_ln581_fu_419_p2);
    or_ln639_fu_552_p2 <= (xor_ln639_1_fu_546_p2 or tmp_53_fu_470_p3);
    or_ln645_fu_672_p2 <= (xor_ln621_1_reg_916 or Range1_all_zeros_1_reg_952);
    or_ln658_fu_718_p2 <= (xor_ln621_fu_713_p2 or deleted_zeros_fu_708_p3);
    p_Result_6_fu_313_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_i_fu_306_p3),54));
    p_Result_7_fu_371_p3 <= p_Val2_14_fu_334_p3(7 downto 7);
    p_Result_s_fu_355_p3 <= p_Result_6_fu_313_p1(to_integer(unsigned(zext_ln591_fu_351_p1)) downto to_integer(unsigned(zext_ln591_fu_351_p1))) when (to_integer(unsigned(zext_ln591_fu_351_p1))>= 0 and to_integer(unsigned(zext_ln591_fu_351_p1))<=53) else "-";
    p_Val2_14_fu_334_p3 <= 
        trunc_ln586_fu_330_p1 when (icmp_ln585_reg_863(0) = '1') else 
        ap_const_lv8_0;
    p_Val2_15_fu_383_p2 <= std_logic_vector(unsigned(p_Val2_14_fu_334_p3) + unsigned(zext_ln415_fu_379_p1));
    p_Val2_16_fu_611_p3 <= 
        shl_ln604_fu_567_p2 when (and_ln603_fu_606_p2(0) = '1') else 
        select_ln403_1_fu_594_p3;
    p_Val2_s_fu_206_p1 <= x_assign_reg_807;

    p_dst_data_stream_V_blk_n_assign_proc : process(p_dst_data_stream_V_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter11, icmp_ln2527_reg_788_pp0_iter10_reg)
    begin
        if (((icmp_ln2527_reg_788_pp0_iter10_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            p_dst_data_stream_V_blk_n <= p_dst_data_stream_V_full_n;
        else 
            p_dst_data_stream_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    p_dst_data_stream_V_din <= 
        select_ln340_fu_724_p3 when (xor_ln571_fu_764_p2(0) = '1') else 
        select_ln571_fu_752_p3;

    p_dst_data_stream_V_write_assign_proc : process(ap_enable_reg_pp0_iter11, icmp_ln2527_reg_788_pp0_iter10_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln2527_reg_788_pp0_iter10_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            p_dst_data_stream_V_write <= ap_const_logic_1;
        else 
            p_dst_data_stream_V_write <= ap_const_logic_0;
        end if; 
    end process;


    p_src_data_stream_V_blk_n_assign_proc : process(p_src_data_stream_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln2527_reg_788)
    begin
        if (((icmp_ln2527_reg_788 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_src_data_stream_V_blk_n <= p_src_data_stream_V_empty_n;
        else 
            p_src_data_stream_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_src_data_stream_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln2527_reg_788, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln2527_reg_788 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_src_data_stream_V_read <= ap_const_logic_1;
        else 
            p_src_data_stream_V_read <= ap_const_logic_0;
        end if; 
    end process;

    pos1_fu_446_p2 <= std_logic_vector(unsigned(ap_const_lv12_8) + unsigned(F2_reg_830));
    pos2_fu_455_p2 <= std_logic_vector(unsigned(ap_const_lv12_9) + unsigned(F2_reg_830));
    qb_fu_363_p3 <= 
        ap_const_lv1_0 when (icmp_ln591_fu_341_p2(0) = '1') else 
        p_Result_s_fu_355_p3;
    r_V_fu_629_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv54_3FFFFFFFFFFFFF),to_integer(unsigned('0' & zext_ln635_reg_941(31-1 downto 0)))));
    select_ln340_fu_724_p3 <= 
        p_Val2_16_reg_963 when (or_ln658_fu_718_p2(0) = '1') else 
        ap_const_lv8_FF;
    select_ln403_1_fu_594_p3 <= 
        p_Val2_15_reg_885 when (and_ln403_1_fu_589_p2(0) = '1') else 
        select_ln403_fu_578_p3;
    select_ln403_fu_578_p3 <= 
        p_Val2_15_reg_885 when (and_ln403_reg_896(0) = '1') else 
        select_ln582_fu_572_p3;
    select_ln571_fu_752_p3 <= 
        ap_const_lv8_0 when (or_ln571_fu_746_p2(0) = '1') else 
        p_Val2_16_reg_963;
    select_ln582_fu_572_p3 <= 
        trunc_ln583_reg_857_pp0_iter9_reg when (icmp_ln582_reg_850_pp0_iter9_reg(0) = '1') else 
        ap_const_lv8_0;
    select_ln631_fu_639_p3 <= 
        Range2_all_ones_fu_634_p2 when (and_ln631_fu_624_p2(0) = '1') else 
        xor_ln631_fu_619_p2;
    select_ln639_1_fu_696_p3 <= 
        and_ln641_fu_666_p2 when (and_ln639_fu_647_p2(0) = '1') else 
        select_ln642_1_fu_689_p3;
    select_ln639_fu_681_p3 <= 
        Range1_all_ones_fu_651_p2 when (and_ln639_fu_647_p2(0) = '1') else 
        select_ln642_fu_676_p3;
    select_ln642_1_fu_689_p3 <= 
        Range1_all_zeros_fu_661_p2 when (and_ln642_reg_957(0) = '1') else 
        or_ln645_fu_672_p2;
    select_ln642_fu_676_p3 <= 
        Range1_all_ones_1_reg_923 when (and_ln642_reg_957(0) = '1') else 
        xor_ln621_1_reg_916;
        sext_ln581_fu_317_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(F2_2_reg_844),32));

        sext_ln618_fu_451_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(pos1_fu_446_p2),32));

        sext_ln619_fu_460_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(pos2_fu_455_p2),32));

    shl_ln604_fu_567_p2 <= std_logic_vector(shift_left(unsigned(trunc_ln583_reg_857_pp0_iter9_reg),to_integer(unsigned('0' & trunc_ln581_fu_564_p1(8-1 downto 0)))));
    sub_ln581_fu_255_p2 <= std_logic_vector(unsigned(ap_const_lv12_0) - unsigned(F2_fu_243_p2));
    tmp_1_i_fu_306_p3 <= (ap_const_lv1_1 & tmp_V_3_reg_812);
    tmp_50_fu_285_p4 <= F2_2_fu_261_p3(11 downto 3);
    tmp_52_fu_389_p3 <= p_Val2_15_fu_383_p2(7 downto 7);
    tmp_53_fu_470_p3 <= pos1_fu_446_p2(11 downto 11);
    tmp_V_3_fu_223_p1 <= p_Val2_s_fu_206_p1(52 - 1 downto 0);
    tmp_V_fu_213_p4 <= p_Val2_s_fu_206_p1(62 downto 52);
    trunc_ln368_fu_209_p1 <= p_Val2_s_fu_206_p1(63 - 1 downto 0);
    trunc_ln581_fu_564_p1 <= F2_2_reg_844_pp0_iter9_reg(8 - 1 downto 0);
    trunc_ln583_fu_275_p1 <= p_Val2_s_fu_206_p1(8 - 1 downto 0);
    trunc_ln586_fu_330_p1 <= ashr_ln586_fu_324_p2(8 - 1 downto 0);
    xor_ln403_fu_584_p2 <= (p_Result_7_reg_880 xor ap_const_lv1_1);
    xor_ln416_fu_397_p2 <= (tmp_52_fu_389_p3 xor ap_const_lv1_1);
    xor_ln428_fu_735_p2 <= (ap_const_lv1_1 xor and_ln428_1_fu_731_p2);
    xor_ln571_fu_764_p2 <= (or_ln571_1_fu_759_p2 xor ap_const_lv1_1);
    xor_ln581_fu_601_p2 <= (or_ln581_reg_901 xor ap_const_lv1_1);
    xor_ln582_fu_403_p2 <= (icmp_ln582_reg_850 xor ap_const_lv1_1);
    xor_ln603_fu_423_p2 <= (icmp_ln603_reg_868 xor ap_const_lv1_1);
    xor_ln621_1_fu_478_p2 <= (tmp_53_fu_470_p3 xor ap_const_lv1_1);
    xor_ln621_fu_713_p2 <= (icmp_ln621_reg_911_pp0_iter10_reg xor ap_const_lv1_1);
    xor_ln631_fu_619_p2 <= (tmp_54_reg_930 xor ap_const_lv1_1);
    xor_ln639_1_fu_546_p2 <= (icmp_ln631_fu_518_p2 xor ap_const_lv1_1);
    zext_ln415_fu_379_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(qb_fu_363_p3),8));
    zext_ln461_fu_233_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_V_fu_213_p4),12));
    zext_ln586_fu_320_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln581_fu_317_p1),54));
    zext_ln591_fu_351_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln591_fu_346_p2),32));
    zext_ln623_fu_484_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln618_fu_451_p1),54));
    zext_ln635_fu_524_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln619_fu_460_p1),54));
end behav;
