# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/base/base.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base || ORIG_REF_NAME==base} -quiet] -quiet

# IP: bd/base/ip/base_axi_vdma_0_0/base_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_vdma_0_0 || ORIG_REF_NAME==base_axi_vdma_0_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_vdma_1_0/base_axi_vdma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_vdma_1_0 || ORIG_REF_NAME==base_axi_vdma_1_0} -quiet] -quiet

# IP: bd/base/ip/base_xlconcat_0_2/base_xlconcat_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xlconcat_0_2 || ORIG_REF_NAME==base_xlconcat_0_2} -quiet] -quiet

# IP: bd/base/ip/base_axi_intc_0_0/base_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_intc_0_0 || ORIG_REF_NAME==base_axi_intc_0_0} -quiet] -quiet

# IP: bd/base/ip/base_xbar_11/base_xbar_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xbar_11 || ORIG_REF_NAME==base_xbar_11} -quiet] -quiet

# IP: bd/base/ip/base_axi_interconnect_0_2/base_axi_interconnect_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_interconnect_0_2 || ORIG_REF_NAME==base_axi_interconnect_0_2} -quiet] -quiet

# IP: bd/base/ip/base_sobel_accel_1_0/base_sobel_accel_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sobel_accel_1_0 || ORIG_REF_NAME==base_sobel_accel_1_0} -quiet] -quiet

# IP: bd/base/ip/base_smartconnect_1_1/base_smartconnect_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_smartconnect_1_1 || ORIG_REF_NAME==base_smartconnect_1_1} -quiet] -quiet

# IP: bd/base/ip/base_proc_sys_reset_1_1/base_proc_sys_reset_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_1_1 || ORIG_REF_NAME==base_proc_sys_reset_1_1} -quiet] -quiet

# IP: bd/base/ip/base_processing_system7_1_1/base_processing_system7_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_processing_system7_1_1 || ORIG_REF_NAME==base_processing_system7_1_1} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_0/base_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_0 || ORIG_REF_NAME==base_auto_pc_0} -quiet] -quiet

# XDC: bd/base/base_ooc.xdc
