// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "ConvertScaleAbs.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic ConvertScaleAbs::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic ConvertScaleAbs::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> ConvertScaleAbs::ap_ST_fsm_state1 = "1";
const sc_lv<4> ConvertScaleAbs::ap_ST_fsm_state2 = "10";
const sc_lv<4> ConvertScaleAbs::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<4> ConvertScaleAbs::ap_ST_fsm_state15 = "1000";
const sc_lv<32> ConvertScaleAbs::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool ConvertScaleAbs::ap_const_boolean_1 = true;
const sc_lv<32> ConvertScaleAbs::ap_const_lv32_2 = "10";
const bool ConvertScaleAbs::ap_const_boolean_0 = false;
const sc_lv<1> ConvertScaleAbs::ap_const_lv1_0 = "0";
const sc_lv<32> ConvertScaleAbs::ap_const_lv32_1 = "1";
const sc_lv<1> ConvertScaleAbs::ap_const_lv1_1 = "1";
const sc_lv<10> ConvertScaleAbs::ap_const_lv10_0 = "0000000000";
const sc_lv<32> ConvertScaleAbs::ap_const_lv32_3 = "11";
const sc_lv<11> ConvertScaleAbs::ap_const_lv11_0 = "00000000000";
const sc_lv<10> ConvertScaleAbs::ap_const_lv10_2D0 = "1011010000";
const sc_lv<10> ConvertScaleAbs::ap_const_lv10_1 = "1";
const sc_lv<11> ConvertScaleAbs::ap_const_lv11_500 = "10100000000";
const sc_lv<11> ConvertScaleAbs::ap_const_lv11_1 = "1";
const sc_lv<32> ConvertScaleAbs::ap_const_lv32_34 = "110100";
const sc_lv<32> ConvertScaleAbs::ap_const_lv32_3E = "111110";
const sc_lv<11> ConvertScaleAbs::ap_const_lv11_7FF = "11111111111";
const sc_lv<63> ConvertScaleAbs::ap_const_lv63_0 = "000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<12> ConvertScaleAbs::ap_const_lv12_433 = "10000110011";
const sc_lv<12> ConvertScaleAbs::ap_const_lv12_0 = "000000000000";
const sc_lv<11> ConvertScaleAbs::ap_const_lv11_433 = "10000110011";
const sc_lv<12> ConvertScaleAbs::ap_const_lv12_36 = "110110";
const sc_lv<32> ConvertScaleAbs::ap_const_lv32_B = "1011";
const sc_lv<9> ConvertScaleAbs::ap_const_lv9_0 = "000000000";
const sc_lv<52> ConvertScaleAbs::ap_const_lv52_0 = "0000000000000000000000000000000000000000000000000000";
const sc_lv<8> ConvertScaleAbs::ap_const_lv8_0 = "00000000";
const sc_lv<12> ConvertScaleAbs::ap_const_lv12_FFF = "111111111111";
const sc_lv<32> ConvertScaleAbs::ap_const_lv32_7 = "111";
const sc_lv<12> ConvertScaleAbs::ap_const_lv12_8 = "1000";
const sc_lv<12> ConvertScaleAbs::ap_const_lv12_9 = "1001";
const sc_lv<54> ConvertScaleAbs::ap_const_lv54_0 = "000000000000000000000000000000000000000000000000000000";
const sc_lv<54> ConvertScaleAbs::ap_const_lv54_3FFFFFFFFFFFFF = "111111111111111111111111111111111111111111111111111111";
const sc_lv<8> ConvertScaleAbs::ap_const_lv8_FF = "11111111";

ConvertScaleAbs::ConvertScaleAbs(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sobel_accel_sitodtde_U85 = new sobel_accel_sitodtde<1,6,32,64>("sobel_accel_sitodtde_U85");
    sobel_accel_sitodtde_U85->clk(ap_clk);
    sobel_accel_sitodtde_U85->reset(ap_rst);
    sobel_accel_sitodtde_U85->din0(grp_fu_175_p0);
    sobel_accel_sitodtde_U85->ce(grp_fu_175_ce);
    sobel_accel_sitodtde_U85->dout(grp_fu_175_p1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_F2_4_fu_261_p3);
    sensitive << ( F2_fu_243_p2 );
    sensitive << ( icmp_ln581_fu_249_p2 );
    sensitive << ( sub_ln581_fu_255_p2 );

    SC_METHOD(thread_F2_fu_243_p2);
    sensitive << ( zext_ln461_fu_233_p1 );

    SC_METHOD(thread_Range1_all_ones_2_fu_504_p2);
    sensitive << ( icmp_ln621_fu_464_p2 );
    sensitive << ( and_ln621_fu_498_p2 );

    SC_METHOD(thread_Range1_all_ones_fu_651_p2);
    sensitive << ( Range1_all_ones_2_reg_923 );
    sensitive << ( select_ln631_fu_639_p3 );

    SC_METHOD(thread_Range1_all_zeros_2_fu_540_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_788_pp0_iter8_reg );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( p_Result_12_fu_313_p1 );

    SC_METHOD(thread_Range1_all_zeros_fu_661_p2);
    sensitive << ( Range1_all_ones_2_reg_923 );

    SC_METHOD(thread_Range2_V_2_fu_528_p2);
    sensitive << ( zext_ln635_fu_524_p1 );
    sensitive << ( p_Result_12_fu_313_p1 );

    SC_METHOD(thread_Range2_all_ones_fu_634_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_788_pp0_iter9_reg );
    sensitive << ( and_ln603_4_reg_906 );
    sensitive << ( Range2_V_2_reg_946 );
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( r_V_fu_629_p2 );

    SC_METHOD(thread_add_ln591_fu_346_p2);
    sensitive << ( F2_reg_830 );

    SC_METHOD(thread_and_ln403_2_fu_589_p2);
    sensitive << ( and_ln581_reg_891 );
    sensitive << ( xor_ln403_fu_584_p2 );

    SC_METHOD(thread_and_ln403_fu_413_p2);
    sensitive << ( p_Result_13_fu_371_p3 );
    sensitive << ( and_ln581_fu_408_p2 );

    SC_METHOD(thread_and_ln428_2_fu_731_p2);
    sensitive << ( icmp_ln833_reg_818_pp0_iter10_reg );
    sensitive << ( icmp_ln837_reg_874_pp0_iter10_reg );

    SC_METHOD(thread_and_ln428_fu_704_p2);
    sensitive << ( icmp_ln833_reg_818_pp0_iter10_reg );
    sensitive << ( icmp_ln837_reg_874_pp0_iter10_reg );

    SC_METHOD(thread_and_ln571_fu_741_p2);
    sensitive << ( icmp_ln571_reg_824_pp0_iter10_reg );
    sensitive << ( xor_ln428_fu_735_p2 );

    SC_METHOD(thread_and_ln581_fu_408_p2);
    sensitive << ( icmp_ln581_reg_838 );
    sensitive << ( xor_ln582_fu_403_p2 );

    SC_METHOD(thread_and_ln603_3_fu_434_p2);
    sensitive << ( or_ln603_fu_428_p2 );
    sensitive << ( xor_ln416_fu_397_p2 );

    SC_METHOD(thread_and_ln603_4_fu_440_p2);
    sensitive << ( and_ln403_fu_413_p2 );
    sensitive << ( and_ln603_3_fu_434_p2 );

    SC_METHOD(thread_and_ln603_fu_606_p2);
    sensitive << ( icmp_ln603_reg_868_pp0_iter9_reg );
    sensitive << ( xor_ln581_fu_601_p2 );

    SC_METHOD(thread_and_ln621_fu_498_p2);
    sensitive << ( xor_ln621_2_fu_478_p2 );
    sensitive << ( lD_fu_494_p1 );

    SC_METHOD(thread_and_ln631_fu_624_p2);
    sensitive << ( icmp_ln631_reg_935 );
    sensitive << ( xor_ln631_fu_619_p2 );

    SC_METHOD(thread_and_ln639_fu_647_p2);
    sensitive << ( xor_ln621_2_reg_916 );
    sensitive << ( icmp_ln631_reg_935 );

    SC_METHOD(thread_and_ln641_fu_666_p2);
    sensitive << ( icmp_ln641_fu_656_p2 );
    sensitive << ( Range1_all_zeros_fu_661_p2 );

    SC_METHOD(thread_and_ln642_fu_558_p2);
    sensitive << ( icmp_ln642_fu_534_p2 );
    sensitive << ( or_ln639_fu_552_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( p_src_data_stream_V_empty_n );
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln2527_reg_788 );
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( icmp_ln2527_reg_788_pp0_iter10_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( p_src_data_stream_V_empty_n );
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln2527_reg_788 );
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( icmp_ln2527_reg_788_pp0_iter10_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( p_src_data_stream_V_empty_n );
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln2527_reg_788 );
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( icmp_ln2527_reg_788_pp0_iter10_reg );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter7);

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter8);

    SC_METHOD(thread_ap_block_state12_pp0_stage0_iter9);

    SC_METHOD(thread_ap_block_state13_pp0_stage0_iter10);

    SC_METHOD(thread_ap_block_state14_pp0_stage0_iter11);
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( icmp_ln2527_reg_788_pp0_iter10_reg );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( p_src_data_stream_V_empty_n );
    sensitive << ( icmp_ln2527_reg_788 );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter6);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( icmp_ln2527_fu_190_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( icmp_ln2526_fu_178_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_enable_reg_pp0_iter10 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( icmp_ln2526_fu_178_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ashr_ln586_fu_324_p2);
    sensitive << ( p_Result_12_fu_313_p1 );
    sensitive << ( zext_ln586_fu_320_p1 );

    SC_METHOD(thread_ashr_ln623_fu_488_p2);
    sensitive << ( p_Result_12_fu_313_p1 );
    sensitive << ( zext_ln623_fu_484_p1 );

    SC_METHOD(thread_deleted_zeros_fu_708_p3);
    sensitive << ( and_ln603_4_reg_906_pp0_iter10_reg );
    sensitive << ( select_ln639_reg_969 );
    sensitive << ( select_ln639_2_reg_974 );

    SC_METHOD(thread_grp_fu_175_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_175_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_reg_797 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_i_fu_184_p2);
    sensitive << ( i_0_reg_153 );

    SC_METHOD(thread_icmp_ln2526_fu_178_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_153 );

    SC_METHOD(thread_icmp_ln2527_fu_190_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( j_0_reg_164 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln571_fu_237_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_788_pp0_iter7_reg );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( trunc_ln368_fu_209_p1 );

    SC_METHOD(thread_icmp_ln581_fu_249_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_788_pp0_iter7_reg );
    sensitive << ( F2_fu_243_p2 );
    sensitive << ( ap_enable_reg_pp0_iter8 );

    SC_METHOD(thread_icmp_ln582_fu_269_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_788_pp0_iter7_reg );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( tmp_V_fu_213_p4 );

    SC_METHOD(thread_icmp_ln585_fu_279_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_788_pp0_iter7_reg );
    sensitive << ( F2_4_fu_261_p3 );
    sensitive << ( ap_enable_reg_pp0_iter8 );

    SC_METHOD(thread_icmp_ln591_fu_341_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_788_pp0_iter8_reg );
    sensitive << ( F2_reg_830 );
    sensitive << ( ap_enable_reg_pp0_iter9 );

    SC_METHOD(thread_icmp_ln603_fu_295_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_788_pp0_iter7_reg );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( tmp_56_fu_285_p4 );

    SC_METHOD(thread_icmp_ln621_fu_464_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_788_pp0_iter8_reg );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( pos1_fu_446_p2 );

    SC_METHOD(thread_icmp_ln631_fu_518_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_788_pp0_iter8_reg );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( pos2_fu_455_p2 );

    SC_METHOD(thread_icmp_ln641_fu_656_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_788_pp0_iter9_reg );
    sensitive << ( and_ln603_4_reg_906 );
    sensitive << ( Range2_V_2_reg_946 );
    sensitive << ( ap_enable_reg_pp0_iter10 );

    SC_METHOD(thread_icmp_ln642_fu_534_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_788_pp0_iter8_reg );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( pos2_fu_455_p2 );

    SC_METHOD(thread_icmp_ln833_fu_227_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_788_pp0_iter7_reg );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( tmp_V_fu_213_p4 );

    SC_METHOD(thread_icmp_ln837_fu_301_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_788_pp0_iter8_reg );
    sensitive << ( tmp_V_4_reg_812 );
    sensitive << ( ap_enable_reg_pp0_iter9 );

    SC_METHOD(thread_j_fu_196_p2);
    sensitive << ( j_0_reg_164 );

    SC_METHOD(thread_lD_fu_494_p1);
    sensitive << ( ashr_ln623_fu_488_p2 );

    SC_METHOD(thread_or_ln571_2_fu_759_p2);
    sensitive << ( icmp_ln571_reg_824_pp0_iter10_reg );
    sensitive << ( and_ln428_fu_704_p2 );

    SC_METHOD(thread_or_ln571_fu_746_p2);
    sensitive << ( and_ln571_fu_741_p2 );
    sensitive << ( and_ln428_fu_704_p2 );

    SC_METHOD(thread_or_ln581_fu_419_p2);
    sensitive << ( icmp_ln581_reg_838 );
    sensitive << ( icmp_ln582_reg_850 );

    SC_METHOD(thread_or_ln603_fu_428_p2);
    sensitive << ( or_ln581_fu_419_p2 );
    sensitive << ( xor_ln603_fu_423_p2 );

    SC_METHOD(thread_or_ln639_fu_552_p2);
    sensitive << ( tmp_59_fu_470_p3 );
    sensitive << ( xor_ln639_2_fu_546_p2 );

    SC_METHOD(thread_or_ln645_fu_672_p2);
    sensitive << ( xor_ln621_2_reg_916 );
    sensitive << ( Range1_all_zeros_2_reg_952 );

    SC_METHOD(thread_or_ln658_fu_718_p2);
    sensitive << ( xor_ln621_fu_713_p2 );
    sensitive << ( deleted_zeros_fu_708_p3 );

    SC_METHOD(thread_p_Result_12_fu_313_p1);
    sensitive << ( tmp_1_i_fu_306_p3 );

    SC_METHOD(thread_p_Result_13_fu_371_p3);
    sensitive << ( p_Val2_18_fu_334_p3 );

    SC_METHOD(thread_p_Result_s_fu_355_p3);
    sensitive << ( p_Result_12_fu_313_p1 );
    sensitive << ( zext_ln591_fu_351_p1 );

    SC_METHOD(thread_p_Val2_18_fu_334_p3);
    sensitive << ( icmp_ln585_reg_863 );
    sensitive << ( trunc_ln586_fu_330_p1 );

    SC_METHOD(thread_p_Val2_19_fu_383_p2);
    sensitive << ( p_Val2_18_fu_334_p3 );
    sensitive << ( zext_ln415_fu_379_p1 );

    SC_METHOD(thread_p_Val2_20_fu_611_p3);
    sensitive << ( and_ln603_fu_606_p2 );
    sensitive << ( shl_ln604_fu_567_p2 );
    sensitive << ( select_ln403_2_fu_594_p3 );

    SC_METHOD(thread_p_Val2_s_fu_206_p1);
    sensitive << ( x_assign_reg_807 );

    SC_METHOD(thread_p_dst_data_stream_V_blk_n);
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( icmp_ln2527_reg_788_pp0_iter10_reg );

    SC_METHOD(thread_p_dst_data_stream_V_din);
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( icmp_ln2527_reg_788_pp0_iter10_reg );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( xor_ln571_fu_764_p2 );
    sensitive << ( select_ln340_fu_724_p3 );
    sensitive << ( select_ln571_fu_752_p3 );

    SC_METHOD(thread_p_dst_data_stream_V_write);
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( icmp_ln2527_reg_788_pp0_iter10_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_p_src_data_stream_V_blk_n);
    sensitive << ( p_src_data_stream_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln2527_reg_788 );

    SC_METHOD(thread_p_src_data_stream_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln2527_reg_788 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_pos1_fu_446_p2);
    sensitive << ( F2_reg_830 );

    SC_METHOD(thread_pos2_fu_455_p2);
    sensitive << ( F2_reg_830 );

    SC_METHOD(thread_qb_fu_363_p3);
    sensitive << ( icmp_ln591_fu_341_p2 );
    sensitive << ( p_Result_s_fu_355_p3 );

    SC_METHOD(thread_r_V_fu_629_p2);
    sensitive << ( zext_ln635_reg_941 );

    SC_METHOD(thread_select_ln340_fu_724_p3);
    sensitive << ( p_Val2_20_reg_963 );
    sensitive << ( or_ln658_fu_718_p2 );

    SC_METHOD(thread_select_ln403_2_fu_594_p3);
    sensitive << ( p_Val2_19_reg_885 );
    sensitive << ( and_ln403_2_fu_589_p2 );
    sensitive << ( select_ln403_fu_578_p3 );

    SC_METHOD(thread_select_ln403_fu_578_p3);
    sensitive << ( p_Val2_19_reg_885 );
    sensitive << ( and_ln403_reg_896 );
    sensitive << ( select_ln582_fu_572_p3 );

    SC_METHOD(thread_select_ln571_fu_752_p3);
    sensitive << ( p_Val2_20_reg_963 );
    sensitive << ( or_ln571_fu_746_p2 );

    SC_METHOD(thread_select_ln582_fu_572_p3);
    sensitive << ( icmp_ln582_reg_850_pp0_iter9_reg );
    sensitive << ( trunc_ln583_reg_857_pp0_iter9_reg );

    SC_METHOD(thread_select_ln631_fu_639_p3);
    sensitive << ( xor_ln631_fu_619_p2 );
    sensitive << ( and_ln631_fu_624_p2 );
    sensitive << ( Range2_all_ones_fu_634_p2 );

    SC_METHOD(thread_select_ln639_2_fu_696_p3);
    sensitive << ( and_ln639_fu_647_p2 );
    sensitive << ( and_ln641_fu_666_p2 );
    sensitive << ( select_ln642_2_fu_689_p3 );

    SC_METHOD(thread_select_ln639_fu_681_p3);
    sensitive << ( and_ln639_fu_647_p2 );
    sensitive << ( Range1_all_ones_fu_651_p2 );
    sensitive << ( select_ln642_fu_676_p3 );

    SC_METHOD(thread_select_ln642_2_fu_689_p3);
    sensitive << ( and_ln642_reg_957 );
    sensitive << ( Range1_all_zeros_fu_661_p2 );
    sensitive << ( or_ln645_fu_672_p2 );

    SC_METHOD(thread_select_ln642_fu_676_p3);
    sensitive << ( xor_ln621_2_reg_916 );
    sensitive << ( Range1_all_ones_2_reg_923 );
    sensitive << ( and_ln642_reg_957 );

    SC_METHOD(thread_sext_ln581_fu_317_p1);
    sensitive << ( F2_4_reg_844 );

    SC_METHOD(thread_sext_ln618_fu_451_p1);
    sensitive << ( pos1_fu_446_p2 );

    SC_METHOD(thread_sext_ln619_fu_460_p1);
    sensitive << ( pos2_fu_455_p2 );

    SC_METHOD(thread_shl_ln604_fu_567_p2);
    sensitive << ( trunc_ln583_reg_857_pp0_iter9_reg );
    sensitive << ( trunc_ln581_fu_564_p1 );

    SC_METHOD(thread_sub_ln581_fu_255_p2);
    sensitive << ( F2_fu_243_p2 );

    SC_METHOD(thread_tmp_1_i_fu_306_p3);
    sensitive << ( tmp_V_4_reg_812 );

    SC_METHOD(thread_tmp_56_fu_285_p4);
    sensitive << ( F2_4_fu_261_p3 );

    SC_METHOD(thread_tmp_58_fu_389_p3);
    sensitive << ( p_Val2_19_fu_383_p2 );

    SC_METHOD(thread_tmp_59_fu_470_p3);
    sensitive << ( pos1_fu_446_p2 );

    SC_METHOD(thread_tmp_V_4_fu_223_p1);
    sensitive << ( p_Val2_s_fu_206_p1 );

    SC_METHOD(thread_tmp_V_fu_213_p4);
    sensitive << ( p_Val2_s_fu_206_p1 );

    SC_METHOD(thread_trunc_ln368_fu_209_p1);
    sensitive << ( p_Val2_s_fu_206_p1 );

    SC_METHOD(thread_trunc_ln581_fu_564_p1);
    sensitive << ( F2_4_reg_844_pp0_iter9_reg );

    SC_METHOD(thread_trunc_ln583_fu_275_p1);
    sensitive << ( p_Val2_s_fu_206_p1 );

    SC_METHOD(thread_trunc_ln586_fu_330_p1);
    sensitive << ( ashr_ln586_fu_324_p2 );

    SC_METHOD(thread_xor_ln403_fu_584_p2);
    sensitive << ( p_Result_13_reg_880 );

    SC_METHOD(thread_xor_ln416_fu_397_p2);
    sensitive << ( tmp_58_fu_389_p3 );

    SC_METHOD(thread_xor_ln428_fu_735_p2);
    sensitive << ( and_ln428_2_fu_731_p2 );

    SC_METHOD(thread_xor_ln571_fu_764_p2);
    sensitive << ( or_ln571_2_fu_759_p2 );

    SC_METHOD(thread_xor_ln581_fu_601_p2);
    sensitive << ( or_ln581_reg_901 );

    SC_METHOD(thread_xor_ln582_fu_403_p2);
    sensitive << ( icmp_ln582_reg_850 );

    SC_METHOD(thread_xor_ln603_fu_423_p2);
    sensitive << ( icmp_ln603_reg_868 );

    SC_METHOD(thread_xor_ln621_2_fu_478_p2);
    sensitive << ( tmp_59_fu_470_p3 );

    SC_METHOD(thread_xor_ln621_fu_713_p2);
    sensitive << ( icmp_ln621_reg_911_pp0_iter10_reg );

    SC_METHOD(thread_xor_ln631_fu_619_p2);
    sensitive << ( tmp_60_reg_930 );

    SC_METHOD(thread_xor_ln639_2_fu_546_p2);
    sensitive << ( icmp_ln631_fu_518_p2 );

    SC_METHOD(thread_zext_ln415_fu_379_p1);
    sensitive << ( qb_fu_363_p3 );

    SC_METHOD(thread_zext_ln461_fu_233_p1);
    sensitive << ( tmp_V_fu_213_p4 );

    SC_METHOD(thread_zext_ln586_fu_320_p1);
    sensitive << ( sext_ln581_fu_317_p1 );

    SC_METHOD(thread_zext_ln591_fu_351_p1);
    sensitive << ( add_ln591_fu_346_p2 );

    SC_METHOD(thread_zext_ln623_fu_484_p1);
    sensitive << ( sext_ln618_fu_451_p1 );

    SC_METHOD(thread_zext_ln635_fu_524_p1);
    sensitive << ( sext_ln619_fu_460_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( icmp_ln2526_fu_178_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln2527_fu_190_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter10 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter11 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter7 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter8 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter9 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter10 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "ConvertScaleAbs_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, p_src_data_stream_V_dout, "(port)p_src_data_stream_V_dout");
    sc_trace(mVcdFile, p_src_data_stream_V_empty_n, "(port)p_src_data_stream_V_empty_n");
    sc_trace(mVcdFile, p_src_data_stream_V_read, "(port)p_src_data_stream_V_read");
    sc_trace(mVcdFile, p_dst_data_stream_V_din, "(port)p_dst_data_stream_V_din");
    sc_trace(mVcdFile, p_dst_data_stream_V_full_n, "(port)p_dst_data_stream_V_full_n");
    sc_trace(mVcdFile, p_dst_data_stream_V_write, "(port)p_dst_data_stream_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, p_src_data_stream_V_blk_n, "p_src_data_stream_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln2527_reg_788, "icmp_ln2527_reg_788");
    sc_trace(mVcdFile, p_dst_data_stream_V_blk_n, "p_dst_data_stream_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter11, "ap_enable_reg_pp0_iter11");
    sc_trace(mVcdFile, icmp_ln2527_reg_788_pp0_iter10_reg, "icmp_ln2527_reg_788_pp0_iter10_reg");
    sc_trace(mVcdFile, j_0_reg_164, "j_0_reg_164");
    sc_trace(mVcdFile, icmp_ln2526_fu_178_p2, "icmp_ln2526_fu_178_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_fu_184_p2, "i_fu_184_p2");
    sc_trace(mVcdFile, i_reg_783, "i_reg_783");
    sc_trace(mVcdFile, icmp_ln2527_fu_190_p2, "icmp_ln2527_fu_190_p2");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter2, "ap_block_state5_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter3, "ap_block_state6_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter4, "ap_block_state7_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter5, "ap_block_state8_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter6, "ap_block_state9_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter7, "ap_block_state10_pp0_stage0_iter7");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter8, "ap_block_state11_pp0_stage0_iter8");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage0_iter9, "ap_block_state12_pp0_stage0_iter9");
    sc_trace(mVcdFile, ap_block_state13_pp0_stage0_iter10, "ap_block_state13_pp0_stage0_iter10");
    sc_trace(mVcdFile, ap_block_state14_pp0_stage0_iter11, "ap_block_state14_pp0_stage0_iter11");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, icmp_ln2527_reg_788_pp0_iter1_reg, "icmp_ln2527_reg_788_pp0_iter1_reg");
    sc_trace(mVcdFile, icmp_ln2527_reg_788_pp0_iter2_reg, "icmp_ln2527_reg_788_pp0_iter2_reg");
    sc_trace(mVcdFile, icmp_ln2527_reg_788_pp0_iter3_reg, "icmp_ln2527_reg_788_pp0_iter3_reg");
    sc_trace(mVcdFile, icmp_ln2527_reg_788_pp0_iter4_reg, "icmp_ln2527_reg_788_pp0_iter4_reg");
    sc_trace(mVcdFile, icmp_ln2527_reg_788_pp0_iter5_reg, "icmp_ln2527_reg_788_pp0_iter5_reg");
    sc_trace(mVcdFile, icmp_ln2527_reg_788_pp0_iter6_reg, "icmp_ln2527_reg_788_pp0_iter6_reg");
    sc_trace(mVcdFile, icmp_ln2527_reg_788_pp0_iter7_reg, "icmp_ln2527_reg_788_pp0_iter7_reg");
    sc_trace(mVcdFile, icmp_ln2527_reg_788_pp0_iter8_reg, "icmp_ln2527_reg_788_pp0_iter8_reg");
    sc_trace(mVcdFile, icmp_ln2527_reg_788_pp0_iter9_reg, "icmp_ln2527_reg_788_pp0_iter9_reg");
    sc_trace(mVcdFile, j_fu_196_p2, "j_fu_196_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_reg_797, "tmp_reg_797");
    sc_trace(mVcdFile, grp_fu_175_p1, "grp_fu_175_p1");
    sc_trace(mVcdFile, x_assign_reg_807, "x_assign_reg_807");
    sc_trace(mVcdFile, tmp_V_4_fu_223_p1, "tmp_V_4_fu_223_p1");
    sc_trace(mVcdFile, tmp_V_4_reg_812, "tmp_V_4_reg_812");
    sc_trace(mVcdFile, icmp_ln833_fu_227_p2, "icmp_ln833_fu_227_p2");
    sc_trace(mVcdFile, icmp_ln833_reg_818, "icmp_ln833_reg_818");
    sc_trace(mVcdFile, icmp_ln833_reg_818_pp0_iter9_reg, "icmp_ln833_reg_818_pp0_iter9_reg");
    sc_trace(mVcdFile, icmp_ln833_reg_818_pp0_iter10_reg, "icmp_ln833_reg_818_pp0_iter10_reg");
    sc_trace(mVcdFile, icmp_ln571_fu_237_p2, "icmp_ln571_fu_237_p2");
    sc_trace(mVcdFile, icmp_ln571_reg_824, "icmp_ln571_reg_824");
    sc_trace(mVcdFile, icmp_ln571_reg_824_pp0_iter9_reg, "icmp_ln571_reg_824_pp0_iter9_reg");
    sc_trace(mVcdFile, icmp_ln571_reg_824_pp0_iter10_reg, "icmp_ln571_reg_824_pp0_iter10_reg");
    sc_trace(mVcdFile, F2_fu_243_p2, "F2_fu_243_p2");
    sc_trace(mVcdFile, F2_reg_830, "F2_reg_830");
    sc_trace(mVcdFile, icmp_ln581_fu_249_p2, "icmp_ln581_fu_249_p2");
    sc_trace(mVcdFile, icmp_ln581_reg_838, "icmp_ln581_reg_838");
    sc_trace(mVcdFile, F2_4_fu_261_p3, "F2_4_fu_261_p3");
    sc_trace(mVcdFile, F2_4_reg_844, "F2_4_reg_844");
    sc_trace(mVcdFile, F2_4_reg_844_pp0_iter9_reg, "F2_4_reg_844_pp0_iter9_reg");
    sc_trace(mVcdFile, icmp_ln582_fu_269_p2, "icmp_ln582_fu_269_p2");
    sc_trace(mVcdFile, icmp_ln582_reg_850, "icmp_ln582_reg_850");
    sc_trace(mVcdFile, icmp_ln582_reg_850_pp0_iter9_reg, "icmp_ln582_reg_850_pp0_iter9_reg");
    sc_trace(mVcdFile, trunc_ln583_fu_275_p1, "trunc_ln583_fu_275_p1");
    sc_trace(mVcdFile, trunc_ln583_reg_857, "trunc_ln583_reg_857");
    sc_trace(mVcdFile, trunc_ln583_reg_857_pp0_iter9_reg, "trunc_ln583_reg_857_pp0_iter9_reg");
    sc_trace(mVcdFile, icmp_ln585_fu_279_p2, "icmp_ln585_fu_279_p2");
    sc_trace(mVcdFile, icmp_ln585_reg_863, "icmp_ln585_reg_863");
    sc_trace(mVcdFile, icmp_ln603_fu_295_p2, "icmp_ln603_fu_295_p2");
    sc_trace(mVcdFile, icmp_ln603_reg_868, "icmp_ln603_reg_868");
    sc_trace(mVcdFile, icmp_ln603_reg_868_pp0_iter9_reg, "icmp_ln603_reg_868_pp0_iter9_reg");
    sc_trace(mVcdFile, icmp_ln837_fu_301_p2, "icmp_ln837_fu_301_p2");
    sc_trace(mVcdFile, icmp_ln837_reg_874, "icmp_ln837_reg_874");
    sc_trace(mVcdFile, icmp_ln837_reg_874_pp0_iter10_reg, "icmp_ln837_reg_874_pp0_iter10_reg");
    sc_trace(mVcdFile, p_Result_13_fu_371_p3, "p_Result_13_fu_371_p3");
    sc_trace(mVcdFile, p_Result_13_reg_880, "p_Result_13_reg_880");
    sc_trace(mVcdFile, p_Val2_19_fu_383_p2, "p_Val2_19_fu_383_p2");
    sc_trace(mVcdFile, p_Val2_19_reg_885, "p_Val2_19_reg_885");
    sc_trace(mVcdFile, and_ln581_fu_408_p2, "and_ln581_fu_408_p2");
    sc_trace(mVcdFile, and_ln581_reg_891, "and_ln581_reg_891");
    sc_trace(mVcdFile, and_ln403_fu_413_p2, "and_ln403_fu_413_p2");
    sc_trace(mVcdFile, and_ln403_reg_896, "and_ln403_reg_896");
    sc_trace(mVcdFile, or_ln581_fu_419_p2, "or_ln581_fu_419_p2");
    sc_trace(mVcdFile, or_ln581_reg_901, "or_ln581_reg_901");
    sc_trace(mVcdFile, and_ln603_4_fu_440_p2, "and_ln603_4_fu_440_p2");
    sc_trace(mVcdFile, and_ln603_4_reg_906, "and_ln603_4_reg_906");
    sc_trace(mVcdFile, and_ln603_4_reg_906_pp0_iter10_reg, "and_ln603_4_reg_906_pp0_iter10_reg");
    sc_trace(mVcdFile, icmp_ln621_fu_464_p2, "icmp_ln621_fu_464_p2");
    sc_trace(mVcdFile, icmp_ln621_reg_911, "icmp_ln621_reg_911");
    sc_trace(mVcdFile, icmp_ln621_reg_911_pp0_iter10_reg, "icmp_ln621_reg_911_pp0_iter10_reg");
    sc_trace(mVcdFile, xor_ln621_2_fu_478_p2, "xor_ln621_2_fu_478_p2");
    sc_trace(mVcdFile, xor_ln621_2_reg_916, "xor_ln621_2_reg_916");
    sc_trace(mVcdFile, Range1_all_ones_2_fu_504_p2, "Range1_all_ones_2_fu_504_p2");
    sc_trace(mVcdFile, Range1_all_ones_2_reg_923, "Range1_all_ones_2_reg_923");
    sc_trace(mVcdFile, tmp_60_reg_930, "tmp_60_reg_930");
    sc_trace(mVcdFile, icmp_ln631_fu_518_p2, "icmp_ln631_fu_518_p2");
    sc_trace(mVcdFile, icmp_ln631_reg_935, "icmp_ln631_reg_935");
    sc_trace(mVcdFile, zext_ln635_fu_524_p1, "zext_ln635_fu_524_p1");
    sc_trace(mVcdFile, zext_ln635_reg_941, "zext_ln635_reg_941");
    sc_trace(mVcdFile, Range2_V_2_fu_528_p2, "Range2_V_2_fu_528_p2");
    sc_trace(mVcdFile, Range2_V_2_reg_946, "Range2_V_2_reg_946");
    sc_trace(mVcdFile, Range1_all_zeros_2_fu_540_p2, "Range1_all_zeros_2_fu_540_p2");
    sc_trace(mVcdFile, Range1_all_zeros_2_reg_952, "Range1_all_zeros_2_reg_952");
    sc_trace(mVcdFile, and_ln642_fu_558_p2, "and_ln642_fu_558_p2");
    sc_trace(mVcdFile, and_ln642_reg_957, "and_ln642_reg_957");
    sc_trace(mVcdFile, p_Val2_20_fu_611_p3, "p_Val2_20_fu_611_p3");
    sc_trace(mVcdFile, p_Val2_20_reg_963, "p_Val2_20_reg_963");
    sc_trace(mVcdFile, select_ln639_fu_681_p3, "select_ln639_fu_681_p3");
    sc_trace(mVcdFile, select_ln639_reg_969, "select_ln639_reg_969");
    sc_trace(mVcdFile, select_ln639_2_fu_696_p3, "select_ln639_2_fu_696_p3");
    sc_trace(mVcdFile, select_ln639_2_reg_974, "select_ln639_2_reg_974");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter7, "ap_enable_reg_pp0_iter7");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter8, "ap_enable_reg_pp0_iter8");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter9, "ap_enable_reg_pp0_iter9");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter10, "ap_enable_reg_pp0_iter10");
    sc_trace(mVcdFile, i_0_reg_153, "i_0_reg_153");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, grp_fu_175_p0, "grp_fu_175_p0");
    sc_trace(mVcdFile, p_Val2_s_fu_206_p1, "p_Val2_s_fu_206_p1");
    sc_trace(mVcdFile, tmp_V_fu_213_p4, "tmp_V_fu_213_p4");
    sc_trace(mVcdFile, trunc_ln368_fu_209_p1, "trunc_ln368_fu_209_p1");
    sc_trace(mVcdFile, zext_ln461_fu_233_p1, "zext_ln461_fu_233_p1");
    sc_trace(mVcdFile, sub_ln581_fu_255_p2, "sub_ln581_fu_255_p2");
    sc_trace(mVcdFile, tmp_56_fu_285_p4, "tmp_56_fu_285_p4");
    sc_trace(mVcdFile, tmp_1_i_fu_306_p3, "tmp_1_i_fu_306_p3");
    sc_trace(mVcdFile, sext_ln581_fu_317_p1, "sext_ln581_fu_317_p1");
    sc_trace(mVcdFile, p_Result_12_fu_313_p1, "p_Result_12_fu_313_p1");
    sc_trace(mVcdFile, zext_ln586_fu_320_p1, "zext_ln586_fu_320_p1");
    sc_trace(mVcdFile, ashr_ln586_fu_324_p2, "ashr_ln586_fu_324_p2");
    sc_trace(mVcdFile, trunc_ln586_fu_330_p1, "trunc_ln586_fu_330_p1");
    sc_trace(mVcdFile, add_ln591_fu_346_p2, "add_ln591_fu_346_p2");
    sc_trace(mVcdFile, zext_ln591_fu_351_p1, "zext_ln591_fu_351_p1");
    sc_trace(mVcdFile, icmp_ln591_fu_341_p2, "icmp_ln591_fu_341_p2");
    sc_trace(mVcdFile, p_Result_s_fu_355_p3, "p_Result_s_fu_355_p3");
    sc_trace(mVcdFile, p_Val2_18_fu_334_p3, "p_Val2_18_fu_334_p3");
    sc_trace(mVcdFile, qb_fu_363_p3, "qb_fu_363_p3");
    sc_trace(mVcdFile, zext_ln415_fu_379_p1, "zext_ln415_fu_379_p1");
    sc_trace(mVcdFile, tmp_58_fu_389_p3, "tmp_58_fu_389_p3");
    sc_trace(mVcdFile, xor_ln582_fu_403_p2, "xor_ln582_fu_403_p2");
    sc_trace(mVcdFile, xor_ln603_fu_423_p2, "xor_ln603_fu_423_p2");
    sc_trace(mVcdFile, or_ln603_fu_428_p2, "or_ln603_fu_428_p2");
    sc_trace(mVcdFile, xor_ln416_fu_397_p2, "xor_ln416_fu_397_p2");
    sc_trace(mVcdFile, and_ln603_3_fu_434_p2, "and_ln603_3_fu_434_p2");
    sc_trace(mVcdFile, pos1_fu_446_p2, "pos1_fu_446_p2");
    sc_trace(mVcdFile, pos2_fu_455_p2, "pos2_fu_455_p2");
    sc_trace(mVcdFile, tmp_59_fu_470_p3, "tmp_59_fu_470_p3");
    sc_trace(mVcdFile, sext_ln618_fu_451_p1, "sext_ln618_fu_451_p1");
    sc_trace(mVcdFile, zext_ln623_fu_484_p1, "zext_ln623_fu_484_p1");
    sc_trace(mVcdFile, ashr_ln623_fu_488_p2, "ashr_ln623_fu_488_p2");
    sc_trace(mVcdFile, lD_fu_494_p1, "lD_fu_494_p1");
    sc_trace(mVcdFile, and_ln621_fu_498_p2, "and_ln621_fu_498_p2");
    sc_trace(mVcdFile, sext_ln619_fu_460_p1, "sext_ln619_fu_460_p1");
    sc_trace(mVcdFile, xor_ln639_2_fu_546_p2, "xor_ln639_2_fu_546_p2");
    sc_trace(mVcdFile, icmp_ln642_fu_534_p2, "icmp_ln642_fu_534_p2");
    sc_trace(mVcdFile, or_ln639_fu_552_p2, "or_ln639_fu_552_p2");
    sc_trace(mVcdFile, trunc_ln581_fu_564_p1, "trunc_ln581_fu_564_p1");
    sc_trace(mVcdFile, select_ln582_fu_572_p3, "select_ln582_fu_572_p3");
    sc_trace(mVcdFile, xor_ln403_fu_584_p2, "xor_ln403_fu_584_p2");
    sc_trace(mVcdFile, and_ln403_2_fu_589_p2, "and_ln403_2_fu_589_p2");
    sc_trace(mVcdFile, select_ln403_fu_578_p3, "select_ln403_fu_578_p3");
    sc_trace(mVcdFile, xor_ln581_fu_601_p2, "xor_ln581_fu_601_p2");
    sc_trace(mVcdFile, and_ln603_fu_606_p2, "and_ln603_fu_606_p2");
    sc_trace(mVcdFile, shl_ln604_fu_567_p2, "shl_ln604_fu_567_p2");
    sc_trace(mVcdFile, select_ln403_2_fu_594_p3, "select_ln403_2_fu_594_p3");
    sc_trace(mVcdFile, xor_ln631_fu_619_p2, "xor_ln631_fu_619_p2");
    sc_trace(mVcdFile, r_V_fu_629_p2, "r_V_fu_629_p2");
    sc_trace(mVcdFile, and_ln631_fu_624_p2, "and_ln631_fu_624_p2");
    sc_trace(mVcdFile, Range2_all_ones_fu_634_p2, "Range2_all_ones_fu_634_p2");
    sc_trace(mVcdFile, select_ln631_fu_639_p3, "select_ln631_fu_639_p3");
    sc_trace(mVcdFile, icmp_ln641_fu_656_p2, "icmp_ln641_fu_656_p2");
    sc_trace(mVcdFile, Range1_all_zeros_fu_661_p2, "Range1_all_zeros_fu_661_p2");
    sc_trace(mVcdFile, and_ln639_fu_647_p2, "and_ln639_fu_647_p2");
    sc_trace(mVcdFile, Range1_all_ones_fu_651_p2, "Range1_all_ones_fu_651_p2");
    sc_trace(mVcdFile, select_ln642_fu_676_p3, "select_ln642_fu_676_p3");
    sc_trace(mVcdFile, or_ln645_fu_672_p2, "or_ln645_fu_672_p2");
    sc_trace(mVcdFile, and_ln641_fu_666_p2, "and_ln641_fu_666_p2");
    sc_trace(mVcdFile, select_ln642_2_fu_689_p3, "select_ln642_2_fu_689_p3");
    sc_trace(mVcdFile, xor_ln621_fu_713_p2, "xor_ln621_fu_713_p2");
    sc_trace(mVcdFile, deleted_zeros_fu_708_p3, "deleted_zeros_fu_708_p3");
    sc_trace(mVcdFile, or_ln658_fu_718_p2, "or_ln658_fu_718_p2");
    sc_trace(mVcdFile, and_ln428_2_fu_731_p2, "and_ln428_2_fu_731_p2");
    sc_trace(mVcdFile, xor_ln428_fu_735_p2, "xor_ln428_fu_735_p2");
    sc_trace(mVcdFile, and_ln571_fu_741_p2, "and_ln571_fu_741_p2");
    sc_trace(mVcdFile, and_ln428_fu_704_p2, "and_ln428_fu_704_p2");
    sc_trace(mVcdFile, or_ln571_fu_746_p2, "or_ln571_fu_746_p2");
    sc_trace(mVcdFile, or_ln571_2_fu_759_p2, "or_ln571_2_fu_759_p2");
    sc_trace(mVcdFile, xor_ln571_fu_764_p2, "xor_ln571_fu_764_p2");
    sc_trace(mVcdFile, select_ln340_fu_724_p3, "select_ln340_fu_724_p3");
    sc_trace(mVcdFile, select_ln571_fu_752_p3, "select_ln571_fu_752_p3");
    sc_trace(mVcdFile, grp_fu_175_ce, "grp_fu_175_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

ConvertScaleAbs::~ConvertScaleAbs() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete sobel_accel_sitodtde_U85;
}

void ConvertScaleAbs::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(icmp_ln2526_fu_178_p2.read(), ap_const_lv1_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2526_fu_178_p2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter10 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter10 = ap_enable_reg_pp0_iter9.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter11 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter11 = ap_enable_reg_pp0_iter10.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2526_fu_178_p2.read()))) {
            ap_enable_reg_pp0_iter11 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter7 = ap_enable_reg_pp0_iter6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter8 = ap_enable_reg_pp0_iter7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter9 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter9 = ap_enable_reg_pp0_iter8.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        i_0_reg_153 = i_reg_783.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i_0_reg_153 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2527_fu_190_p2.read()))) {
        j_0_reg_164 = j_fu_196_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2526_fu_178_p2.read()))) {
        j_0_reg_164 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2527_reg_788_pp0_iter7_reg.read()))) {
        F2_4_reg_844 = F2_4_fu_261_p3.read();
        F2_reg_830 = F2_fu_243_p2.read();
        icmp_ln571_reg_824 = icmp_ln571_fu_237_p2.read();
        icmp_ln581_reg_838 = icmp_ln581_fu_249_p2.read();
        icmp_ln582_reg_850 = icmp_ln582_fu_269_p2.read();
        icmp_ln585_reg_863 = icmp_ln585_fu_279_p2.read();
        icmp_ln603_reg_868 = icmp_ln603_fu_295_p2.read();
        icmp_ln833_reg_818 = icmp_ln833_fu_227_p2.read();
        tmp_V_4_reg_812 = tmp_V_4_fu_223_p1.read();
        trunc_ln583_reg_857 = trunc_ln583_fu_275_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        F2_4_reg_844_pp0_iter9_reg = F2_4_reg_844.read();
        and_ln603_4_reg_906_pp0_iter10_reg = and_ln603_4_reg_906.read();
        icmp_ln2527_reg_788_pp0_iter10_reg = icmp_ln2527_reg_788_pp0_iter9_reg.read();
        icmp_ln2527_reg_788_pp0_iter2_reg = icmp_ln2527_reg_788_pp0_iter1_reg.read();
        icmp_ln2527_reg_788_pp0_iter3_reg = icmp_ln2527_reg_788_pp0_iter2_reg.read();
        icmp_ln2527_reg_788_pp0_iter4_reg = icmp_ln2527_reg_788_pp0_iter3_reg.read();
        icmp_ln2527_reg_788_pp0_iter5_reg = icmp_ln2527_reg_788_pp0_iter4_reg.read();
        icmp_ln2527_reg_788_pp0_iter6_reg = icmp_ln2527_reg_788_pp0_iter5_reg.read();
        icmp_ln2527_reg_788_pp0_iter7_reg = icmp_ln2527_reg_788_pp0_iter6_reg.read();
        icmp_ln2527_reg_788_pp0_iter8_reg = icmp_ln2527_reg_788_pp0_iter7_reg.read();
        icmp_ln2527_reg_788_pp0_iter9_reg = icmp_ln2527_reg_788_pp0_iter8_reg.read();
        icmp_ln571_reg_824_pp0_iter10_reg = icmp_ln571_reg_824_pp0_iter9_reg.read();
        icmp_ln571_reg_824_pp0_iter9_reg = icmp_ln571_reg_824.read();
        icmp_ln582_reg_850_pp0_iter9_reg = icmp_ln582_reg_850.read();
        icmp_ln603_reg_868_pp0_iter9_reg = icmp_ln603_reg_868.read();
        icmp_ln621_reg_911_pp0_iter10_reg = icmp_ln621_reg_911.read();
        icmp_ln833_reg_818_pp0_iter10_reg = icmp_ln833_reg_818_pp0_iter9_reg.read();
        icmp_ln833_reg_818_pp0_iter9_reg = icmp_ln833_reg_818.read();
        icmp_ln837_reg_874_pp0_iter10_reg = icmp_ln837_reg_874.read();
        trunc_ln583_reg_857_pp0_iter9_reg = trunc_ln583_reg_857.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2527_reg_788_pp0_iter8_reg.read()))) {
        Range1_all_ones_2_reg_923 = Range1_all_ones_2_fu_504_p2.read();
        Range1_all_zeros_2_reg_952 = Range1_all_zeros_2_fu_540_p2.read();
        Range2_V_2_reg_946 = Range2_V_2_fu_528_p2.read();
        and_ln403_reg_896 = and_ln403_fu_413_p2.read();
        and_ln581_reg_891 = and_ln581_fu_408_p2.read();
        and_ln603_4_reg_906 = and_ln603_4_fu_440_p2.read();
        and_ln642_reg_957 = and_ln642_fu_558_p2.read();
        icmp_ln621_reg_911 = icmp_ln621_fu_464_p2.read();
        icmp_ln631_reg_935 = icmp_ln631_fu_518_p2.read();
        icmp_ln837_reg_874 = icmp_ln837_fu_301_p2.read();
        or_ln581_reg_901 = or_ln581_fu_419_p2.read();
        p_Result_13_reg_880 = p_Val2_18_fu_334_p3.read().range(7, 7);
        p_Val2_19_reg_885 = p_Val2_19_fu_383_p2.read();
        tmp_60_reg_930 = pos2_fu_455_p2.read().range(11, 11);
        xor_ln621_2_reg_916 = xor_ln621_2_fu_478_p2.read();
        zext_ln635_reg_941 = zext_ln635_fu_524_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_783 = i_fu_184_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln2527_reg_788 = icmp_ln2527_fu_190_p2.read();
        icmp_ln2527_reg_788_pp0_iter1_reg = icmp_ln2527_reg_788.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2527_reg_788_pp0_iter9_reg.read()))) {
        p_Val2_20_reg_963 = p_Val2_20_fu_611_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2527_reg_788_pp0_iter9_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, and_ln603_4_reg_906.read()))) {
        select_ln639_2_reg_974 = select_ln639_2_fu_696_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2527_reg_788_pp0_iter9_reg.read()) && esl_seteq<1,1,1>(and_ln603_4_reg_906.read(), ap_const_lv1_1))) {
        select_ln639_reg_969 = select_ln639_fu_681_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(icmp_ln2527_reg_788.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_reg_797 = p_src_data_stream_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2527_reg_788_pp0_iter6_reg.read()))) {
        x_assign_reg_807 = grp_fu_175_p1.read();
    }
}

void ConvertScaleAbs::thread_F2_4_fu_261_p3() {
    F2_4_fu_261_p3 = (!icmp_ln581_fu_249_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln581_fu_249_p2.read()[0].to_bool())? F2_fu_243_p2.read(): sub_ln581_fu_255_p2.read());
}

void ConvertScaleAbs::thread_F2_fu_243_p2() {
    F2_fu_243_p2 = (!ap_const_lv12_433.is_01() || !zext_ln461_fu_233_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_433) - sc_biguint<12>(zext_ln461_fu_233_p1.read()));
}

void ConvertScaleAbs::thread_Range1_all_ones_2_fu_504_p2() {
    Range1_all_ones_2_fu_504_p2 = (and_ln621_fu_498_p2.read() & icmp_ln621_fu_464_p2.read());
}

void ConvertScaleAbs::thread_Range1_all_ones_fu_651_p2() {
    Range1_all_ones_fu_651_p2 = (select_ln631_fu_639_p3.read() & Range1_all_ones_2_reg_923.read());
}

void ConvertScaleAbs::thread_Range1_all_zeros_2_fu_540_p2() {
    Range1_all_zeros_2_fu_540_p2 = (!p_Result_12_fu_313_p1.read().is_01() || !ap_const_lv54_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_12_fu_313_p1.read() == ap_const_lv54_0);
}

void ConvertScaleAbs::thread_Range1_all_zeros_fu_661_p2() {
    Range1_all_zeros_fu_661_p2 = (Range1_all_ones_2_reg_923.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_Range2_V_2_fu_528_p2() {
    Range2_V_2_fu_528_p2 = (!zext_ln635_fu_524_p1.read().is_01())? sc_lv<54>(): p_Result_12_fu_313_p1.read() >> (unsigned short)zext_ln635_fu_524_p1.read().to_uint();
}

void ConvertScaleAbs::thread_Range2_all_ones_fu_634_p2() {
    Range2_all_ones_fu_634_p2 = (!Range2_V_2_reg_946.read().is_01() || !r_V_fu_629_p2.read().is_01())? sc_lv<1>(): sc_lv<1>(Range2_V_2_reg_946.read() == r_V_fu_629_p2.read());
}

void ConvertScaleAbs::thread_add_ln591_fu_346_p2() {
    add_ln591_fu_346_p2 = (!ap_const_lv12_FFF.is_01() || !F2_reg_830.read().is_01())? sc_lv<12>(): (sc_bigint<12>(ap_const_lv12_FFF) + sc_biguint<12>(F2_reg_830.read()));
}

void ConvertScaleAbs::thread_and_ln403_2_fu_589_p2() {
    and_ln403_2_fu_589_p2 = (and_ln581_reg_891.read() & xor_ln403_fu_584_p2.read());
}

void ConvertScaleAbs::thread_and_ln403_fu_413_p2() {
    and_ln403_fu_413_p2 = (and_ln581_fu_408_p2.read() & p_Result_13_fu_371_p3.read());
}

void ConvertScaleAbs::thread_and_ln428_2_fu_731_p2() {
    and_ln428_2_fu_731_p2 = (icmp_ln833_reg_818_pp0_iter10_reg.read() & icmp_ln837_reg_874_pp0_iter10_reg.read());
}

void ConvertScaleAbs::thread_and_ln428_fu_704_p2() {
    and_ln428_fu_704_p2 = (icmp_ln833_reg_818_pp0_iter10_reg.read() & icmp_ln837_reg_874_pp0_iter10_reg.read());
}

void ConvertScaleAbs::thread_and_ln571_fu_741_p2() {
    and_ln571_fu_741_p2 = (icmp_ln571_reg_824_pp0_iter10_reg.read() & xor_ln428_fu_735_p2.read());
}

void ConvertScaleAbs::thread_and_ln581_fu_408_p2() {
    and_ln581_fu_408_p2 = (icmp_ln581_reg_838.read() & xor_ln582_fu_403_p2.read());
}

void ConvertScaleAbs::thread_and_ln603_3_fu_434_p2() {
    and_ln603_3_fu_434_p2 = (or_ln603_fu_428_p2.read() & xor_ln416_fu_397_p2.read());
}

void ConvertScaleAbs::thread_and_ln603_4_fu_440_p2() {
    and_ln603_4_fu_440_p2 = (and_ln603_3_fu_434_p2.read() & and_ln403_fu_413_p2.read());
}

void ConvertScaleAbs::thread_and_ln603_fu_606_p2() {
    and_ln603_fu_606_p2 = (icmp_ln603_reg_868_pp0_iter9_reg.read() & xor_ln581_fu_601_p2.read());
}

void ConvertScaleAbs::thread_and_ln621_fu_498_p2() {
    and_ln621_fu_498_p2 = (lD_fu_494_p1.read() & xor_ln621_2_fu_478_p2.read());
}

void ConvertScaleAbs::thread_and_ln631_fu_624_p2() {
    and_ln631_fu_624_p2 = (icmp_ln631_reg_935.read() & xor_ln631_fu_619_p2.read());
}

void ConvertScaleAbs::thread_and_ln639_fu_647_p2() {
    and_ln639_fu_647_p2 = (icmp_ln631_reg_935.read() & xor_ln621_2_reg_916.read());
}

void ConvertScaleAbs::thread_and_ln641_fu_666_p2() {
    and_ln641_fu_666_p2 = (icmp_ln641_fu_656_p2.read() & Range1_all_zeros_fu_661_p2.read());
}

void ConvertScaleAbs::thread_and_ln642_fu_558_p2() {
    and_ln642_fu_558_p2 = (icmp_ln642_fu_534_p2.read() & or_ln639_fu_552_p2.read());
}

void ConvertScaleAbs::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void ConvertScaleAbs::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void ConvertScaleAbs::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[3];
}

void ConvertScaleAbs::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void ConvertScaleAbs::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ConvertScaleAbs::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(icmp_ln2527_reg_788.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter11.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2527_reg_788_pp0_iter10_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_full_n.read())));
}

void ConvertScaleAbs::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(icmp_ln2527_reg_788.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter11.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2527_reg_788_pp0_iter10_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_full_n.read())));
}

void ConvertScaleAbs::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(icmp_ln2527_reg_788.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter11.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2527_reg_788_pp0_iter10_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_full_n.read())));
}

void ConvertScaleAbs::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void ConvertScaleAbs::thread_ap_block_state10_pp0_stage0_iter7() {
    ap_block_state10_pp0_stage0_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ConvertScaleAbs::thread_ap_block_state11_pp0_stage0_iter8() {
    ap_block_state11_pp0_stage0_iter8 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ConvertScaleAbs::thread_ap_block_state12_pp0_stage0_iter9() {
    ap_block_state12_pp0_stage0_iter9 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ConvertScaleAbs::thread_ap_block_state13_pp0_stage0_iter10() {
    ap_block_state13_pp0_stage0_iter10 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ConvertScaleAbs::thread_ap_block_state14_pp0_stage0_iter11() {
    ap_block_state14_pp0_stage0_iter11 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2527_reg_788_pp0_iter10_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_full_n.read()));
}

void ConvertScaleAbs::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ConvertScaleAbs::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = (esl_seteq<1,1,1>(icmp_ln2527_reg_788.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read()));
}

void ConvertScaleAbs::thread_ap_block_state5_pp0_stage0_iter2() {
    ap_block_state5_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ConvertScaleAbs::thread_ap_block_state6_pp0_stage0_iter3() {
    ap_block_state6_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ConvertScaleAbs::thread_ap_block_state7_pp0_stage0_iter4() {
    ap_block_state7_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ConvertScaleAbs::thread_ap_block_state8_pp0_stage0_iter5() {
    ap_block_state8_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ConvertScaleAbs::thread_ap_block_state9_pp0_stage0_iter6() {
    ap_block_state9_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ConvertScaleAbs::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(icmp_ln2527_fu_190_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void ConvertScaleAbs::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln2526_fu_178_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void ConvertScaleAbs::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void ConvertScaleAbs::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void ConvertScaleAbs::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter10.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter11.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void ConvertScaleAbs::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln2526_fu_178_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void ConvertScaleAbs::thread_ashr_ln586_fu_324_p2() {
    ashr_ln586_fu_324_p2 = (!p_Result_12_fu_313_p1.read().is_01() || !zext_ln586_fu_320_p1.read().is_01())? sc_lv<54>(): sc_bigint<54>(p_Result_12_fu_313_p1.read()) >> (unsigned short)zext_ln586_fu_320_p1.read().to_uint();
}

void ConvertScaleAbs::thread_ashr_ln623_fu_488_p2() {
    ashr_ln623_fu_488_p2 = (!p_Result_12_fu_313_p1.read().is_01() || !zext_ln623_fu_484_p1.read().is_01())? sc_lv<54>(): sc_bigint<54>(p_Result_12_fu_313_p1.read()) >> (unsigned short)zext_ln623_fu_484_p1.read().to_uint();
}

void ConvertScaleAbs::thread_deleted_zeros_fu_708_p3() {
    deleted_zeros_fu_708_p3 = (!and_ln603_4_reg_906_pp0_iter10_reg.read()[0].is_01())? sc_lv<1>(): ((and_ln603_4_reg_906_pp0_iter10_reg.read()[0].to_bool())? select_ln639_reg_969.read(): select_ln639_2_reg_974.read());
}

void ConvertScaleAbs::thread_grp_fu_175_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_175_ce = ap_const_logic_1;
    } else {
        grp_fu_175_ce = ap_const_logic_0;
    }
}

void ConvertScaleAbs::thread_grp_fu_175_p0() {
    grp_fu_175_p0 = esl_sext<32,16>(tmp_reg_797.read());
}

void ConvertScaleAbs::thread_i_fu_184_p2() {
    i_fu_184_p2 = (!i_0_reg_153.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(i_0_reg_153.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void ConvertScaleAbs::thread_icmp_ln2526_fu_178_p2() {
    icmp_ln2526_fu_178_p2 = (!i_0_reg_153.read().is_01() || !ap_const_lv10_2D0.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_153.read() == ap_const_lv10_2D0);
}

void ConvertScaleAbs::thread_icmp_ln2527_fu_190_p2() {
    icmp_ln2527_fu_190_p2 = (!j_0_reg_164.read().is_01() || !ap_const_lv11_500.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_164.read() == ap_const_lv11_500);
}

void ConvertScaleAbs::thread_icmp_ln571_fu_237_p2() {
    icmp_ln571_fu_237_p2 = (!trunc_ln368_fu_209_p1.read().is_01() || !ap_const_lv63_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln368_fu_209_p1.read() == ap_const_lv63_0);
}

void ConvertScaleAbs::thread_icmp_ln581_fu_249_p2() {
    icmp_ln581_fu_249_p2 = (!F2_fu_243_p2.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(F2_fu_243_p2.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void ConvertScaleAbs::thread_icmp_ln582_fu_269_p2() {
    icmp_ln582_fu_269_p2 = (!tmp_V_fu_213_p4.read().is_01() || !ap_const_lv11_433.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_fu_213_p4.read() == ap_const_lv11_433);
}

void ConvertScaleAbs::thread_icmp_ln585_fu_279_p2() {
    icmp_ln585_fu_279_p2 = (!F2_4_fu_261_p3.read().is_01() || !ap_const_lv12_36.is_01())? sc_lv<1>(): (sc_biguint<12>(F2_4_fu_261_p3.read()) < sc_biguint<12>(ap_const_lv12_36));
}

void ConvertScaleAbs::thread_icmp_ln591_fu_341_p2() {
    icmp_ln591_fu_341_p2 = (!F2_reg_830.read().is_01() || !ap_const_lv12_36.is_01())? sc_lv<1>(): (sc_bigint<12>(F2_reg_830.read()) > sc_bigint<12>(ap_const_lv12_36));
}

void ConvertScaleAbs::thread_icmp_ln603_fu_295_p2() {
    icmp_ln603_fu_295_p2 = (!tmp_56_fu_285_p4.read().is_01() || !ap_const_lv9_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_56_fu_285_p4.read() == ap_const_lv9_0);
}

void ConvertScaleAbs::thread_icmp_ln621_fu_464_p2() {
    icmp_ln621_fu_464_p2 = (!pos1_fu_446_p2.read().is_01() || !ap_const_lv12_36.is_01())? sc_lv<1>(): (sc_bigint<12>(pos1_fu_446_p2.read()) < sc_bigint<12>(ap_const_lv12_36));
}

void ConvertScaleAbs::thread_icmp_ln631_fu_518_p2() {
    icmp_ln631_fu_518_p2 = (!pos2_fu_455_p2.read().is_01() || !ap_const_lv12_36.is_01())? sc_lv<1>(): (sc_bigint<12>(pos2_fu_455_p2.read()) < sc_bigint<12>(ap_const_lv12_36));
}

void ConvertScaleAbs::thread_icmp_ln641_fu_656_p2() {
    icmp_ln641_fu_656_p2 = (!Range2_V_2_reg_946.read().is_01() || !ap_const_lv54_0.is_01())? sc_lv<1>(): sc_lv<1>(Range2_V_2_reg_946.read() == ap_const_lv54_0);
}

void ConvertScaleAbs::thread_icmp_ln642_fu_534_p2() {
    icmp_ln642_fu_534_p2 = (!pos2_fu_455_p2.read().is_01() || !ap_const_lv12_36.is_01())? sc_lv<1>(): sc_lv<1>(pos2_fu_455_p2.read() == ap_const_lv12_36);
}

void ConvertScaleAbs::thread_icmp_ln833_fu_227_p2() {
    icmp_ln833_fu_227_p2 = (!tmp_V_fu_213_p4.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_fu_213_p4.read() == ap_const_lv11_7FF);
}

void ConvertScaleAbs::thread_icmp_ln837_fu_301_p2() {
    icmp_ln837_fu_301_p2 = (!tmp_V_4_reg_812.read().is_01() || !ap_const_lv52_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_4_reg_812.read() != ap_const_lv52_0);
}

void ConvertScaleAbs::thread_j_fu_196_p2() {
    j_fu_196_p2 = (!j_0_reg_164.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(j_0_reg_164.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void ConvertScaleAbs::thread_lD_fu_494_p1() {
    lD_fu_494_p1 = ashr_ln623_fu_488_p2.read().range(1-1, 0);
}

void ConvertScaleAbs::thread_or_ln571_2_fu_759_p2() {
    or_ln571_2_fu_759_p2 = (and_ln428_fu_704_p2.read() | icmp_ln571_reg_824_pp0_iter10_reg.read());
}

void ConvertScaleAbs::thread_or_ln571_fu_746_p2() {
    or_ln571_fu_746_p2 = (and_ln571_fu_741_p2.read() | and_ln428_fu_704_p2.read());
}

void ConvertScaleAbs::thread_or_ln581_fu_419_p2() {
    or_ln581_fu_419_p2 = (icmp_ln582_reg_850.read() | icmp_ln581_reg_838.read());
}

void ConvertScaleAbs::thread_or_ln603_fu_428_p2() {
    or_ln603_fu_428_p2 = (or_ln581_fu_419_p2.read() | xor_ln603_fu_423_p2.read());
}

void ConvertScaleAbs::thread_or_ln639_fu_552_p2() {
    or_ln639_fu_552_p2 = (tmp_59_fu_470_p3.read() | xor_ln639_2_fu_546_p2.read());
}

void ConvertScaleAbs::thread_or_ln645_fu_672_p2() {
    or_ln645_fu_672_p2 = (Range1_all_zeros_2_reg_952.read() | xor_ln621_2_reg_916.read());
}

void ConvertScaleAbs::thread_or_ln658_fu_718_p2() {
    or_ln658_fu_718_p2 = (xor_ln621_fu_713_p2.read() | deleted_zeros_fu_708_p3.read());
}

void ConvertScaleAbs::thread_p_Result_12_fu_313_p1() {
    p_Result_12_fu_313_p1 = esl_zext<54,53>(tmp_1_i_fu_306_p3.read());
}

void ConvertScaleAbs::thread_p_Result_13_fu_371_p3() {
    p_Result_13_fu_371_p3 = p_Val2_18_fu_334_p3.read().range(7, 7);
}

void ConvertScaleAbs::thread_p_Result_s_fu_355_p3() {
    p_Result_s_fu_355_p3 = (!zext_ln591_fu_351_p1.read().is_01() || sc_biguint<32>(zext_ln591_fu_351_p1.read()).to_uint() >= 54)? sc_lv<1>(): p_Result_12_fu_313_p1.read().range(sc_biguint<32>(zext_ln591_fu_351_p1.read()).to_uint(), sc_biguint<32>(zext_ln591_fu_351_p1.read()).to_uint());
}

void ConvertScaleAbs::thread_p_Val2_18_fu_334_p3() {
    p_Val2_18_fu_334_p3 = (!icmp_ln585_reg_863.read()[0].is_01())? sc_lv<8>(): ((icmp_ln585_reg_863.read()[0].to_bool())? trunc_ln586_fu_330_p1.read(): ap_const_lv8_0);
}

void ConvertScaleAbs::thread_p_Val2_19_fu_383_p2() {
    p_Val2_19_fu_383_p2 = (!p_Val2_18_fu_334_p3.read().is_01() || !zext_ln415_fu_379_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_Val2_18_fu_334_p3.read()) + sc_biguint<8>(zext_ln415_fu_379_p1.read()));
}

void ConvertScaleAbs::thread_p_Val2_20_fu_611_p3() {
    p_Val2_20_fu_611_p3 = (!and_ln603_fu_606_p2.read()[0].is_01())? sc_lv<8>(): ((and_ln603_fu_606_p2.read()[0].to_bool())? shl_ln604_fu_567_p2.read(): select_ln403_2_fu_594_p3.read());
}

void ConvertScaleAbs::thread_p_Val2_s_fu_206_p1() {
    p_Val2_s_fu_206_p1 = x_assign_reg_807.read();
}

void ConvertScaleAbs::thread_p_dst_data_stream_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter11.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2527_reg_788_pp0_iter10_reg.read()))) {
        p_dst_data_stream_V_blk_n = p_dst_data_stream_V_full_n.read();
    } else {
        p_dst_data_stream_V_blk_n = ap_const_logic_1;
    }
}

void ConvertScaleAbs::thread_p_dst_data_stream_V_din() {
    p_dst_data_stream_V_din = (!xor_ln571_fu_764_p2.read()[0].is_01())? sc_lv<8>(): ((xor_ln571_fu_764_p2.read()[0].to_bool())? select_ln340_fu_724_p3.read(): select_ln571_fu_752_p3.read());
}

void ConvertScaleAbs::thread_p_dst_data_stream_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter11.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2527_reg_788_pp0_iter10_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        p_dst_data_stream_V_write = ap_const_logic_1;
    } else {
        p_dst_data_stream_V_write = ap_const_logic_0;
    }
}

void ConvertScaleAbs::thread_p_src_data_stream_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln2527_reg_788.read(), ap_const_lv1_0))) {
        p_src_data_stream_V_blk_n = p_src_data_stream_V_empty_n.read();
    } else {
        p_src_data_stream_V_blk_n = ap_const_logic_1;
    }
}

void ConvertScaleAbs::thread_p_src_data_stream_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln2527_reg_788.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        p_src_data_stream_V_read = ap_const_logic_1;
    } else {
        p_src_data_stream_V_read = ap_const_logic_0;
    }
}

void ConvertScaleAbs::thread_pos1_fu_446_p2() {
    pos1_fu_446_p2 = (!ap_const_lv12_8.is_01() || !F2_reg_830.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_8) + sc_biguint<12>(F2_reg_830.read()));
}

void ConvertScaleAbs::thread_pos2_fu_455_p2() {
    pos2_fu_455_p2 = (!ap_const_lv12_9.is_01() || !F2_reg_830.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_9) + sc_biguint<12>(F2_reg_830.read()));
}

void ConvertScaleAbs::thread_qb_fu_363_p3() {
    qb_fu_363_p3 = (!icmp_ln591_fu_341_p2.read()[0].is_01())? sc_lv<1>(): ((icmp_ln591_fu_341_p2.read()[0].to_bool())? ap_const_lv1_0: p_Result_s_fu_355_p3.read());
}

void ConvertScaleAbs::thread_r_V_fu_629_p2() {
    r_V_fu_629_p2 = (!zext_ln635_reg_941.read().is_01())? sc_lv<54>(): ap_const_lv54_3FFFFFFFFFFFFF >> (unsigned short)zext_ln635_reg_941.read().to_uint();
}

void ConvertScaleAbs::thread_select_ln340_fu_724_p3() {
    select_ln340_fu_724_p3 = (!or_ln658_fu_718_p2.read()[0].is_01())? sc_lv<8>(): ((or_ln658_fu_718_p2.read()[0].to_bool())? p_Val2_20_reg_963.read(): ap_const_lv8_FF);
}

void ConvertScaleAbs::thread_select_ln403_2_fu_594_p3() {
    select_ln403_2_fu_594_p3 = (!and_ln403_2_fu_589_p2.read()[0].is_01())? sc_lv<8>(): ((and_ln403_2_fu_589_p2.read()[0].to_bool())? p_Val2_19_reg_885.read(): select_ln403_fu_578_p3.read());
}

void ConvertScaleAbs::thread_select_ln403_fu_578_p3() {
    select_ln403_fu_578_p3 = (!and_ln403_reg_896.read()[0].is_01())? sc_lv<8>(): ((and_ln403_reg_896.read()[0].to_bool())? p_Val2_19_reg_885.read(): select_ln582_fu_572_p3.read());
}

void ConvertScaleAbs::thread_select_ln571_fu_752_p3() {
    select_ln571_fu_752_p3 = (!or_ln571_fu_746_p2.read()[0].is_01())? sc_lv<8>(): ((or_ln571_fu_746_p2.read()[0].to_bool())? ap_const_lv8_0: p_Val2_20_reg_963.read());
}

void ConvertScaleAbs::thread_select_ln582_fu_572_p3() {
    select_ln582_fu_572_p3 = (!icmp_ln582_reg_850_pp0_iter9_reg.read()[0].is_01())? sc_lv<8>(): ((icmp_ln582_reg_850_pp0_iter9_reg.read()[0].to_bool())? trunc_ln583_reg_857_pp0_iter9_reg.read(): ap_const_lv8_0);
}

void ConvertScaleAbs::thread_select_ln631_fu_639_p3() {
    select_ln631_fu_639_p3 = (!and_ln631_fu_624_p2.read()[0].is_01())? sc_lv<1>(): ((and_ln631_fu_624_p2.read()[0].to_bool())? Range2_all_ones_fu_634_p2.read(): xor_ln631_fu_619_p2.read());
}

void ConvertScaleAbs::thread_select_ln639_2_fu_696_p3() {
    select_ln639_2_fu_696_p3 = (!and_ln639_fu_647_p2.read()[0].is_01())? sc_lv<1>(): ((and_ln639_fu_647_p2.read()[0].to_bool())? and_ln641_fu_666_p2.read(): select_ln642_2_fu_689_p3.read());
}

void ConvertScaleAbs::thread_select_ln639_fu_681_p3() {
    select_ln639_fu_681_p3 = (!and_ln639_fu_647_p2.read()[0].is_01())? sc_lv<1>(): ((and_ln639_fu_647_p2.read()[0].to_bool())? Range1_all_ones_fu_651_p2.read(): select_ln642_fu_676_p3.read());
}

void ConvertScaleAbs::thread_select_ln642_2_fu_689_p3() {
    select_ln642_2_fu_689_p3 = (!and_ln642_reg_957.read()[0].is_01())? sc_lv<1>(): ((and_ln642_reg_957.read()[0].to_bool())? Range1_all_zeros_fu_661_p2.read(): or_ln645_fu_672_p2.read());
}

void ConvertScaleAbs::thread_select_ln642_fu_676_p3() {
    select_ln642_fu_676_p3 = (!and_ln642_reg_957.read()[0].is_01())? sc_lv<1>(): ((and_ln642_reg_957.read()[0].to_bool())? Range1_all_ones_2_reg_923.read(): xor_ln621_2_reg_916.read());
}

void ConvertScaleAbs::thread_sext_ln581_fu_317_p1() {
    sext_ln581_fu_317_p1 = esl_sext<32,12>(F2_4_reg_844.read());
}

void ConvertScaleAbs::thread_sext_ln618_fu_451_p1() {
    sext_ln618_fu_451_p1 = esl_sext<32,12>(pos1_fu_446_p2.read());
}

void ConvertScaleAbs::thread_sext_ln619_fu_460_p1() {
    sext_ln619_fu_460_p1 = esl_sext<32,12>(pos2_fu_455_p2.read());
}

void ConvertScaleAbs::thread_shl_ln604_fu_567_p2() {
    shl_ln604_fu_567_p2 = (!trunc_ln581_fu_564_p1.read().is_01())? sc_lv<8>(): trunc_ln583_reg_857_pp0_iter9_reg.read() << (unsigned short)trunc_ln581_fu_564_p1.read().to_uint();
}

void ConvertScaleAbs::thread_sub_ln581_fu_255_p2() {
    sub_ln581_fu_255_p2 = (!ap_const_lv12_0.is_01() || !F2_fu_243_p2.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_0) - sc_biguint<12>(F2_fu_243_p2.read()));
}

void ConvertScaleAbs::thread_tmp_1_i_fu_306_p3() {
    tmp_1_i_fu_306_p3 = esl_concat<1,52>(ap_const_lv1_1, tmp_V_4_reg_812.read());
}

void ConvertScaleAbs::thread_tmp_56_fu_285_p4() {
    tmp_56_fu_285_p4 = F2_4_fu_261_p3.read().range(11, 3);
}

void ConvertScaleAbs::thread_tmp_58_fu_389_p3() {
    tmp_58_fu_389_p3 = p_Val2_19_fu_383_p2.read().range(7, 7);
}

void ConvertScaleAbs::thread_tmp_59_fu_470_p3() {
    tmp_59_fu_470_p3 = pos1_fu_446_p2.read().range(11, 11);
}

void ConvertScaleAbs::thread_tmp_V_4_fu_223_p1() {
    tmp_V_4_fu_223_p1 = p_Val2_s_fu_206_p1.read().range(52-1, 0);
}

void ConvertScaleAbs::thread_tmp_V_fu_213_p4() {
    tmp_V_fu_213_p4 = p_Val2_s_fu_206_p1.read().range(62, 52);
}

void ConvertScaleAbs::thread_trunc_ln368_fu_209_p1() {
    trunc_ln368_fu_209_p1 = p_Val2_s_fu_206_p1.read().range(63-1, 0);
}

void ConvertScaleAbs::thread_trunc_ln581_fu_564_p1() {
    trunc_ln581_fu_564_p1 = F2_4_reg_844_pp0_iter9_reg.read().range(8-1, 0);
}

void ConvertScaleAbs::thread_trunc_ln583_fu_275_p1() {
    trunc_ln583_fu_275_p1 = p_Val2_s_fu_206_p1.read().range(8-1, 0);
}

void ConvertScaleAbs::thread_trunc_ln586_fu_330_p1() {
    trunc_ln586_fu_330_p1 = ashr_ln586_fu_324_p2.read().range(8-1, 0);
}

void ConvertScaleAbs::thread_xor_ln403_fu_584_p2() {
    xor_ln403_fu_584_p2 = (p_Result_13_reg_880.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_xor_ln416_fu_397_p2() {
    xor_ln416_fu_397_p2 = (tmp_58_fu_389_p3.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_xor_ln428_fu_735_p2() {
    xor_ln428_fu_735_p2 = (and_ln428_2_fu_731_p2.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_xor_ln571_fu_764_p2() {
    xor_ln571_fu_764_p2 = (or_ln571_2_fu_759_p2.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_xor_ln581_fu_601_p2() {
    xor_ln581_fu_601_p2 = (or_ln581_reg_901.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_xor_ln582_fu_403_p2() {
    xor_ln582_fu_403_p2 = (icmp_ln582_reg_850.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_xor_ln603_fu_423_p2() {
    xor_ln603_fu_423_p2 = (icmp_ln603_reg_868.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_xor_ln621_2_fu_478_p2() {
    xor_ln621_2_fu_478_p2 = (tmp_59_fu_470_p3.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_xor_ln621_fu_713_p2() {
    xor_ln621_fu_713_p2 = (icmp_ln621_reg_911_pp0_iter10_reg.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_xor_ln631_fu_619_p2() {
    xor_ln631_fu_619_p2 = (tmp_60_reg_930.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_xor_ln639_2_fu_546_p2() {
    xor_ln639_2_fu_546_p2 = (icmp_ln631_fu_518_p2.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_zext_ln415_fu_379_p1() {
    zext_ln415_fu_379_p1 = esl_zext<8,1>(qb_fu_363_p3.read());
}

void ConvertScaleAbs::thread_zext_ln461_fu_233_p1() {
    zext_ln461_fu_233_p1 = esl_zext<12,11>(tmp_V_fu_213_p4.read());
}

void ConvertScaleAbs::thread_zext_ln586_fu_320_p1() {
    zext_ln586_fu_320_p1 = esl_zext<54,32>(sext_ln581_fu_317_p1.read());
}

void ConvertScaleAbs::thread_zext_ln591_fu_351_p1() {
    zext_ln591_fu_351_p1 = esl_zext<32,12>(add_ln591_fu_346_p2.read());
}

void ConvertScaleAbs::thread_zext_ln623_fu_484_p1() {
    zext_ln623_fu_484_p1 = esl_zext<54,32>(sext_ln618_fu_451_p1.read());
}

void ConvertScaleAbs::thread_zext_ln635_fu_524_p1() {
    zext_ln635_fu_524_p1 = esl_zext<54,32>(sext_ln619_fu_460_p1.read());
}

void ConvertScaleAbs::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln2526_fu_178_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter11.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter10.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln2527_fu_190_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter11.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter10.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln2527_fu_190_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state15;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

