# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/base_filter.xdc

# Block Designs: bd/base_filter/base_filter.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter || ORIG_REF_NAME==base_filter} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_audio_codec_ctrl_0_0/base_filter_audio_codec_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_audio_codec_ctrl_0_0 || ORIG_REF_NAME==base_filter_audio_codec_ctrl_0_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_axi_dma_0/base_filter_axi_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_axi_dma_0 || ORIG_REF_NAME==base_filter_axi_dma_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_axi_smc_0/base_filter_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_axi_smc_0 || ORIG_REF_NAME==base_filter_axi_smc_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_axi_smc_1_0/base_filter_axi_smc_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_axi_smc_1_0 || ORIG_REF_NAME==base_filter_axi_smc_1_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_btns_gpio_0/base_filter_btns_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_btns_gpio_0 || ORIG_REF_NAME==base_filter_btns_gpio_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_clk_wiz_10MHz_0/base_filter_clk_wiz_10MHz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_clk_wiz_10MHz_0 || ORIG_REF_NAME==base_filter_clk_wiz_10MHz_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_concat_interrupts_0/base_filter_concat_interrupts_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_concat_interrupts_0 || ORIG_REF_NAME==base_filter_concat_interrupts_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_fir_compiler_0_0/base_filter_fir_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_fir_compiler_0_0 || ORIG_REF_NAME==base_filter_fir_compiler_0_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_inputfifo_0/base_filter_inputfifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_inputfifo_0 || ORIG_REF_NAME==base_filter_inputfifo_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_leds_gpio_0/base_filter_leds_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_leds_gpio_0 || ORIG_REF_NAME==base_filter_leds_gpio_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_outputfifo_0/base_filter_outputfifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_outputfifo_0 || ORIG_REF_NAME==base_filter_outputfifo_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_ps7_0_0/base_filter_ps7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_ps7_0_0 || ORIG_REF_NAME==base_filter_ps7_0_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_xbar_0/base_filter_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_xbar_0 || ORIG_REF_NAME==base_filter_xbar_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_ps7_0_axi_periph_0/base_filter_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_ps7_0_axi_periph_0 || ORIG_REF_NAME==base_filter_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_rgbleds_gpio_0/base_filter_rgbleds_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_rgbleds_gpio_0 || ORIG_REF_NAME==base_filter_rgbleds_gpio_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_rst_ps7_0_fclk0_0/base_filter_rst_ps7_0_fclk0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_rst_ps7_0_fclk0_0 || ORIG_REF_NAME==base_filter_rst_ps7_0_fclk0_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_switches_gpio_0/base_filter_switches_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_switches_gpio_0 || ORIG_REF_NAME==base_filter_switches_gpio_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_system_interrupts_0/base_filter_system_interrupts_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_system_interrupts_0 || ORIG_REF_NAME==base_filter_system_interrupts_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_s00_regslice_0/base_filter_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_s00_regslice_0 || ORIG_REF_NAME==base_filter_s00_regslice_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_auto_pc_0/base_filter_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_auto_pc_0 || ORIG_REF_NAME==base_filter_auto_pc_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_m00_regslice_0/base_filter_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_m00_regslice_0 || ORIG_REF_NAME==base_filter_m00_regslice_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_m01_regslice_0/base_filter_m01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_m01_regslice_0 || ORIG_REF_NAME==base_filter_m01_regslice_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_m02_regslice_0/base_filter_m02_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_m02_regslice_0 || ORIG_REF_NAME==base_filter_m02_regslice_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_m03_regslice_0/base_filter_m03_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_m03_regslice_0 || ORIG_REF_NAME==base_filter_m03_regslice_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_m04_regslice_0/base_filter_m04_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_m04_regslice_0 || ORIG_REF_NAME==base_filter_m04_regslice_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_m05_regslice_0/base_filter_m05_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_m05_regslice_0 || ORIG_REF_NAME==base_filter_m05_regslice_0} -quiet] -quiet

# IP: bd/base_filter/ip/base_filter_m06_regslice_0/base_filter_m06_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_filter_m06_regslice_0 || ORIG_REF_NAME==base_filter_m06_regslice_0} -quiet] -quiet

# XDC: bd/base_filter/base_filter_ooc.xdc
