# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/pgprogram/tcd_pgprogram/5m01IntegratedSystemDesign/lab04_VVD/lab04_VVD.srcs/sources_1/bd/base/ip/base_sobel_accel_1_0/base_sobel_accel_1_0.xci
# IP: The module: 'base_sobel_accel_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/pgprogram/tcd_pgprogram/5m01IntegratedSystemDesign/lab04_VVD/lab04_VVD.srcs/sources_1/bd/base/ip/base_sobel_accel_1_0/constraints/sobel_accel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_sobel_accel_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/pgprogram/tcd_pgprogram/5m01IntegratedSystemDesign/lab04_VVD/lab04_VVD.srcs/sources_1/bd/base/ip/base_sobel_accel_1_0/base_sobel_accel_1_0.xci
# IP: The module: 'base_sobel_accel_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/pgprogram/tcd_pgprogram/5m01IntegratedSystemDesign/lab04_VVD/lab04_VVD.srcs/sources_1/bd/base/ip/base_sobel_accel_1_0/constraints/sobel_accel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_sobel_accel_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
