# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/pgprogram/tcd_pgprogram/5m01IntegratedSystemDesign/lab04_VVD/lab04_VVD.srcs/sources_1/bd/base/ip/base_processing_system7_1_1/base_processing_system7_1_1.xci
# IP: The module: 'base_processing_system7_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/pgprogram/tcd_pgprogram/5m01IntegratedSystemDesign/lab04_VVD/lab04_VVD.srcs/sources_1/bd/base/ip/base_processing_system7_1_1/base_processing_system7_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_processing_system7_1_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/pgprogram/tcd_pgprogram/5m01IntegratedSystemDesign/lab04_VVD/lab04_VVD.srcs/sources_1/bd/base/ip/base_processing_system7_1_1/base_processing_system7_1_1.xci
# IP: The module: 'base_processing_system7_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/pgprogram/tcd_pgprogram/5m01IntegratedSystemDesign/lab04_VVD/lab04_VVD.srcs/sources_1/bd/base/ip/base_processing_system7_1_1/base_processing_system7_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_processing_system7_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
