# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/base_filter_axi_smc_1_0.xci
# IP: The module: 'base_filter_axi_smc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/bd_1c50.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_0/bd_1c50_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_1/bd_1c50_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_2/bd_1c50_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_3/bd_1c50_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_4/bd_1c50_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_5/bd_1c50_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_6/bd_1c50_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_7/bd_1c50_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_8/bd_1c50_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_9/bd_1c50_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_10/bd_1c50_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_1/bd_1c50_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_1/bd_1c50_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_5/bd_1c50_s00a2s_0_ooc.xdc

# XDC: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_6/bd_1c50_sawn_0_ooc.xdc

# XDC: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_7/bd_1c50_swn_0_ooc.xdc

# XDC: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_8/bd_1c50_sbn_0_ooc.xdc

# XDC: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_9/bd_1c50_m00s2a_0_ooc.xdc

# XDC: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_filter_axi_smc_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/base_filter_axi_smc_1_0.xci
# IP: The module: 'base_filter_axi_smc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/bd_1c50.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_0/bd_1c50_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_1/bd_1c50_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_2/bd_1c50_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_3/bd_1c50_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_4/bd_1c50_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_5/bd_1c50_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_6/bd_1c50_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_7/bd_1c50_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_8/bd_1c50_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_9/bd_1c50_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_10/bd_1c50_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_1/bd_1c50_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_1/bd_1c50_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_5/bd_1c50_s00a2s_0_ooc.xdc

# XDC: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_6/bd_1c50_sawn_0_ooc.xdc

# XDC: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_7/bd_1c50_swn_0_ooc.xdc

# XDC: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_8/bd_1c50_sbn_0_ooc.xdc

# XDC: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/bd_0/ip/ip_9/bd_1c50_m00s2a_0_ooc.xdc

# XDC: c:/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/base_filter/base_filter.srcs/sources_1/bd/base_filter/ip/base_filter_axi_smc_1_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_filter_axi_smc_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
