-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Filter2D is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_src_data_stream_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_src_data_stream_V_empty_n : IN STD_LOGIC;
    p_src_data_stream_V_read : OUT STD_LOGIC;
    p_dst_data_stream_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_dst_data_stream_V_full_n : IN STD_LOGIC;
    p_dst_data_stream_V_write : OUT STD_LOGIC;
    p_kernel_val_0_V_1_read : IN STD_LOGIC_VECTOR (1 downto 0);
    p_kernel_val_0_V_2_read : IN STD_LOGIC_VECTOR (1 downto 0);
    p_kernel_val_1_V_0_read : IN STD_LOGIC_VECTOR (2 downto 0);
    p_kernel_val_1_V_2_read : IN STD_LOGIC_VECTOR (3 downto 0);
    p_kernel_val_2_V_0_read : IN STD_LOGIC_VECTOR (1 downto 0);
    p_kernel_val_2_V_1_read : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of Filter2D is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv10_2D2 : STD_LOGIC_VECTOR (9 downto 0) := "1011010010";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv10_2D0 : STD_LOGIC_VECTOR (9 downto 0) := "1011010000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv11_2D0 : STD_LOGIC_VECTOR (10 downto 0) := "01011010000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv11_7FE : STD_LOGIC_VECTOR (10 downto 0) := "11111111110";
    constant ap_const_lv11_7FD : STD_LOGIC_VECTOR (10 downto 0) := "11111111101";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv11_502 : STD_LOGIC_VECTOR (10 downto 0) := "10100000010";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv12_500 : STD_LOGIC_VECTOR (11 downto 0) := "010100000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv12_9FE : STD_LOGIC_VECTOR (11 downto 0) := "100111111110";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_src_data_stream_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln444_reg_1419 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln118_reg_1428 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln899_reg_1384 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln887_reg_1375 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_dst_data_stream_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal and_ln512_reg_1449 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln512_reg_1449_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal t_V_2_reg_329 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1118_fu_340_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1118_reg_1336 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1118_1_fu_344_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1118_1_reg_1341 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1118_2_fu_348_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1118_2_reg_1346 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln1118_4_fu_352_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln1118_4_reg_1351 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln1118_3_fu_356_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1118_3_reg_1356 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln1118_5_fu_360_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln1118_5_reg_1361 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln443_fu_368_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal i_V_fu_374_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal i_V_reg_1370 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln887_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln457_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln457_reg_1379 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln899_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_fu_408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_1389 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_1_fu_414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_1_reg_1393 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln899_1_fu_420_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln899_1_reg_1397 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln493_1_fu_574_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal xor_ln493_1_reg_1404 : STD_LOGIC_VECTOR (1 downto 0);
    signal xor_ln493_2_fu_612_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal xor_ln493_2_reg_1409 : STD_LOGIC_VECTOR (1 downto 0);
    signal xor_ln493_3_fu_650_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal xor_ln493_3_reg_1414 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln444_fu_660_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal ap_predicate_op141_read_state4 : BOOLEAN;
    signal ap_predicate_op148_read_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln444_reg_1419_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln444_reg_1419_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal j_V_fu_666_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal and_ln118_fu_714_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln118_reg_1428_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_fu_788_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal x_reg_1432 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln458_fu_796_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln458_reg_1437 : STD_LOGIC_VECTOR (1 downto 0);
    signal or_ln457_fu_800_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln457_reg_1442 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln457_reg_1442_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln512_fu_805_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln512_reg_1449_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln512_reg_1449_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln512_reg_1449_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal right_border_buf_0_19_reg_1453 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln493_fu_823_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal xor_ln493_reg_1464 : STD_LOGIC_VECTOR (1 downto 0);
    signal k_buf_0_val_4_addr_reg_1471 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_5_addr_reg_1477 : STD_LOGIC_VECTOR (10 downto 0);
    signal src_kernel_win_0_va_23_fu_942_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_23_reg_1483 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_23_reg_1483_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_24_fu_960_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_24_reg_1490 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_24_reg_1490_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_25_fu_978_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_25_reg_1496 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1231_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln703_reg_1502 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal grp_fu_1245_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln703_2_reg_1507 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal mul_ln1118_4_fu_1032_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln1118_4_reg_1512 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln1118_5_fu_1041_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln1118_5_reg_1518 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Result_s_reg_1524 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_5_fu_1139_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_5_reg_1530 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_1_reg_1535 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_41_reg_1541 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter1_state4 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal k_buf_0_val_3_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_3_ce0 : STD_LOGIC;
    signal k_buf_0_val_3_we0 : STD_LOGIC;
    signal k_buf_0_val_3_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_3_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_3_ce1 : STD_LOGIC;
    signal k_buf_0_val_3_we1 : STD_LOGIC;
    signal k_buf_0_val_4_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_4_ce0 : STD_LOGIC;
    signal k_buf_0_val_4_we0 : STD_LOGIC;
    signal k_buf_0_val_4_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_4_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_4_ce1 : STD_LOGIC;
    signal k_buf_0_val_4_we1 : STD_LOGIC;
    signal k_buf_0_val_5_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_5_ce0 : STD_LOGIC;
    signal k_buf_0_val_5_we0 : STD_LOGIC;
    signal k_buf_0_val_5_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_5_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_5_ce1 : STD_LOGIC;
    signal k_buf_0_val_5_we1 : STD_LOGIC;
    signal t_V_reg_318 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal zext_ln835_fu_816_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal src_kernel_win_0_va_fu_154 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_18_fu_158 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_19_fu_162 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_20_fu_166 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_21_fu_170 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_src_kernel_win_0_va_29 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_22_fu_174 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_src_kernel_win_0_va_30 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_s_fu_178 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_0_0_fu_854_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_14_fu_182 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_15_fu_186 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_16_fu_190 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_1_0_fu_872_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_17_fu_194 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_18_fu_198 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_2_0_fu_889_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_right_border_buf_0_19 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_fu_392_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln443_fu_364_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln506_fu_426_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln506_fu_430_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_28_fu_442_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln118_fu_456_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln118_6_fu_450_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_fu_468_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln142_fu_476_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln139_1_fu_482_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln507_fu_490_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln506_1_fu_506_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln506_2_fu_532_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln144_1_fu_494_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln507_fu_500_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln118_1_fu_462_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln507_fu_436_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln507_fu_558_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln507_1_fu_566_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln142_fu_528_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_31_fu_520_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln118_fu_586_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln118_fu_592_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_30_fu_512_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln139_4_fu_596_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal xor_ln118_1_fu_580_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln118_fu_604_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln142_2_fu_554_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_33_fu_546_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln118_7_fu_624_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln118_2_fu_630_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_32_fu_538_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln139_5_fu_634_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln118_fu_618_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln118_1_fu_642_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_34_fu_672_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln444_fu_656_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ImagLoc_x_fu_688_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_35_fu_694_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln118_1_fu_708_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln118_8_fu_702_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_36_fu_720_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln142_2_fu_728_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln139_fu_734_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln147_fu_752_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln118_3_fu_758_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal xor_ln118_9_fu_770_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln144_fu_746_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln118_fu_776_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln144_fu_782_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln139_fu_742_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln118_fu_766_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln891_fu_682_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln144_fu_813_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_843_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_861_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_fu_879_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_931_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_8_fu_949_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_9_fu_967_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1118_fu_991_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln1118_fu_995_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_1238_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln1118_4_fu_1032_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1118_4_fu_1032_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal mul_ln1118_5_fu_1041_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1118_5_fu_1041_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal sext_ln703_3_fu_1085_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln703_5_fu_1091_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln703_4_fu_1096_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_1252_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln703_6_fu_1100_p2 : STD_LOGIC_VECTOR (11 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln703_6_fu_1100_p2 : signal is "no";
    signal zext_ln703_2_fu_1108_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_s_fu_1111_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln703_fu_1088_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln703_1_fu_1105_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln703_9_fu_1130_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln703_5_fu_1135_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln703_8_fu_1125_p2 : STD_LOGIC_VECTOR (11 downto 0);
    attribute use_dsp48 of add_ln703_8_fu_1125_p2 : signal is "no";
    signal or_ln785_fu_1164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_fu_1168_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_fu_1179_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_fu_1183_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_fu_1189_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_fu_1173_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_fu_1194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln703_6_fu_1161_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln340_1_fu_1200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_fu_1206_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_fu_1214_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1231_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1231_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_1238_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1238_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_1245_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1245_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_1252_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1252_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0 : BOOLEAN;
    signal ap_predicate_op142_store_state4 : BOOLEAN;
    signal ap_enable_operation_142 : BOOLEAN;
    signal ap_enable_state4_pp0_iter1_stage0 : BOOLEAN;
    signal ap_predicate_op140_load_state4 : BOOLEAN;
    signal ap_enable_operation_140 : BOOLEAN;
    signal ap_enable_operation_165 : BOOLEAN;
    signal ap_enable_state5_pp0_iter2_stage0 : BOOLEAN;
    signal ap_predicate_op170_store_state5 : BOOLEAN;
    signal ap_enable_operation_170 : BOOLEAN;
    signal ap_predicate_op144_store_state4 : BOOLEAN;
    signal ap_enable_operation_144 : BOOLEAN;
    signal ap_enable_operation_138 : BOOLEAN;
    signal ap_enable_operation_162 : BOOLEAN;
    signal ap_predicate_op171_store_state5 : BOOLEAN;
    signal ap_enable_operation_171 : BOOLEAN;
    signal ap_predicate_op146_store_state4 : BOOLEAN;
    signal ap_enable_operation_146 : BOOLEAN;
    signal ap_enable_operation_135 : BOOLEAN;
    signal ap_enable_operation_159 : BOOLEAN;
    signal ap_predicate_op149_store_state4 : BOOLEAN;
    signal ap_enable_operation_149 : BOOLEAN;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal grp_fu_1231_p00 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_1238_p00 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_1245_p00 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_1252_p00 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1118_4_fu_1032_p00 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln1118_5_fu_1041_p00 : STD_LOGIC_VECTOR (10 downto 0);

    component sobel_accel_mux_3hbi IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component sobel_accel_mac_mpcA IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (1 downto 0);
        din2 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component sobel_accel_mac_mqcK IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (1 downto 0);
        din2 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component sobel_accel_mac_mrcU IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        din2 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component sobel_accel_mac_msc4 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        din2 : IN STD_LOGIC_VECTOR (11 downto 0);
        dout : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component Filter2D_1_k_buf_eOg IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    k_buf_0_val_3_U : component Filter2D_1_k_buf_eOg
    generic map (
        DataWidth => 8,
        AddressRange => 1280,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_3_address0,
        ce0 => k_buf_0_val_3_ce0,
        we0 => k_buf_0_val_3_we0,
        d0 => p_src_data_stream_V_dout,
        q0 => k_buf_0_val_3_q0,
        address1 => k_buf_0_val_3_address1,
        ce1 => k_buf_0_val_3_ce1,
        we1 => k_buf_0_val_3_we1,
        d1 => p_src_data_stream_V_dout);

    k_buf_0_val_4_U : component Filter2D_1_k_buf_eOg
    generic map (
        DataWidth => 8,
        AddressRange => 1280,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_4_address0,
        ce0 => k_buf_0_val_4_ce0,
        we0 => k_buf_0_val_4_we0,
        d0 => p_src_data_stream_V_dout,
        q0 => k_buf_0_val_4_q0,
        address1 => k_buf_0_val_4_address1,
        ce1 => k_buf_0_val_4_ce1,
        we1 => k_buf_0_val_4_we1,
        d1 => k_buf_0_val_3_q0);

    k_buf_0_val_5_U : component Filter2D_1_k_buf_eOg
    generic map (
        DataWidth => 8,
        AddressRange => 1280,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_5_address0,
        ce0 => k_buf_0_val_5_ce0,
        we0 => k_buf_0_val_5_we0,
        d0 => p_src_data_stream_V_dout,
        q0 => k_buf_0_val_5_q0,
        address1 => k_buf_0_val_5_address1,
        ce1 => k_buf_0_val_5_ce1,
        we1 => k_buf_0_val_5_we1,
        d1 => k_buf_0_val_4_q0);

    sobel_accel_mux_3hbi_U55 : component sobel_accel_mux_3hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => right_border_buf_0_s_fu_178,
        din1 => right_border_buf_0_14_fu_182,
        din2 => ap_const_lv8_0,
        din3 => xor_ln493_reg_1464,
        dout => tmp_4_fu_843_p5);

    sobel_accel_mux_3hbi_U56 : component sobel_accel_mux_3hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => right_border_buf_0_16_fu_190,
        din1 => right_border_buf_0_17_fu_194,
        din2 => ap_const_lv8_0,
        din3 => xor_ln493_reg_1464,
        dout => tmp_5_fu_861_p5);

    sobel_accel_mux_3hbi_U57 : component sobel_accel_mux_3hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => right_border_buf_0_19_reg_1453,
        din1 => right_border_buf_0_15_fu_186,
        din2 => ap_const_lv8_0,
        din3 => xor_ln493_reg_1464,
        dout => tmp_6_fu_879_p5);

    sobel_accel_mux_3hbi_U58 : component sobel_accel_mux_3hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => col_buf_0_val_0_0_fu_854_p3,
        din1 => col_buf_0_val_1_0_fu_872_p3,
        din2 => col_buf_0_val_2_0_fu_889_p3,
        din3 => xor_ln493_1_reg_1404,
        dout => tmp_7_fu_931_p5);

    sobel_accel_mux_3hbi_U59 : component sobel_accel_mux_3hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => col_buf_0_val_0_0_fu_854_p3,
        din1 => col_buf_0_val_1_0_fu_872_p3,
        din2 => col_buf_0_val_2_0_fu_889_p3,
        din3 => xor_ln493_2_reg_1409,
        dout => tmp_8_fu_949_p5);

    sobel_accel_mux_3hbi_U60 : component sobel_accel_mux_3hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => col_buf_0_val_0_0_fu_854_p3,
        din1 => col_buf_0_val_1_0_fu_872_p3,
        din2 => col_buf_0_val_2_0_fu_889_p3,
        din3 => xor_ln493_3_reg_1414,
        dout => tmp_9_fu_967_p5);

    sobel_accel_mac_mpcA_U61 : component sobel_accel_mac_mpcA
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 2,
        din2_WIDTH => 9,
        dout_WIDTH => 11)
    port map (
        din0 => grp_fu_1231_p0,
        din1 => grp_fu_1231_p1,
        din2 => sub_ln1118_fu_995_p2,
        dout => grp_fu_1231_p3);

    sobel_accel_mac_mqcK_U62 : component sobel_accel_mac_mqcK
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 2,
        din2_WIDTH => 11,
        dout_WIDTH => 11)
    port map (
        din0 => grp_fu_1238_p0,
        din1 => grp_fu_1238_p1,
        din2 => add_ln703_reg_1502,
        dout => grp_fu_1238_p3);

    sobel_accel_mac_mrcU_U63 : component sobel_accel_mac_mrcU
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 3,
        din2_WIDTH => 11,
        dout_WIDTH => 12)
    port map (
        din0 => grp_fu_1245_p0,
        din1 => grp_fu_1245_p1,
        din2 => grp_fu_1238_p3,
        dout => grp_fu_1245_p3);

    sobel_accel_mac_msc4_U64 : component sobel_accel_mac_msc4
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 4,
        din2_WIDTH => 12,
        dout_WIDTH => 12)
    port map (
        din0 => grp_fu_1252_p0,
        din1 => grp_fu_1252_p1,
        din2 => add_ln703_2_reg_1507,
        dout => grp_fu_1252_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((icmp_ln444_fu_660_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((icmp_ln443_fu_368_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter1_state4)) then 
                        ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                elsif (((icmp_ln443_fu_368_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    t_V_2_reg_329_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln444_fu_660_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                t_V_2_reg_329 <= j_V_fu_666_p2;
            elsif (((icmp_ln443_fu_368_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                t_V_2_reg_329 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;

    t_V_reg_318_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                t_V_reg_318 <= i_V_reg_1370;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                t_V_reg_318 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln512_reg_1449_pp0_iter2_reg) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln703_2_reg_1507 <= grp_fu_1245_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln512_reg_1449_pp0_iter1_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln703_reg_1502 <= grp_fu_1231_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln444_fu_660_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                and_ln118_reg_1428 <= and_ln118_fu_714_p2;
                and_ln512_reg_1449 <= and_ln512_fu_805_p2;
                or_ln457_reg_1442 <= or_ln457_fu_800_p2;
                trunc_ln458_reg_1437 <= trunc_ln458_fu_796_p1;
                x_reg_1432 <= x_fu_788_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                and_ln118_reg_1428_pp0_iter1_reg <= and_ln118_reg_1428;
                and_ln512_reg_1449_pp0_iter1_reg <= and_ln512_reg_1449;
                icmp_ln444_reg_1419 <= icmp_ln444_fu_660_p2;
                icmp_ln444_reg_1419_pp0_iter1_reg <= icmp_ln444_reg_1419;
                or_ln457_reg_1442_pp0_iter1_reg <= or_ln457_reg_1442;
                right_border_buf_0_19_reg_1453 <= ap_sig_allocacmp_right_border_buf_0_19;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                and_ln512_reg_1449_pp0_iter2_reg <= and_ln512_reg_1449_pp0_iter1_reg;
                and_ln512_reg_1449_pp0_iter3_reg <= and_ln512_reg_1449_pp0_iter2_reg;
                and_ln512_reg_1449_pp0_iter4_reg <= and_ln512_reg_1449_pp0_iter3_reg;
                icmp_ln444_reg_1419_pp0_iter2_reg <= icmp_ln444_reg_1419_pp0_iter1_reg;
                src_kernel_win_0_va_23_reg_1483 <= src_kernel_win_0_va_23_fu_942_p3;
                src_kernel_win_0_va_23_reg_1483_pp0_iter3_reg <= src_kernel_win_0_va_23_reg_1483;
                src_kernel_win_0_va_24_reg_1490 <= src_kernel_win_0_va_24_fu_960_p3;
                src_kernel_win_0_va_24_reg_1490_pp0_iter3_reg <= src_kernel_win_0_va_24_reg_1490;
                src_kernel_win_0_va_25_reg_1496 <= src_kernel_win_0_va_25_fu_978_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_V_reg_1370 <= i_V_fu_374_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln443_fu_368_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                icmp_ln879_1_reg_1393 <= icmp_ln879_1_fu_414_p2;
                icmp_ln879_reg_1389 <= icmp_ln879_fu_408_p2;
                icmp_ln887_reg_1375 <= icmp_ln887_fu_380_p2;
                icmp_ln899_1_reg_1397 <= icmp_ln899_1_fu_420_p2;
                icmp_ln899_reg_1384 <= icmp_ln899_fu_402_p2;
                xor_ln457_reg_1379 <= xor_ln457_fu_386_p2;
                xor_ln493_1_reg_1404 <= xor_ln493_1_fu_574_p2;
                xor_ln493_2_reg_1409 <= xor_ln493_2_fu_612_p2;
                xor_ln493_3_reg_1414 <= xor_ln493_3_fu_650_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln444_reg_1419 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                k_buf_0_val_4_addr_reg_1471 <= zext_ln835_fu_816_p1(11 - 1 downto 0);
                k_buf_0_val_5_addr_reg_1477 <= zext_ln835_fu_816_p1(11 - 1 downto 0);
                xor_ln493_reg_1464 <= xor_ln493_fu_823_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln512_reg_1449_pp0_iter2_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                mul_ln1118_4_reg_1512 <= mul_ln1118_4_fu_1032_p2;
                mul_ln1118_5_reg_1518 <= mul_ln1118_5_fu_1041_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln512_reg_1449_pp0_iter3_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                p_Result_1_reg_1535 <= p_Val2_5_fu_1139_p2(11 downto 11);
                p_Result_s_reg_1524 <= p_Val2_s_fu_1111_p2(11 downto 11);
                p_Val2_5_reg_1530 <= p_Val2_5_fu_1139_p2;
                tmp_41_reg_1541 <= p_Val2_s_fu_1111_p2(11 downto 11);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln887_reg_1375 = ap_const_lv1_1) and (icmp_ln899_reg_1384 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1428_pp0_iter1_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                right_border_buf_0_14_fu_182 <= right_border_buf_0_s_fu_178;
                right_border_buf_0_15_fu_186 <= right_border_buf_0_19_reg_1453;
                right_border_buf_0_16_fu_190 <= col_buf_0_val_1_0_fu_872_p3;
                right_border_buf_0_17_fu_194 <= right_border_buf_0_16_fu_190;
                right_border_buf_0_18_fu_198 <= col_buf_0_val_2_0_fu_889_p3;
                right_border_buf_0_s_fu_178 <= col_buf_0_val_0_0_fu_854_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                sext_ln1118_1_reg_1341 <= sext_ln1118_1_fu_344_p1;
                sext_ln1118_2_reg_1346 <= sext_ln1118_2_fu_348_p1;
                sext_ln1118_3_reg_1356 <= sext_ln1118_3_fu_356_p1;
                sext_ln1118_reg_1336 <= sext_ln1118_fu_340_p1;
                    zext_ln1118_4_reg_1351(3 downto 0) <= zext_ln1118_4_fu_352_p1(3 downto 0);
                    zext_ln1118_5_reg_1361(2 downto 0) <= zext_ln1118_5_fu_360_p1(2 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln444_reg_1419_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                src_kernel_win_0_va_18_fu_158 <= src_kernel_win_0_va_fu_154;
                src_kernel_win_0_va_19_fu_162 <= src_kernel_win_0_va_24_reg_1490;
                src_kernel_win_0_va_20_fu_166 <= src_kernel_win_0_va_19_fu_162;
                src_kernel_win_0_va_21_fu_170 <= src_kernel_win_0_va_25_reg_1496;
                src_kernel_win_0_va_22_fu_174 <= src_kernel_win_0_va_21_fu_170;
                src_kernel_win_0_va_fu_154 <= src_kernel_win_0_va_23_reg_1483;
            end if;
        end if;
    end process;
    zext_ln1118_4_reg_1351(11 downto 4) <= "00000000";
    zext_ln1118_5_reg_1361(10 downto 3) <= "00000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, icmp_ln443_fu_368_p2, ap_CS_fsm_state2, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln443_fu_368_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) and not(((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ImagLoc_x_fu_688_p2 <= std_logic_vector(signed(ap_const_lv12_FFF) + signed(zext_ln444_fu_656_p1));
    add_ln118_fu_618_p2 <= std_logic_vector(unsigned(ap_const_lv2_1) + unsigned(trunc_ln506_fu_426_p1));
    add_ln506_1_fu_506_p2 <= std_logic_vector(signed(ap_const_lv11_7FE) + signed(zext_ln443_fu_364_p1));
    add_ln506_2_fu_532_p2 <= std_logic_vector(signed(ap_const_lv11_7FD) + signed(zext_ln443_fu_364_p1));
    add_ln506_fu_430_p2 <= std_logic_vector(signed(ap_const_lv11_7FF) + signed(zext_ln443_fu_364_p1));
    add_ln507_fu_436_p2 <= std_logic_vector(signed(ap_const_lv2_3) + signed(trunc_ln506_fu_426_p1));
    add_ln703_5_fu_1091_p2 <= std_logic_vector(unsigned(mul_ln1118_5_reg_1518) + unsigned(sext_ln703_3_fu_1085_p1));
    add_ln703_6_fu_1100_p2 <= std_logic_vector(signed(sext_ln703_4_fu_1096_p1) + signed(grp_fu_1252_p3));
    add_ln703_8_fu_1125_p2 <= std_logic_vector(signed(grp_fu_1252_p3) + signed(zext_ln703_fu_1088_p1));
    add_ln703_9_fu_1130_p2 <= std_logic_vector(signed(mul_ln1118_4_reg_1512) + signed(zext_ln703_1_fu_1105_p1));
    and_ln118_1_fu_462_p2 <= (xor_ln118_6_fu_450_p2 and icmp_ln118_fu_456_p2);
    and_ln118_fu_714_p2 <= (xor_ln118_8_fu_702_p2 and icmp_ln118_1_fu_708_p2);
    and_ln144_fu_782_p2 <= (or_ln118_fu_776_p2 and icmp_ln144_fu_746_p2);
    and_ln512_fu_805_p2 <= (icmp_ln899_reg_1384 and icmp_ln891_fu_682_p2);
    and_ln786_fu_1179_p2 <= (tmp_41_reg_1541 and p_Result_1_reg_1535);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state9 <= ap_CS_fsm(3);

    ap_block_pp0_assign_proc : process(ap_CS_fsm, ap_block_pp0_stage0_subdone)
    begin
                ap_block_pp0 <= ((ap_ST_fsm_pp0_stage0 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage0_subdone));
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(p_src_data_stream_V_empty_n, p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, and_ln512_reg_1449_pp0_iter4_reg, ap_predicate_op141_read_state4, ap_predicate_op148_read_state4)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_const_lv1_1 = and_ln512_reg_1449_pp0_iter4_reg) and (p_dst_data_stream_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op148_read_state4 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op141_read_state4 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(p_src_data_stream_V_empty_n, p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, and_ln512_reg_1449_pp0_iter4_reg, ap_predicate_op141_read_state4, ap_predicate_op148_read_state4)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_const_lv1_1 = and_ln512_reg_1449_pp0_iter4_reg) and (p_dst_data_stream_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op148_read_state4 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op141_read_state4 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(p_src_data_stream_V_empty_n, p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, and_ln512_reg_1449_pp0_iter4_reg, ap_predicate_op141_read_state4, ap_predicate_op148_read_state4)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_const_lv1_1 = and_ln512_reg_1449_pp0_iter4_reg) and (p_dst_data_stream_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op148_read_state4 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op141_read_state4 = ap_const_boolean_1)))));
    end process;

        ap_block_state3_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_pp0_stage0_iter1_assign_proc : process(p_src_data_stream_V_empty_n, ap_predicate_op141_read_state4, ap_predicate_op148_read_state4)
    begin
                ap_block_state4_pp0_stage0_iter1 <= (((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op148_read_state4 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op141_read_state4 = ap_const_boolean_1)));
    end process;

        ap_block_state5_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state8_pp0_stage0_iter5_assign_proc : process(p_dst_data_stream_V_full_n, and_ln512_reg_1449_pp0_iter4_reg)
    begin
                ap_block_state8_pp0_stage0_iter5 <= ((ap_const_lv1_1 = and_ln512_reg_1449_pp0_iter4_reg) and (p_dst_data_stream_V_full_n = ap_const_logic_0));
    end process;


    ap_condition_pp0_exit_iter1_state4_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_condition_pp0_exit_iter1_state4 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter1_state4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln443_fu_368_p2, ap_CS_fsm_state2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln443_fu_368_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_operation_135_assign_proc : process(icmp_ln444_reg_1419)
    begin
                ap_enable_operation_135 <= (icmp_ln444_reg_1419 = ap_const_lv1_0);
    end process;


    ap_enable_operation_138_assign_proc : process(icmp_ln444_reg_1419)
    begin
                ap_enable_operation_138 <= (icmp_ln444_reg_1419 = ap_const_lv1_0);
    end process;


    ap_enable_operation_140_assign_proc : process(ap_predicate_op140_load_state4)
    begin
                ap_enable_operation_140 <= (ap_predicate_op140_load_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_142_assign_proc : process(ap_predicate_op142_store_state4)
    begin
                ap_enable_operation_142 <= (ap_predicate_op142_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_144_assign_proc : process(ap_predicate_op144_store_state4)
    begin
                ap_enable_operation_144 <= (ap_predicate_op144_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_146_assign_proc : process(ap_predicate_op146_store_state4)
    begin
                ap_enable_operation_146 <= (ap_predicate_op146_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_149_assign_proc : process(ap_predicate_op149_store_state4)
    begin
                ap_enable_operation_149 <= (ap_predicate_op149_store_state4 = ap_const_boolean_1);
    end process;

        ap_enable_operation_159 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_162 <= (ap_const_boolean_1 = ap_const_boolean_1);

    ap_enable_operation_165_assign_proc : process(or_ln457_reg_1442_pp0_iter1_reg)
    begin
                ap_enable_operation_165 <= (or_ln457_reg_1442_pp0_iter1_reg = ap_const_lv1_1);
    end process;


    ap_enable_operation_170_assign_proc : process(ap_predicate_op170_store_state5)
    begin
                ap_enable_operation_170 <= (ap_predicate_op170_store_state5 = ap_const_boolean_1);
    end process;


    ap_enable_operation_171_assign_proc : process(ap_predicate_op171_store_state5)
    begin
                ap_enable_operation_171 <= (ap_predicate_op171_store_state5 = ap_const_boolean_1);
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_state4_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
                ap_enable_state4_pp0_iter1_stage0 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state5_pp0_iter2_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2)
    begin
                ap_enable_state5_pp0_iter2_stage0 <= ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op140_load_state4_assign_proc : process(icmp_ln444_reg_1419, or_ln457_reg_1442)
    begin
                ap_predicate_op140_load_state4 <= ((or_ln457_reg_1442 = ap_const_lv1_1) and (icmp_ln444_reg_1419 = ap_const_lv1_0));
    end process;


    ap_predicate_op141_read_state4_assign_proc : process(icmp_ln444_reg_1419, and_ln118_reg_1428, icmp_ln899_reg_1384)
    begin
                ap_predicate_op141_read_state4 <= ((ap_const_lv1_1 = and_ln118_reg_1428) and (icmp_ln899_reg_1384 = ap_const_lv1_0) and (icmp_ln444_reg_1419 = ap_const_lv1_0));
    end process;


    ap_predicate_op142_store_state4_assign_proc : process(icmp_ln444_reg_1419, and_ln118_reg_1428, icmp_ln899_reg_1384, icmp_ln879_reg_1389)
    begin
                ap_predicate_op142_store_state4 <= ((icmp_ln879_reg_1389 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1428) and (icmp_ln899_reg_1384 = ap_const_lv1_0) and (icmp_ln444_reg_1419 = ap_const_lv1_0));
    end process;


    ap_predicate_op144_store_state4_assign_proc : process(icmp_ln444_reg_1419, and_ln118_reg_1428, icmp_ln899_reg_1384, icmp_ln879_1_reg_1393)
    begin
                ap_predicate_op144_store_state4 <= ((icmp_ln879_1_reg_1393 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1428) and (icmp_ln899_reg_1384 = ap_const_lv1_0) and (icmp_ln444_reg_1419 = ap_const_lv1_0));
    end process;


    ap_predicate_op146_store_state4_assign_proc : process(icmp_ln444_reg_1419, and_ln118_reg_1428, icmp_ln899_reg_1384, icmp_ln879_reg_1389)
    begin
                ap_predicate_op146_store_state4 <= ((icmp_ln879_reg_1389 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1428) and (icmp_ln899_reg_1384 = ap_const_lv1_0) and (icmp_ln444_reg_1419 = ap_const_lv1_0));
    end process;


    ap_predicate_op148_read_state4_assign_proc : process(icmp_ln444_reg_1419, and_ln118_reg_1428, icmp_ln899_reg_1384, icmp_ln887_reg_1375)
    begin
                ap_predicate_op148_read_state4 <= ((icmp_ln887_reg_1375 = ap_const_lv1_1) and (icmp_ln899_reg_1384 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1428) and (icmp_ln444_reg_1419 = ap_const_lv1_0));
    end process;


    ap_predicate_op149_store_state4_assign_proc : process(icmp_ln444_reg_1419, and_ln118_reg_1428, icmp_ln899_reg_1384, icmp_ln887_reg_1375)
    begin
                ap_predicate_op149_store_state4 <= ((icmp_ln887_reg_1375 = ap_const_lv1_1) and (icmp_ln899_reg_1384 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1428) and (icmp_ln444_reg_1419 = ap_const_lv1_0));
    end process;


    ap_predicate_op170_store_state5_assign_proc : process(icmp_ln899_reg_1384, icmp_ln887_reg_1375, and_ln118_reg_1428_pp0_iter1_reg)
    begin
                ap_predicate_op170_store_state5 <= ((icmp_ln887_reg_1375 = ap_const_lv1_1) and (icmp_ln899_reg_1384 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1428_pp0_iter1_reg));
    end process;


    ap_predicate_op171_store_state5_assign_proc : process(icmp_ln899_reg_1384, icmp_ln887_reg_1375, and_ln118_reg_1428_pp0_iter1_reg)
    begin
                ap_predicate_op171_store_state5 <= ((icmp_ln887_reg_1375 = ap_const_lv1_1) and (icmp_ln899_reg_1384 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1428_pp0_iter1_reg));
    end process;


    ap_ready_assign_proc : process(icmp_ln443_fu_368_p2, ap_CS_fsm_state2)
    begin
        if (((icmp_ln443_fu_368_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_right_border_buf_0_19_assign_proc : process(ap_block_pp0_stage0, icmp_ln899_reg_1384, icmp_ln887_reg_1375, and_ln118_reg_1428_pp0_iter1_reg, ap_enable_reg_pp0_iter2, right_border_buf_0_18_fu_198, col_buf_0_val_2_0_fu_889_p3)
    begin
        if (((icmp_ln887_reg_1375 = ap_const_lv1_1) and (icmp_ln899_reg_1384 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1428_pp0_iter1_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_sig_allocacmp_right_border_buf_0_19 <= col_buf_0_val_2_0_fu_889_p3;
        else 
            ap_sig_allocacmp_right_border_buf_0_19 <= right_border_buf_0_18_fu_198;
        end if; 
    end process;


    ap_sig_allocacmp_src_kernel_win_0_va_29_assign_proc : process(ap_block_pp0_stage0, icmp_ln444_reg_1419_pp0_iter2_reg, src_kernel_win_0_va_25_reg_1496, ap_enable_reg_pp0_iter3, src_kernel_win_0_va_21_fu_170)
    begin
        if (((icmp_ln444_reg_1419_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_src_kernel_win_0_va_29 <= src_kernel_win_0_va_25_reg_1496;
        else 
            ap_sig_allocacmp_src_kernel_win_0_va_29 <= src_kernel_win_0_va_21_fu_170;
        end if; 
    end process;


    ap_sig_allocacmp_src_kernel_win_0_va_30_assign_proc : process(ap_block_pp0_stage0, icmp_ln444_reg_1419_pp0_iter2_reg, ap_enable_reg_pp0_iter3, src_kernel_win_0_va_21_fu_170, src_kernel_win_0_va_22_fu_174)
    begin
        if (((icmp_ln444_reg_1419_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_src_kernel_win_0_va_30 <= src_kernel_win_0_va_21_fu_170;
        else 
            ap_sig_allocacmp_src_kernel_win_0_va_30 <= src_kernel_win_0_va_22_fu_174;
        end if; 
    end process;

    col_buf_0_val_0_0_fu_854_p3 <= 
        k_buf_0_val_3_q0 when (or_ln457_reg_1442_pp0_iter1_reg(0) = '1') else 
        tmp_4_fu_843_p5;
    col_buf_0_val_1_0_fu_872_p3 <= 
        k_buf_0_val_4_q0 when (or_ln457_reg_1442_pp0_iter1_reg(0) = '1') else 
        tmp_5_fu_861_p5;
    col_buf_0_val_2_0_fu_889_p3 <= 
        k_buf_0_val_5_q0 when (or_ln457_reg_1442_pp0_iter1_reg(0) = '1') else 
        tmp_6_fu_879_p5;
    grp_fu_1231_p0 <= grp_fu_1231_p00(8 - 1 downto 0);
    grp_fu_1231_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_src_kernel_win_0_va_29),10));
    grp_fu_1231_p1 <= sext_ln1118_reg_1336(2 - 1 downto 0);
    grp_fu_1238_p0 <= grp_fu_1238_p00(8 - 1 downto 0);
    grp_fu_1238_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_25_reg_1496),10));
    grp_fu_1238_p1 <= sext_ln1118_1_reg_1341(2 - 1 downto 0);
    grp_fu_1245_p0 <= grp_fu_1245_p00(8 - 1 downto 0);
    grp_fu_1245_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_20_fu_166),11));
    grp_fu_1245_p1 <= sext_ln1118_2_reg_1346(3 - 1 downto 0);
    grp_fu_1252_p0 <= grp_fu_1252_p00(8 - 1 downto 0);
    grp_fu_1252_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_24_reg_1490_pp0_iter3_reg),12));
    grp_fu_1252_p1 <= zext_ln1118_4_reg_1351(4 - 1 downto 0);
    i_V_fu_374_p2 <= std_logic_vector(unsigned(t_V_reg_318) + unsigned(ap_const_lv10_1));
    icmp_ln118_1_fu_708_p2 <= "1" when (signed(ImagLoc_x_fu_688_p2) < signed(ap_const_lv12_500)) else "0";
    icmp_ln118_fu_456_p2 <= "1" when (signed(add_ln506_fu_430_p2) < signed(ap_const_lv11_2D0)) else "0";
    icmp_ln144_1_fu_494_p2 <= "1" when (signed(select_ln139_1_fu_482_p3) < signed(ap_const_lv11_2D0)) else "0";
    icmp_ln144_fu_746_p2 <= "1" when (signed(select_ln139_fu_734_p3) < signed(ap_const_lv12_500)) else "0";
    icmp_ln443_fu_368_p2 <= "1" when (t_V_reg_318 = ap_const_lv10_2D2) else "0";
    icmp_ln444_fu_660_p2 <= "1" when (t_V_2_reg_329 = ap_const_lv11_502) else "0";
    icmp_ln879_1_fu_414_p2 <= "1" when (t_V_reg_318 = ap_const_lv10_0) else "0";
    icmp_ln879_fu_408_p2 <= "1" when (t_V_reg_318 = ap_const_lv10_1) else "0";
    icmp_ln887_fu_380_p2 <= "1" when (unsigned(t_V_reg_318) < unsigned(ap_const_lv10_2D0)) else "0";
    icmp_ln891_fu_682_p2 <= "0" when (tmp_34_fu_672_p4 = ap_const_lv10_0) else "1";
    icmp_ln899_1_fu_420_p2 <= "1" when (unsigned(t_V_reg_318) > unsigned(ap_const_lv10_2D0)) else "0";
    icmp_ln899_fu_402_p2 <= "0" when (tmp_fu_392_p4 = ap_const_lv9_0) else "1";
    j_V_fu_666_p2 <= std_logic_vector(unsigned(t_V_2_reg_329) + unsigned(ap_const_lv11_1));
    k_buf_0_val_3_address0 <= zext_ln835_fu_816_p1(11 - 1 downto 0);
    k_buf_0_val_3_address1 <= zext_ln835_fu_816_p1(11 - 1 downto 0);

    k_buf_0_val_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln444_reg_1419, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln444_reg_1419 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_3_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_3_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_3_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_3_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln444_reg_1419, and_ln118_reg_1428, icmp_ln899_reg_1384, icmp_ln879_reg_1389, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln879_reg_1389 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1428) and (icmp_ln899_reg_1384 = ap_const_lv1_0) and (icmp_ln444_reg_1419 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_3_we0 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_3_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln444_reg_1419, and_ln118_reg_1428, icmp_ln899_reg_1384, icmp_ln887_reg_1375, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln887_reg_1375 = ap_const_lv1_1) and (icmp_ln899_reg_1384 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1428) and (icmp_ln444_reg_1419 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_3_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_we1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_4_address0 <= zext_ln835_fu_816_p1(11 - 1 downto 0);
    k_buf_0_val_4_address1 <= k_buf_0_val_4_addr_reg_1471;

    k_buf_0_val_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln444_reg_1419, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln444_reg_1419 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_4_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_4_ce1_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_4_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_4_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln444_reg_1419, and_ln118_reg_1428, icmp_ln899_reg_1384, icmp_ln879_1_reg_1393, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln879_1_reg_1393 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1428) and (icmp_ln899_reg_1384 = ap_const_lv1_0) and (icmp_ln444_reg_1419 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_4_we0 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_we0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_4_we1_assign_proc : process(icmp_ln899_reg_1384, icmp_ln887_reg_1375, ap_block_pp0_stage0_11001, and_ln118_reg_1428_pp0_iter1_reg, ap_enable_reg_pp0_iter2)
    begin
        if (((icmp_ln887_reg_1375 = ap_const_lv1_1) and (icmp_ln899_reg_1384 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1428_pp0_iter1_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_4_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_we1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_5_address0 <= zext_ln835_fu_816_p1(11 - 1 downto 0);
    k_buf_0_val_5_address1 <= k_buf_0_val_5_addr_reg_1477;

    k_buf_0_val_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln444_reg_1419, and_ln118_reg_1428, icmp_ln899_reg_1384, icmp_ln879_reg_1389, ap_block_pp0_stage0_11001, or_ln457_reg_1442)
    begin
        if ((((icmp_ln879_reg_1389 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1428) and (icmp_ln899_reg_1384 = ap_const_lv1_0) and (icmp_ln444_reg_1419 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((or_ln457_reg_1442 = ap_const_lv1_1) and (icmp_ln444_reg_1419 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            k_buf_0_val_5_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_5_ce1_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_5_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_5_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln444_reg_1419, and_ln118_reg_1428, icmp_ln899_reg_1384, icmp_ln879_reg_1389, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln879_reg_1389 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1428) and (icmp_ln899_reg_1384 = ap_const_lv1_0) and (icmp_ln444_reg_1419 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_5_we0 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_we0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_5_we1_assign_proc : process(icmp_ln899_reg_1384, icmp_ln887_reg_1375, ap_block_pp0_stage0_11001, and_ln118_reg_1428_pp0_iter1_reg, ap_enable_reg_pp0_iter2)
    begin
        if (((icmp_ln887_reg_1375 = ap_const_lv1_1) and (icmp_ln899_reg_1384 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1428_pp0_iter1_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_5_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_we1 <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln1118_4_fu_1032_p0 <= mul_ln1118_4_fu_1032_p00(8 - 1 downto 0);
    mul_ln1118_4_fu_1032_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_18_fu_158),10));
    mul_ln1118_4_fu_1032_p1 <= sext_ln1118_3_reg_1356(2 - 1 downto 0);
    mul_ln1118_4_fu_1032_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &mul_ln1118_4_fu_1032_p0) * signed(mul_ln1118_4_fu_1032_p1))), 10));
    mul_ln1118_5_fu_1041_p0 <= mul_ln1118_5_fu_1041_p00(8 - 1 downto 0);
    mul_ln1118_5_fu_1041_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_fu_154),11));
    mul_ln1118_5_fu_1041_p1 <= zext_ln1118_5_reg_1361(3 - 1 downto 0);
    mul_ln1118_5_fu_1041_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1118_5_fu_1041_p0) * unsigned(mul_ln1118_5_fu_1041_p1), 11));
    or_ln118_fu_776_p2 <= (xor_ln118_9_fu_770_p2 or tmp_35_fu_694_p3);
    or_ln340_1_fu_1200_p2 <= (xor_ln785_fu_1168_p2 or and_ln786_fu_1179_p2);
    or_ln340_fu_1194_p2 <= (underflow_fu_1189_p2 or overflow_fu_1173_p2);
    or_ln457_fu_800_p2 <= (xor_ln457_reg_1379 or icmp_ln118_1_fu_708_p2);
    or_ln785_fu_1164_p2 <= (tmp_41_reg_1541 or p_Result_1_reg_1535);
    overflow_fu_1173_p2 <= (xor_ln785_fu_1168_p2 and or_ln785_fu_1164_p2);
    p_Val2_5_fu_1139_p2 <= std_logic_vector(signed(sext_ln703_5_fu_1135_p1) + signed(add_ln703_8_fu_1125_p2));
    p_Val2_s_fu_1111_p2 <= std_logic_vector(unsigned(add_ln703_6_fu_1100_p2) + unsigned(zext_ln703_2_fu_1108_p1));

    p_dst_data_stream_V_blk_n_assign_proc : process(p_dst_data_stream_V_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter5, and_ln512_reg_1449_pp0_iter4_reg)
    begin
        if (((ap_const_lv1_1 = and_ln512_reg_1449_pp0_iter4_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            p_dst_data_stream_V_blk_n <= p_dst_data_stream_V_full_n;
        else 
            p_dst_data_stream_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    p_dst_data_stream_V_din <= 
        select_ln340_fu_1206_p3 when (or_ln340_1_fu_1200_p2(0) = '1') else 
        select_ln388_fu_1214_p3;

    p_dst_data_stream_V_write_assign_proc : process(ap_enable_reg_pp0_iter5, and_ln512_reg_1449_pp0_iter4_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_lv1_1 = and_ln512_reg_1449_pp0_iter4_reg) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_dst_data_stream_V_write <= ap_const_logic_1;
        else 
            p_dst_data_stream_V_write <= ap_const_logic_0;
        end if; 
    end process;


    p_src_data_stream_V_blk_n_assign_proc : process(p_src_data_stream_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln444_reg_1419, and_ln118_reg_1428, icmp_ln899_reg_1384, icmp_ln887_reg_1375)
    begin
        if ((((icmp_ln887_reg_1375 = ap_const_lv1_1) and (icmp_ln899_reg_1384 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1428) and (icmp_ln444_reg_1419 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_lv1_1 = and_ln118_reg_1428) and (icmp_ln899_reg_1384 = ap_const_lv1_0) and (icmp_ln444_reg_1419 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            p_src_data_stream_V_blk_n <= p_src_data_stream_V_empty_n;
        else 
            p_src_data_stream_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_src_data_stream_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op141_read_state4, ap_predicate_op148_read_state4, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op148_read_state4 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op141_read_state4 = ap_const_boolean_1)))) then 
            p_src_data_stream_V_read <= ap_const_logic_1;
        else 
            p_src_data_stream_V_read <= ap_const_logic_0;
        end if; 
    end process;

    select_ln118_1_fu_642_p3 <= 
        select_ln139_5_fu_634_p3 when (tmp_32_fu_538_p3(0) = '1') else 
        add_ln118_fu_618_p2;
    select_ln118_3_fu_758_p3 <= 
        ImagLoc_x_fu_688_p2 when (and_ln118_fu_714_p2(0) = '1') else 
        sub_ln147_fu_752_p2;
    select_ln118_fu_604_p3 <= 
        select_ln139_4_fu_596_p3 when (tmp_30_fu_512_p3(0) = '1') else 
        xor_ln118_1_fu_580_p2;
    select_ln139_1_fu_482_p3 <= 
        sub_ln142_fu_476_p2 when (tmp_29_fu_468_p3(0) = '1') else 
        add_ln506_fu_430_p2;
    select_ln139_4_fu_596_p3 <= 
        sub_ln118_fu_586_p2 when (tmp_31_fu_520_p3(0) = '1') else 
        trunc_ln118_fu_592_p1;
    select_ln139_5_fu_634_p3 <= 
        xor_ln118_7_fu_624_p2 when (tmp_33_fu_546_p3(0) = '1') else 
        trunc_ln118_2_fu_630_p1;
    select_ln139_fu_734_p3 <= 
        sub_ln142_2_fu_728_p2 when (tmp_36_fu_720_p3(0) = '1') else 
        ImagLoc_x_fu_688_p2;
    select_ln340_fu_1206_p3 <= 
        ap_const_lv16_7FFF when (or_ln340_fu_1194_p2(0) = '1') else 
        sext_ln703_6_fu_1161_p1;
    select_ln388_fu_1214_p3 <= 
        ap_const_lv16_8000 when (underflow_fu_1189_p2(0) = '1') else 
        sext_ln703_6_fu_1161_p1;
    select_ln507_1_fu_566_p3 <= 
        add_ln507_fu_436_p2 when (and_ln118_1_fu_462_p2(0) = '1') else 
        select_ln507_fu_558_p3;
    select_ln507_fu_558_p3 <= 
        trunc_ln507_fu_490_p1 when (icmp_ln144_1_fu_494_p2(0) = '1') else 
        sub_ln507_fu_500_p2;
        sext_ln1118_1_fu_344_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_kernel_val_0_V_2_read),10));

        sext_ln1118_2_fu_348_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_kernel_val_1_V_0_read),11));

        sext_ln1118_3_fu_356_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_kernel_val_2_V_0_read),10));

        sext_ln1118_fu_340_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_kernel_val_0_V_1_read),10));

        sext_ln139_fu_742_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln139_fu_734_p3),13));

        sext_ln144_fu_813_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_reg_1432),32));

        sext_ln703_3_fu_1085_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln1118_4_reg_1512),11));

        sext_ln703_4_fu_1096_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln703_5_fu_1091_p2),12));

        sext_ln703_5_fu_1135_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln703_9_fu_1130_p2),12));

        sext_ln703_6_fu_1161_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_5_reg_1530),16));

    src_kernel_win_0_va_23_fu_942_p3 <= 
        tmp_7_fu_931_p5 when (icmp_ln899_1_reg_1397(0) = '1') else 
        col_buf_0_val_0_0_fu_854_p3;
    src_kernel_win_0_va_24_fu_960_p3 <= 
        tmp_8_fu_949_p5 when (icmp_ln899_1_reg_1397(0) = '1') else 
        col_buf_0_val_1_0_fu_872_p3;
    src_kernel_win_0_va_25_fu_978_p3 <= 
        tmp_9_fu_967_p5 when (icmp_ln899_1_reg_1397(0) = '1') else 
        col_buf_0_val_2_0_fu_889_p3;
    sub_ln1118_fu_995_p2 <= std_logic_vector(unsigned(ap_const_lv9_0) - unsigned(zext_ln1118_fu_991_p1));
    sub_ln118_fu_586_p2 <= std_logic_vector(signed(ap_const_lv2_2) - signed(trunc_ln142_fu_528_p1));
    sub_ln142_2_fu_728_p2 <= std_logic_vector(unsigned(ap_const_lv12_1) - unsigned(zext_ln444_fu_656_p1));
    sub_ln142_fu_476_p2 <= std_logic_vector(unsigned(ap_const_lv11_1) - unsigned(zext_ln443_fu_364_p1));
    sub_ln147_fu_752_p2 <= std_logic_vector(signed(ap_const_lv12_9FE) - signed(select_ln139_fu_734_p3));
    sub_ln507_fu_500_p2 <= std_logic_vector(signed(ap_const_lv2_2) - signed(trunc_ln507_fu_490_p1));
    tmp_28_fu_442_p3 <= add_ln506_fu_430_p2(10 downto 10);
    tmp_29_fu_468_p3 <= add_ln506_fu_430_p2(10 downto 10);
    tmp_30_fu_512_p3 <= add_ln506_1_fu_506_p2(10 downto 10);
    tmp_31_fu_520_p3 <= add_ln506_1_fu_506_p2(10 downto 10);
    tmp_32_fu_538_p3 <= add_ln506_2_fu_532_p2(10 downto 10);
    tmp_33_fu_546_p3 <= add_ln506_2_fu_532_p2(10 downto 10);
    tmp_34_fu_672_p4 <= t_V_2_reg_329(10 downto 1);
    tmp_35_fu_694_p3 <= ImagLoc_x_fu_688_p2(11 downto 11);
    tmp_36_fu_720_p3 <= ImagLoc_x_fu_688_p2(11 downto 11);
    tmp_fu_392_p4 <= t_V_reg_318(9 downto 1);
    trunc_ln118_2_fu_630_p1 <= add_ln506_2_fu_532_p2(2 - 1 downto 0);
    trunc_ln118_fu_592_p1 <= add_ln506_1_fu_506_p2(2 - 1 downto 0);
    trunc_ln142_2_fu_554_p1 <= t_V_reg_318(2 - 1 downto 0);
    trunc_ln142_fu_528_p1 <= t_V_reg_318(2 - 1 downto 0);
    trunc_ln458_fu_796_p1 <= x_fu_788_p3(2 - 1 downto 0);
    trunc_ln506_fu_426_p1 <= t_V_reg_318(2 - 1 downto 0);
    trunc_ln507_fu_490_p1 <= select_ln139_1_fu_482_p3(2 - 1 downto 0);
    underflow_fu_1189_p2 <= (xor_ln786_fu_1183_p2 and p_Result_s_reg_1524);
    x_fu_788_p3 <= 
        sext_ln139_fu_742_p1 when (and_ln144_fu_782_p2(0) = '1') else 
        zext_ln118_fu_766_p1;
    xor_ln118_1_fu_580_p2 <= (trunc_ln506_fu_426_p1 xor ap_const_lv2_2);
    xor_ln118_6_fu_450_p2 <= (tmp_28_fu_442_p3 xor ap_const_lv1_1);
    xor_ln118_7_fu_624_p2 <= (trunc_ln142_2_fu_554_p1 xor ap_const_lv2_3);
    xor_ln118_8_fu_702_p2 <= (tmp_35_fu_694_p3 xor ap_const_lv1_1);
    xor_ln118_9_fu_770_p2 <= (icmp_ln118_1_fu_708_p2 xor ap_const_lv1_1);
    xor_ln457_fu_386_p2 <= (icmp_ln887_fu_380_p2 xor ap_const_lv1_1);
    xor_ln493_1_fu_574_p2 <= (select_ln507_1_fu_566_p3 xor ap_const_lv2_3);
    xor_ln493_2_fu_612_p2 <= (select_ln118_fu_604_p3 xor ap_const_lv2_3);
    xor_ln493_3_fu_650_p2 <= (select_ln118_1_fu_642_p3 xor ap_const_lv2_3);
    xor_ln493_fu_823_p2 <= (trunc_ln458_reg_1437 xor ap_const_lv2_3);
    xor_ln785_fu_1168_p2 <= (p_Result_s_reg_1524 xor ap_const_lv1_1);
    xor_ln786_fu_1183_p2 <= (ap_const_lv1_1 xor and_ln786_fu_1179_p2);
    zext_ln1118_4_fu_352_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_kernel_val_1_V_2_read),12));
    zext_ln1118_5_fu_360_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_kernel_val_2_V_1_read),11));
    zext_ln1118_fu_991_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_src_kernel_win_0_va_30),9));
    zext_ln118_fu_766_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln118_3_fu_758_p3),13));
    zext_ln443_fu_364_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_V_reg_318),11));
    zext_ln444_fu_656_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_V_2_reg_329),12));
    zext_ln703_1_fu_1105_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_23_reg_1483_pp0_iter3_reg),10));
    zext_ln703_2_fu_1108_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_23_reg_1483_pp0_iter3_reg),12));
    zext_ln703_fu_1088_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1118_5_reg_1518),12));
    zext_ln835_fu_816_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln144_fu_813_p1),64));
end behav;
